### ISSUE TITLE
'Personalise your results' section 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#110]
As a user, I want to be able to personalise my results to tailor my search more to my current situation so that I get the most relevant suggestions

- [x] Filter section that is currently reached by 'Filter' button and side panel - now to be displayed on page in series of questions
- [x] Questions are existing ones from the filters, Q1 is specific to the overall topic tag of the page, Q2 and Q3 are global
- [x] Questions either side greyed out and can be reached on click
- [x] Questions either side are not visible on mobile
- [x] Side side swiping on mobile with animation
- [x] Session storage to remember a person's search preferences if they return to that homepage
- [x] Styled as per mock-ups in this issue

Currently no 'see more' button needed to see more tags/options, but this may change in future

**Comment by Danwhy** [comment]
![sleep-landingpage-questions](https://user-images.githubusercontent.com/26305143/29033327-914ac2c0-7b8c-11e7-9d8a-1b7b716a22f3.png)

**Comment by Danwhy** [comment]
@ellemindwave I've just noticed that the searchbar isn't on the mockup. Do we want this section to come above or below the search?

**Comment by ellemindwave** [comment]
@Danwhy Good point. 

My understanding is that these topic pages and the links in to them are an alternative to the search bar. 
The search feature would still exist on the global homepage, but these landing pages are the result of the user already having clicked through from the main homepage by way of the nav bar, which is equivalent to having performed a search... 

Therefore, the search bar is not needed on these bespoke topic landing pages.

This is my understanding, and would need Sarah to confirm, but as she has made these mock-ups this way, I'm sure she would have thought about this in depth! So safe to go ahead as the mock-ups show. 

Mock-ups for the 'global homepage' will be done this sprint ready for next sprint.
