### ISSUE TITLE
Reviews using 'Disqus'

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#116]
As a service provider, I want to be able to gather reviews on the resources from users, so that I can start to gather feedback and improve the service

- [x] Set up Disqus
- [x] Embed onto the resource pages, with out the box functionality
- [x] Show a 'Comments' box (as per screenshots)
- [x] Show all comments per resource (can be reviewed when we have more content)
- [ ] Set up pre-moderation for comments

![screen shot 2017-08-10 at 11 53 29](https://user-images.githubusercontent.com/26304634/29167502-92209f48-7dc2-11e7-92f8-039545d0e902.png)

**Comment by samhstn** [comment]
Perhaps we should close this one and work from smaller issues #177 and #178 for disqus

**Comment by ellemindwave** [comment]
Good shout, @shouston3. Will do
