### ISSUE TITLE
Create multiple tag types

### ISSUE THREAD

**Issue by Danwhy** [LDMW/cms#14]
* [x] - Main tags
* [x] - Audience/Demographic tags
* [x] - Content Type tags

**Comment by nelsonic** [comment]
@Danwhy _ideally_ we should get this requirement from the Product Owner
(_or at least get **confirmation** of the need in the form of a comment `before` building it..._) 👍

**Comment by samhstn** [comment]
This is quite out of date, closing as it was addressed in https://github.com/LDMW/cms/pull/15
