### ISSUE TITLE
Full Resource set a little slow to load

### ISSUE THREAD

**Issue by Danwhy** [LDMW/cms#156]
When all the resources are coming through (no filter), it takes a while for them to appear, so there are 0 results for a few seconds. 

There are a few ways we could make this better: 
* Improve the filtering logic on the backend to make it faster
* Load only the first three resources at first, then lazy load the rest
* Have it say 'Loading Resources' instead of 0 resources

In my opinion, implementing all three of these would be best, with lazy loading having the biggest effect and therefore taking priority

**Comment by Danwhy** [comment]
Also relevant to: #173, as lazy loading and pagination will have shared logic

**Comment by samhstn** [comment]
Loads super fast now @Danwhy 👍 
Can we close this?

**Comment by Danwhy** [comment]
:+1: We're now lazy loading the resources
