### ISSUE TITLE
Add relevant fields to wagtail for resources

### ISSUE THREAD

**Issue by Danwhy** [LDMW/cms#16]
<img width="367" alt="screen shot 2017-04-28 at 12 38 04" src="https://cloud.githubusercontent.com/assets/8939909/25527213/9cc259e6-2c0f-11e7-92fd-6dcae3cfabd8.png">

- [x] heading
- [x] tags
- [x] link
- [x] body

**Comment by nelsonic** [comment]
@Danwhy looks good. 😍 
Please get Product Owner feedback/approval before building your next feature. 😉  
(_I know you're just "getting on with it" - which is superb! - but we need to get everyone on our team(s) in the habit of communicating better with Product Owners. thanks!_)

**Comment by samhstn** [comment]
Out of date and was addressed in #17 , closing
