### ISSUE TITLE
Remove greyed out 'previous question' on 1st question card

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#169]
- [x] no greyed out 'previous question' button on 1st question of 'personalise your results' question

**Comment by reddog** [comment]
![image](https://user-images.githubusercontent.com/151362/29619603-639bf6d0-8813-11e7-907b-d82170b2e79d.png)

**Comment by samhstn** [comment]
Removed first previous question on the [staging site](https://ldmw-staging.herokuapp.com/)

![screen shot 2017-08-29 at 12 34 32](https://user-images.githubusercontent.com/15983736/29818972-79fb171a-8cb6-11e7-9c4a-eaced57be28a.png)
