### ISSUE TITLE
Adding 'search' button on 3rd question

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#170]
On 3rd/last question of 'personalise your results' section:

- [x] no 'next question' button
- [x] should have 'search' button
- [x] clicking on 'search' button should jump user to the top of the search results
- [x] styled according to rest of the site

**Comment by reddog** [comment]
![image](https://user-images.githubusercontent.com/151362/29619666-8af7d668-8813-11e7-8a39-447a60b91def.png)

**Comment by ellemindwave** [comment]
** changing priority of this @Danwhy @Cleop @shouston3 seeing as the site is now live and this is quite crucial to user journey

**Comment by samhstn** [comment]
Should be up and running on the [staging site](https://ldmw-staging.herokuapp.com/)

![screen shot 2017-08-29 at 12 25 48](https://user-images.githubusercontent.com/15983736/29818642-3f3be25e-8cb5-11e7-8fb2-49b66f340f2d.png)

**Comment by ellemindwave** [comment]
@shouston3 I have looked on both staging sites and cannot see this change.. for the sake of being absolutely clear, please can let us know which staging site is being used at the moment? Is it http://ldmw.herokuapp.com/ or https://ldmw-app-staging.herokuapp.com/ ?
