### ISSUE TITLE
Remove old search bar section

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#171]
- [x] Remove second search section from homepage
- [x] Will be replaced by the content cubes

![screen shot 2017-08-24 at 11 04 59](https://user-images.githubusercontent.com/26304634/29661523-3181a434-88bc-11e7-8f6a-5559c878037c.png)

**Comment by samhstn** [comment]
Wireframes for content cubes required #209

**Comment by ellemindwave** [comment]
![screen shot 2017-08-24 at 11 27 06](https://user-images.githubusercontent.com/26304634/29662419-34afb4b8-88bf-11e7-98c2-524d988a28c9.png)

**Comment by Danwhy** [comment]
Live on http://ldmw-staging.herokuapp.com/
