### ISSUE TITLE
Pagination for resources

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#173]
See @reddog 's comment below

**Comment by reddog** [comment]
All resources are currently loaded within a page - they are just hidden to display the first three.  Clicking `See More` then displays these hidden resources.

Issue to consider just having those required within the page and load others over AJAX in a paged manner (no decision made on "page" size).

**Comment by samhstn** [comment]
Initial discussion about this was had here: https://github.com/LDMW/app/issues/262

**Comment by samhstn** [comment]
Is this for discussion or implementation in this milestone?

**Comment by Cleop** [comment]
@ellemindwave @sarahwelton @reddog - would you like the team to implement this during this sprint? If so, how many resources should be displayed per page? 5?

**Comment by ellemindwave** [comment]
@Cleop I have been discussing this with @reddog and it seems that for this sprint, the easiest thing to do which requires least work is to up the dynos on the Heroku account. 

We will set up a Heroku account and then transfer over to our account so that the billing etc is all coming from us (which will make Tracy happy! )

Shall I make an issue for the transfer?

**Comment by Cleop** [comment]
Thanks @ellemindwave. Yes, go ahead, or add to #190.

**Comment by ellemindwave** [comment]
@Cleop we currently show 3 resources, and hide the rest?

Just been discussing this with @sarahwelton - The answer to this isn't as simple as only loading 3 resources and then loading the rest in groups of 5 at a time, say, because then the 'personalise my results' section would work by populating the results rather than filtering them down... So a little more thought is needed behind this before we work out what might be the best solution I think.

**Comment by ellemindwave** [comment]
@Cleop @shouston3 @Danwhy 
Another discussion with @sarahwelton about this:

Pagination is not needed at the moment - and doesn't need to be included in the next sprint. 
We think that, with a little bit of tweaking of the wording on the 'showing x results' and the 'order by'  sections that we can make the user experience work fine as it is, and also the page doesn't take too long to load at the moment with the current amount of resources. 
For live, there won't be too many more resources on there, and when they do start to grow and become an issue then we will revisit this issue 👍

**Comment by Cleop** [comment]
Being removed due to time saving element of pagination already being achieved by lazy loading. Still left open for later implementation should it be preferred from a UI perspective.

**Comment by Cleop** [comment]
@sarahwelton @ellemindwave - have you decided yet whether pagination is still something you'd like from a UI perspective or are you happy with 'see more' lazy loading? Just seeing if this issue can now be closed.
