### ISSUE TITLE
Clicking on resource title takes you to the full resource page

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#174]
- [ ] Title should be clickable and take the user straight to the resource
- [ ] Title should have a hover state to show it is clickable

**Comment by reddog** [comment]
For example, in this screen, `Fear Fighter` would be clickable and go to the link shown below:

![image](https://user-images.githubusercontent.com/151362/29619864-1abf1a72-8814-11e7-953e-861607b10285.png)

**Comment by reddog** [comment]
Link has a blue background on mouse-over.  Should title have that too?

![image](https://user-images.githubusercontent.com/151362/29619905-3a021682-8814-11e7-8079-cb34d7a88be7.png)

**Comment by samhstn** [comment]
If @ellemindwave @sarahwelton @indiamindwave24 or you would like that to happen then we can change it to do that. Would you like that to be the case?

**Comment by ellemindwave** [comment]
@indiamindwave24 / @sarahwelton style-wise/UX wise is that hover state okay?

**Comment by ellemindwave** [comment]
@reddog @shouston3 @sarahwelton @indiamindwave24 @Cleop 

From the title of this issue, and our conversations yesterday, I thought that the idea was for clicking on the title of the resource in the search results to take the user to the full resource page for this resource, i.e. the londonminds.co.uk page with reviews and description etc. 

Are we saying that it is actually meant to take the user direct to the third party site?

**Comment by samhstn** [comment]
Each resource currently has:

Title - with no link
Link to 3rd party resource
`Get more info` - linking to full resource page

I thought from the discussions yesterday we would have for each resource:

Title - link to full resource page
Link to 3rd party resource.

@ellemindwave would you like the `Get more info` link to remain? Is the above layout correct?

**Comment by ellemindwave** [comment]
As per the new wireframes - the 'get more info' button is going to disappear, and there will be a button that says 'read reviews and join the discussion' which will take the user to the full resource page.

Perhaps the confusion is because David's screenshots are of the old version.. ?
@indiamindwave24 will be providing UI for the new version soon.

![screen shot 2017-08-24 at 12 01 46](https://user-images.githubusercontent.com/26304634/29713799-329e563c-8998-11e7-83df-859a49048cc7.png)

**Comment by ellemindwave** [comment]
So: 

Title of resource - links to full resource page
Link - links to 3rd party site
'read reviews and join the discusssion' - goes to full resource page

@sarahwelton @indiamindwave24 is that what you are thinking too?
