### ISSUE TITLE
No 'get more info' link for tips

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#175]
see #176 

- [ ] tips should not have the 'get more info' option in search results
- [ ] this will be covered in the redesign of the tips styling

**Comment by reddog** [comment]
![image](https://user-images.githubusercontent.com/151362/29620173-1bd0d8f0-8815-11e7-9a1c-3a96b434b035.png)

`Get More Info` should remain for Resources

**Comment by ellemindwave** [comment]
Closing this issue has it is covered by #176
