### ISSUE TITLE
New 'tips' section on Wagtail

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#176]
- [x] different styling (to follow and time estimates to reflect this)
- [x] no 'get more info' link on tips in search results - see #175 

India doing UI for new homepage and tips section on Friday 25th Aug

**Comment by ellemindwave** [comment]
@Cleop @shouston3 @Danwhy New wireframe from @sarahwelton with example of a tip

![lm-homepage_20170904-tip](https://user-images.githubusercontent.com/26304634/30032566-9621d0a0-918e-11e7-9ad6-e77d26075a25.png)

**Comment by ellemindwave** [comment]
@Cleop @Danwhy @shouston3 
Update from @indiamindwave24 as discussed on Slack: 

- background of tips to be same peach/orange colour as the feedback loop boxes
- speech marks to appear at top of tip (as per design below from a previous sprint)
- text to be in same navy blue as other text on the page
- button to be same navy blue as other buttons

for guidance on placement of speechmarks only:
![screen shot 2017-09-05 at 12 42 54](https://user-images.githubusercontent.com/26304634/30059871-d8bc69b6-9238-11e7-89dd-cfe91e51b8e5.png)

**Comment by reddog** [comment]
@Danwhy This has been merged in - is it available on the staging site to test?

**Comment by Danwhy** [comment]
Nothing has been deployed to staging today as it would overwrite the sleep assessment I manually pushed on Friday. Once PR #319 has been merged, staging will be up to date and ready for testing

**Comment by reddog** [comment]
@Danwhy #319's been merged - can this be progessed now?
