### ISSUE TITLE
Disqus - set it up to notify Sarah & Elle

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#177]
- [ ] Email notifications when anyone comments on a resource - to go to Sarah & Elle's MV accounts

**Comment by reddog** [comment]
@shouston3 to provide admin access details for Disqus to @ellemindwave

**Comment by ellemindwave** [comment]
@shouston3 Please can you send a link to the document with the login details for Disqus / Send them to me on Slack? Thanks

**Comment by samhstn** [comment]
I've added a link to the login details on slack
