### ISSUE TITLE
Make resources open in new tab

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#180]
- Sarah & India to look into GDS guidelines
- How do we display the fact that we are taking them to another site? Is this needed?

**Comment by Cleop** [comment]
@sarahwelton - any update on the GDS guidelines? Is this something you'd like to be implemented this sprint?

**Comment by ellemindwave** [comment]
@Cleop I have just checked in with @sarahwelton. 

Please can the resources open in a new tab 👍  We had this happen on the previous version of the site if I remember correctly...

Currently there is no need for a banner/alert as @sarahwelton has confirmed that that will be dealt with in the copy on the resources for now.
