### ISSUE TITLE
Google Analytics for submit button options

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#182]
- [x] Able to track whether feedback (thumbs up / thumbs down) comes from normal search results or from feedback loop

**Comment by reddog** [comment]
Separate methods for tracking thumbs up/down in the feedback loop vs. within the resource box, and separate methods for thumbs up and down.

Outcome will be that all of the following will be tracked separately:

- feedback box - thumbs up
- feedback box - thumbs down
- resource box - thumbs up
- resource box - thumbs down
