### ISSUE TITLE
Geolocation next steps

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#184]
See #191 for first next step...

More to come

Relates #146

**Comment by ellemindwave** [comment]
@shouston3 @Danwhy @Cleop 
Discussed with @sarahwelton:

This issue mainly relates to offline services, as they will be the ones where location is more relevant when appearing in search. According to the current content strategy, 'offline services' are number 5 on the list, behind sleep, anxiety, stress and sadness. The focus on the first 4 will be predominantly on online digital services.

**For 'live' (20th Sept)** - it would be good for there to be a way for offline services on the site (of which there may not be many yet) to have a field for postcode when they are being added and the functionality for a 5 mile radius around the searcher? Services that are closest to the person searching would appear highest in search. This can be discussed further in planning as to what might be easiest to implement. 

@shouston3 there is currently the functionality to have a different image appear depending on which part of London you are in. This would also be good to have for live. Is it possible for it to be based on the first 2 letters of the postcode ie EC or NW etc? 

By February, the idea is that there would be somewhere that a user can input their postcode and search according to postcode. February is the current expected date when offline services will be a focus.

**Comment by samhstn** [comment]
@ellemindwave 
We can have a field for postcode as well as a field for radius (or an additional close-radius)
We could also have multiple postcodes with a surrounding radius for each one.

We can then weight results depending on the users location (if they provide it, and ignore this weighting if they do not provide it).

The addition of a user being able to input their postcode for custom results for that location would actually be a relatively easy addition on top of the above functionality once it is built.

**Comment by Cleop** [comment]
Moving out of this sprint as discussed in the meeting today

**Comment by Cleop** [comment]
@ellemindwave - are we in a position to close this issue now? If not, perhaps you could outline what still needs to be done.
