### ISSUE TITLE
Yandex metric class codes for tracking

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#186]
Hello. Here's the instructions for the Developers related to Yandex Metrica.
=====================================================================
1) add a class to the email capture field.
Adding the CSS class **-metrika-nokeys** to the email form field prevents Yandex from recording information by blurring it out.

https://yandex.com/support/metrica/general/counter-webvisor.xml

2) Replace the Yandex code with this one:

<script type="text/javascript" >
   (function (d, w, c) {
       (w[c] = w[c] || []).push(function() {
           try {
               w.yaCounter45502608 = new Ya.Metrika({
                   id:45502608,
                   clickmap:true,
                   trackLinks:true,
                   accurateTrackBounce:true,
                   webvisor:true
               });
           } catch(e) { }
       });

       var n = d.getElementsByTagName("script")[0],
           s = d.createElement("script"),
           f = function () { n.parentNode.insertBefore(s, n); };
       s.type = "text/javascript";
       s.async = true;
       s.src = "https://mc.yandex.ru/metrika/watch.js";

       if (w.opera == "[object Opera]") {
           d.addEventListener("DOMContentLoaded", f, false);
       } else { f(); }
   })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/45502608" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

yandex.com
Session Replay — Metrica — Yandex.Support
By default, Session Replay records only user actions on the page, not the page content.

**Comment by ellemindwave** [comment]
Hello. Here's the instructions for the Developers related to Yandex Metrica.
=====================================================================
1) add a class to the email capture field.
Adding the CSS class **-metrika-nokeys** to the email form field prevents Yandex from recording information by blurring it out.

https://yandex.com/support/metrica/general/counter-webvisor.xml

2) Replace the Yandex code with this one:


<script type="text/javascript" >
   (function (d, w, c) {
       (w[c] = w[c] || []).push(function() {
           try {
               w.yaCounter45502608 = new Ya.Metrika({
                   id:45502608,
                   clickmap:true,
                   trackLinks:true,
                   accurateTrackBounce:true,
                   webvisor:true
               });
           } catch(e) { }
       });

       var n = d.getElementsByTagName("script")[0],
           s = d.createElement("script"),
           f = function () { n.parentNode.insertBefore(s, n); };
       s.type = "text/javascript";
       s.async = true;
       s.src = "https://mc.yandex.ru/metrika/watch.js";

       if (w.opera == "[object Opera]") {
           d.addEventListener("DOMContentLoaded", f, false);
       } else { f(); }
   })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/45502608" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

yandex.com
Session Replay — Metrica — Yandex.Support
By default, Session Replay records only user actions on the page, not the page content.

**Comment by samhstn** [comment]
@ellemindwave @sarahwelton this has been implemented on the [staging site](https://ldmw-staging.herokuapp.com/)
