### ISSUE TITLE
Redesign of 'get more info' section on resources

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#187]
- [ ] Styled according to wireframes & UI from Sarah/India
 
![screen shot 2017-08-24 at 10 46 44](https://user-images.githubusercontent.com/26304634/29660589-9c180ce6-88b9-11e7-8a93-bdef64afe2a6.png)

**Comment by samhstn** [comment]
Get more info redesign has been implemented on the [staging site](https://ldmw-staging.herokuapp.com/)

![screen shot 2017-08-29 at 12 31 49](https://user-images.githubusercontent.com/15983736/29818872-11a80844-8cb6-11e7-90d4-958d4cbb6340.png)
