### ISSUE TITLE
Look into Heroku payment options for dynos

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#190]
-payment options
-payment card and who they get sent to 
- Switching over to Mindwave's account so that the billing is correctly coming from Mindwave.

This will also be a solution to #173 - as upping the dynos will make the page load faster and therefore will make the need for pagination of resources less urgent

**Comment by reddog** [comment]
Issue is that staging (and live?) site can be slow to respond which hampers testing (and demos, etc).

Heroku pricing information at https://www.heroku.com/pricing

**Comment by reddog** [comment]
@ellemindwave Do we (Mindwave) have a Heroku account with payment details attached?

**Comment by reddog** [comment]
@katyedwards What is the next step to get a Mindwave paid-for Heroku account?  Is that something you can fix up?

**Comment by ghost** [comment]
Have set up and invited you @reddog to be an admin of the MV team... you should get an email.

**Comment by ghost** [comment]
FYI:
## Pricing and limits

- Teams of up to 5 members are free. Larger teams are charged at $10 per month.
- Team-owned dynos, add-ons, and other services are charged at the normal rate.
- Free dynos, which are available for personal apps, are not available to Teams.
- Each Team can have up to 25 members (or contact sales)


## Roles & permissions
Administrator = View, Deploy, Operate, Manage
Member = View, Deploy, Operate

**Comment by reddog** [comment]
@Cleop Who from the Dwyl team needs access to the new Mindwave Heroku account?  @shouston3 & @Danwhy ?

**Comment by Cleop** [comment]
@shouston3 @Danwhy
