### ISSUE TITLE
Decide when requests to Google API should be made for location

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#191]
- [ ] When and how often should requests be made to Google API for location specifics?
- [ ] Can the location specific searching have an on/off switch?

Relates #146

**Comment by shouston3** [comment]
Depends on decisions to be made in #184

**Comment by samhstn** [comment]
#### When and how often should requests be made to Google API for location specifics?
It depends what you would like to do in #184 
#### Can the location specific searching have an on/off switch?
There can be an on off switch for this in the admin view

**Comment by Cleop** [comment]
@ellemindwave - could you clarify what you mean by the on/off switch?

Do you mean a switch to turn off any location specific features (personalised hero images, displaying resources by locality)? What would the benefit/use of this be?

Or do you mean that you can decide per resource whether it should be on/off (should show in results or shouldn't show) for a given location?

**Comment by Cleop** [comment]
- per session
