### ISSUE TITLE
Difference between 'skip' and 'next question' buttons on new wireframes

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#192]

**Comment by reddog** [comment]
What should the `skip` button do?

![image](https://user-images.githubusercontent.com/151362/29621340-5eb0cbaa-8818-11e7-9a4b-a59082b0d046.png)

**Comment by Cleop** [comment]
@sarahwelton - would be great to get some feedback on this so we know whether the skip button is needed or not and therefore whether the team need to implement this or not?

**Comment by ellemindwave** [comment]
@Cleop I have checked with @sarahwelton and for now the 'skip' button is not needed. This will be tested and if a need for it appears, we will deal with it then :)

**Comment by Cleop** [comment]
Great, thanks for investigating @ellemindwave. If that's the case would you be happy to close this issue?
