### ISSUE TITLE
Redesign 'I am, or I know someone who is feeling' section into cubes

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#195]
- [x] content cubes to include child homepage title, blurb and link
- [x] space for between 4-6 child homepage resources at a time
- [x] If there are 4, evenly distributed, 2 rows
- [x] if there are 5, centre the bottow row, 2 rows
- [x] if there are 6, evenly distributed, 2 rows
- [x] Styled according to @indiamindwave24 UI

**Comment by indiamindwave24** [comment]
![global_home_4_topics](https://user-images.githubusercontent.com/25007700/29890825-d748c4f2-8dc0-11e7-92bd-f2c639d57f06.png)

Background section: 
![colour_background_ldmw](https://user-images.githubusercontent.com/25007700/29890829-df426f50-8dc0-11e7-84cd-e4c3fc1fe12d.png)

**Comment by indiamindwave24** [comment]
These are also on Zeplin

**Comment by sarahwelton** [comment]
@Danwhy @shouston3 @indiamindwave24 - need to remove the title from the block section "I am or I know someone who is feeling..." 

- see wireframes below

**Comment by sarahwelton** [comment]
![lm-homepage_20170831](https://user-images.githubusercontent.com/26305143/29960561-0b7ed5c0-8ef4-11e7-9cb7-67e0d36987b9.png)
![lm-homepage_mobile_20170831](https://user-images.githubusercontent.com/26305143/29960562-0b821dde-8ef4-11e7-9672-081842ded8c2.png)

**Comment by Danwhy** [comment]
Live on http://ldmw-staging.herokuapp.com/
