### ISSUE TITLE
Restyle self-assessment / urgent support banners

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#196]
- [x] footer block with 4 different pages (Get in touch, Ts & Cs, Self-assessment and Urgent support)
 - [x] Styled as per @indiamindwave24 designs for homepage

![screen shot 2017-08-24 at 11 20 27](https://user-images.githubusercontent.com/26304634/29662254-8ee16efa-88be-11e7-9d25-c13a8c630262.png)

**Comment by Cleop** [comment]
Designs from India:
![image](https://user-images.githubusercontent.com/16775804/29913600-7f8a5f6a-8e2d-11e7-81fb-73c1284f2ef0.png)

**Comment by Danwhy** [comment]
Live on http://ldmw-staging.herokuapp.com/
