### ISSUE TITLE
Put 'Get in touch' and Ts & Cs into boxes (like self-assessment and get urgent support)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#197]
- [x] footer block with 4 different pages (Get in touch, Ts & Cs, Self-assessment and Urgent support)
- [x] Styled as per @indiamindwave24 designs

![screen shot 2017-08-24 at 11 20 27](https://user-images.githubusercontent.com/26304634/29662214-6979afd8-88be-11e7-952f-986329d74b22.png)

**Comment by Cleop** [comment]
New designs:

![image](https://user-images.githubusercontent.com/16775804/29913565-66bd3340-8e2d-11e7-9e2b-9dd8296d645e.png)

**Comment by Danwhy** [comment]
Live on http://ldmw-staging.herokuapp.com/
