### ISSUE TITLE
Ability to add logos into the footer

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#198]
- [ ] India to check NHS guidelines
- [x] Need to be able to add logos into the footer

**Comment by samhstn** [comment]
`**technical**`
In terms of adding this in dynamically, we would ideally like to have a `+` button where the admin can add as many images as they would like to the footer section. This is currently not supported by wagtail, see [this stackoverflow question](https://stackoverflow.com/questions/42380241/extending-imagechooserpanel-to-allow-multiple-selections-and-uploads) and the links in the comments below it.

For now, we could just have 6 image panel chooser blocks which can be partially filled in and we can pull through up to 6 to dynamically display these in the footer. @Danwhy what do you think.

I think we should add panels for this and not rely on the rich text to do it all for us, see [here](https://groups.google.com/forum/#!topic/wagtail/3-Z9kF6Z88k)
`**technical**`

**Comment by samhstn** [comment]
I think this is our answer https://groups.google.com/forum/#!topic/wagtail/WNxJxmfybGs
