### ISSUE TITLE
Create Project Partners page

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#199]
This page is displayed in the top block of new home page mockup (under the hero block)

**Comment by ellemindwave** [comment]
- [ ] Sarah/Elle to create page
- [ ] Page to contain details of partners 
- [ ] Design of page?

**Comment by ellemindwave** [comment]
@Danwhy @shouston3 
Is there anything specific @sarahwelton and I need to know in the creating of this page in terms of making sure that it pulls through to the correct box on the homepage?

**Comment by samhstn** [comment]
Same instructions as described [here](https://github.com/LDMW/cms/issues/200#issuecomment-327227866)
