### ISSUE TITLE
Create Project Background page

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#200]
This page is displayed in the top block of new home page mockup (under the hero block)

**Comment by ellemindwave** [comment]
- [ ] Sarah / Elle to create page
- [ ] Page to contain details of project background 
- [ ] Styling of page?

**Comment by ellemindwave** [comment]
@Danwhy @shouston3 
Is there anything specific @sarahwelton and I need to know in the creating of this page in terms of making sure that it pulls through to the correct box on the homepage?

**Comment by samhstn** [comment]
@ellemindwave @sarahwelton you just need to go to:

`http://www.londonminds.co.uk/admin/ > Explorer > Home > Add child page > Static page`

Then put whatever you would like to have on that view.

You can click `view live` to see how it looks afterwards

If you want to change the url, simply go to the `promote` tab and change the `slug` field
