### ISSUE TITLE
Implement new Style Guide

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#202]
Update 14th September:

We have and can begin implementing, re @sarahwelton's style guide below:
- [x]  colour palette
- [x] fonts
- [x] buttons
- [x] links 

Name and logo coming at a later date, but rest (above) can be implemented now. 
- [ ] logo
- [ ] name

**Comment by sarahwelton** [comment]
![ldmw_styleguide_20170913](https://user-images.githubusercontent.com/26305143/30380727-3f78d892-9892-11e7-9fe7-4770466f7e2c.png)

@shouston3 @Danwhy let me know if you'd like this in a different format or in Zeplin... or any pages mocked up etc. 

Alternatively just give me a shout here or on Slack if anything needs clarifying. 

Ta

**Comment by sarahwelton** [comment]
![ldmw_styleguide_20170913](https://user-images.githubusercontent.com/26305143/30424257-51e3c842-993d-11e7-89d0-5cf0fc03d84b.png)

@Danwhy @shouston3 - I have slightly amended the divider lines and outline of the resource block.

**Comment by Cleop** [comment]
- Logo - remove logos and do not keep the spacing
- Check out whether banner resizes according to image size
- Name changes to be done by MV team

**Comment by sarahwelton** [comment]
<img width="574" alt="screen shot 2017-09-14 at 15 11 34" src="https://user-images.githubusercontent.com/26305143/30434369-08ffc92e-995f-11e7-9b05-cc0a97d310d5.png">

Sorry - another couple of minor amends. Have adjusted H2 and H3

Let me know if you'd like me to re-upload the whole style guide to replace the one above @Cleop

**Comment by sarahwelton** [comment]
![ldmw_tips-assessment_20170914](https://user-images.githubusercontent.com/26305143/30436449-0afa079e-9964-11e7-9d81-42fbe118a569.png)

Page mock up
