### ISSUE TITLE
Resources: ensuring content formatting is consistent

### ISSUE THREAD

**Issue by Cleop** [LDMW/cms#21]
Relates to #19. 

How can we ensure that content creators are using Wagtail correctly and not creating resources using h2's etc? They should only include `<p>`'s and `<a>`'s. 

- Option A: include instructions in the README on how to create content (#19)
- Option B: prevent users from creating incorrect data formats. Ie. change the field on wagtail to only accept plain text (but then what about links or line breaks?) or another restricted field type.
- Option C: another alternative?

**Comment by samhstn** [comment]
@Cleop this seems a little out of date and perhaps no longer relevant given the new architecture.

Can we close this?

**Comment by Cleop** [comment]
Good spot @shouston3 

Closing due to technology change in: https://github.com/LDMW/app/issues/483 meaning that all Wagtail features will be fully functioning and using the incorrect styling tags will not cause the application to error.

Vetting for the appropriate/preferred styling will be more dynamic and be under the control of the content moderator who will determine which content goes live.
