### ISSUE TITLE
Options for displaying resource URLs

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#217]
Is there a way that we can have the URL display on the resource as, for example 'sleepio.com' , but then when clicked it actually goes to, for example 'sleepio.com?utm_source=londonminds'

The URLs with tracking look so ugly and it would be good for us to be able to cut out the https/www etc too

**Comment by samhstn** [comment]
@ellemindwave I've just done it in the admin view like this and added it:
![screen shot 2017-08-24 at 16 14 27](https://user-images.githubusercontent.com/15983736/29673509-560830ae-88e7-11e7-895f-1fa799ccf15e.png)

and it looks like this:

![screen shot 2017-08-24 at 16 17 35](https://user-images.githubusercontent.com/15983736/29673663-d2d8e434-88e7-11e7-8ac0-2db081d65b5e.png)

Would this be fine?

**Comment by ellemindwave** [comment]
Ah - good idea @shouston3 ! That will do for now, yes. Thanks

**Comment by ellemindwave** [comment]
Although @shouston3 @Danwhy I have just had a thought - will the GA tracking be the same if the link is in the body copy like that rather than in the field for the resource URL? Will anything need to be changed?

**Comment by samhstn** [comment]
@ellemindwave That's true. We'll look at implementing a fix for that

**Comment by Danwhy** [comment]
I don't think this is the best way to do it. As @ellemindwave said, the ga tracking would have to be changed, it wouldn't be styled correctly, and the description is being removed from the resource list: https://github.com/LDMW/cms/issues/205. 

I think we could just remove the end of the url when displaying it on the backend

**Comment by ellemindwave** [comment]
Is it not an option to have 2 fields: 
one for what the url is (destination) and one for how it displays?

**Comment by samhstn** [comment]
That is an option, would you like that instead.

If you would typically be just displaying `sleepio.com`,
but linking to `sleepio.com?utm_source=londonminds` then I suggest going with @Danwhy's solution.

If you would like to display other text, then we can go with a 2 field option.

@ellemindwave Your call.

**Comment by ellemindwave** [comment]
@shouston3 @Danwhy 
Thanks for explaining. 
Talking to the eggs, I think that from a digital marketing/tracking point of view it will become more crucial once we get to 'live' phase to have the 2 fields, one for what the URL is and one for how it displays on the site. 

So that option, please! :) 
This isn't crucial right now, though, therefore giving it a priority 3 label 👍
