### ISSUE TITLE
In global navbar, be able to have spaces instead of '-'

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#221]
sleep-deprived - is it possible to get rid of the hyphens?

**Comment by samhstn** [comment]
[The staging site](https://ldmw-staging.herokuapp.com/) now has no hypens in the navbar

![screen shot 2017-08-29 at 12 14 57](https://user-images.githubusercontent.com/15983736/29818326-b87b06a6-8cb3-11e7-8b66-d41ce13bbccf.png)
To get rid of the hyphens just ensure the title of the resource doesn't have one in it
![screen shot 2017-08-29 at 12 16 14](https://user-images.githubusercontent.com/15983736/29818356-e212475e-8cb3-11e7-8e7e-72dc82ee5be4.png)
