### ISSUE TITLE
Loaddata error

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#222]
We've seen this before, can't remember how we fixed it.

When running:

```bash
heroku run "python manage.py dumpdata --natural-foreign --natural-primary" -a ldmw > dumpdata.json
psql -c "drop database cms"
psql -c "create database cms"
python manage.py migrate
python manage.py loaddata dumpdata.json
```

We get this error

![screen shot 2017-08-24 at 17 03 28](https://user-images.githubusercontent.com/15983736/29675838-49a714ae-88ee-11e7-9ccb-ed3dd3101a4c.png)

```bash
raise base.DeserializationError.WithData(e, d['model'], d.get('pk'), field_value)
django.core.serializers.base.DeserializationError:
Problem installing fixture '/Users/samhouston/proj/cms/dumpdata.json':
An error occurred in the current transaction.
You can't execute queries until the end of
the 'atomic' block.: (wagtailimages.image:pk=2) field_value was '['sarah']'
```

@Danwhy do you remember what the solution was?

**Comment by Danwhy** [comment]
The problem was the images. I'd suggest either using the data from the `s-data` branch, or just dumping/loading the resources and ignoring the rest

**Comment by samhstn** [comment]
I got around the problem by instead just running:
```bash
heroku pg:backups:download -a ldmw
pg_restore --verbose --clean --no-acl --no-owner -d cms latest.dump
```

Cloning the whole database

Taken from here: https://devcenter.heroku.com/articles/heroku-postgres-import-export#download-backup
