### ISSUE TITLE
How to define postgres url?

### ISSUE THREAD

**Issue by SimonLab** [LDMW/cms#23]
The Postgres database settings are define in the [base.py](https://github.com/LDMW/cms/blob/master/cms/settings/base.py) file.
The values for the database are store in the DATABASE['default'] property. However at the moment the config is defined twice:
- hard coded in the [instantiation of the DATABASE object](https://github.com/LDMW/cms/blob/748db228d712415e4f2f0d852e4b8bcfaa685948/cms/settings/base.py#L97-L102)
- redefine with the [dj_database_url.config method](https://pypi.python.org/pypi/dj-database-url) -  [here](https://github.com/LDMW/cms/blob/748db228d712415e4f2f0d852e4b8bcfaa685948/cms/settings/base.py#L110). This method will look for a DATABASE_URL environment variable value and convert the url to the right config values.

We need to resolve this configuration conflict. I suggest that we:
- define the DATABASE object as an empty  value: ```DATABASE={}```
- DATABASE['default'] is then define with dj_database_url.config
- update the documentation/Readme to explain that a .env file needs to be created with the DATABASE_URL environment variable, for example for the user/password postgres/postgres the .env will look like this: ```export DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/cms```. Then before running any migrations execute ```source .env``` to load the environment variable

@Danwhy @shouston3 @Cleop is this a good suggestion?

**Comment by samhstn** [comment]
Looks good @SimonLab 
It's great you've documented all of this
I'll look at adding this to the readme
Sorry for the hassle it caused you today

**Comment by samhstn** [comment]
Fixed by #24
