### ISSUE TITLE
Ad destinations not working

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#233]
====================
Problem Report
====================
AdWords account number: 640-336-7097

----------------------------------------------
Campaign: 'Scenario 1 > Exact > Mobile,' Ad Group: 'Scenario 1 > Can't Sleep'
----------------------------------------------

Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
From Quick Fixes To Long Term Solutions, We Can Help You Sleep Better.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~
Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
NHS-Backed Service To Help You Find A Better Night's Sleep, Starting Right Now.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~
Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
From Helping You Sleep To Talking To Other People. We're Here To Help.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~

SUGGESTIONS:
---> To help make sure that our ads are relevant, useful and easy to interact with, we don't allow ads to link to broken web pages. For example, your landing page can't return an error code beginning with a 4 or a 5 (such as a 404 error). To run your ad, please make sure that you entered the right Destination URL and that your site works properly for all browsers, across all locations.

See the policy to learn how to fix your ad: https://support.google.com/adwordspolicy/answer/6368661#673
----------------------------------------------
Campaign: 'Scenario 1 > Phrase > Mobile,' Ad Group: 'Scenario 1 > Can't Sleep'
----------------------------------------------

Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
From Helping You Sleep To Talking To Other People. We're Here To Help.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~
Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
From Quick Fixes To Long Term Solutions, We Can Help You Sleep Better.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~
Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
NHS-Backed Service To Help You Find A Better Night's Sleep, Starting Right Now.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~

SUGGESTIONS:
---> To help make sure that our ads are relevant, useful and easy to interact with, we don't allow ads to link to broken web pages. For example, your landing page can't return an error code beginning with a 4 or a 5 (such as a 404 error). To run your ad, please make sure that you entered the right Destination URL and that your site works properly for all browsers, across all locations.

See the policy to learn how to fix your ad: https://support.google.com/adwordspolicy/answer/6368661#673
----------------------------------------------
Campaign: 'Scenario 1 > Phrase > Tablet,' Ad Group: 'Scenario 1 > Can't Sleep'
----------------------------------------------

Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
From Quick Fixes To Long Term Solutions, We Can Help You Sleep Better.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~
Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
From Helping You Sleep To Talking To Other People. We're Here To Help.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~
Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
NHS-Backed Service To Help You Find A Better Night's Sleep, Starting Right Now.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~

SUGGESTIONS:
---> To help make sure that our ads are relevant, useful and easy to interact with, we don't allow ads to link to broken web pages. For example, your landing page can't return an error code beginning with a 4 or a 5 (such as a 404 error). To run your ad, please make sure that you entered the right Destination URL and that your site works properly for all browsers, across all locations.

See the policy to learn how to fix your ad: https://support.google.com/adwordspolicy/answer/6368661#673
----------------------------------------------
Campaign: 'Scenario 1 > Exact > Tablet,' Ad Group: 'Scenario 1 > Can't Sleep'
----------------------------------------------

Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
From Quick Fixes To Long Term Solutions, We Can Help You Sleep Better.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~
Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
NHS-Backed Service To Help You Find A Better Night's Sleep, Starting Right Now.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~
Ad Text:

Can't Sleep? You're Not Alone
London Minds Can Help
From Helping You Sleep To Talking To Other People. We're Here To Help.
http://www.londonminds.co.uk/sleep

Ad Status: Disapproved
Ad Issue(s): Destination not working
~~~~~~~~~

SUGGESTIONS:
---> To help make sure that our ads are relevant, useful and easy to interact with, we don't allow ads to link to broken web pages. For example, your landing page can't return an error code beginning with a 4 or a 5 (such as a 404 error). To run your ad, please make sure that you entered the right Destination URL and that your site works properly for all browsers, across all locations.

See the policy to learn how to fix your ad: https://support.google.com/adwordspolicy/answer/6368661#673

**Comment by samhstn** [comment]
I've added that homepage `/sleep` route in the admin view. Everything should now be working fine

**Comment by samhstn** [comment]
@ellemindwave the reason for this failing was that http://www.londonminds.co.uk/sleep gave us a 404 error, this has now been resolved by adding this route in the admin view
