### ISSUE TITLE
Remove Traceback from error page

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#246]
The `Traceback` portion of the error page (displayed when page doesn't exist, for example), shows secret information which should never be revealed, see

![image](https://user-images.githubusercontent.com/151362/29882809-21630f54-8da6-11e7-9d0b-759c57cae4fc.png)

To test:

1.  visit http://www.londonminds.co.uk/sleep/talk-about-it/?utm_source=facebook&utm_medium=cpc&utm_campaign=august-test&utm_content=11-3 (will only work as a test until these template pages are fixed for use with URL parameters, after which point test with a different URL)
2.  `TemplateDoesNotExist` error page will be shown, detailing secret information in the `Traceback` section.

See the following footer message:  `You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.`

**Comment by samhstn** [comment]
@reddog we'll look at swaping our api keys after this is resolved. Looks like we're not following [this](https://docs.djangoproject.com/en/dev/howto/deployment/checklist/#debug).

Nice spot

**Comment by reddog** [comment]
@shouston3 Thanks for that link.  Is there a deployment guide/plan for this app?  Could the info in that found document be referenced in it?

**Comment by reddog** [comment]
@shouston3 Just tried with a link that doesn't exist (given that template URL parameters are now handled, so previous test URL won't give the error anyhow), eg http://www.londonminds.co.uk/sleep/talk-about-it-here/?utm_source=facebook&utm_medium=cpc&utm_campaign=august-test&utm_content=11-3 and I get an `Internal server error`.

Is that right?

**Comment by samhstn** [comment]
Because of how we're hardcoding the static pages, anything starting with `/sleep` will cause an internal server error.
This problem will no longer persist once we are serving the static pages properly through the cms, so I'm not sure that it is not a problem worth solving.
When we no longer serve up hardcoded html files, we will get 404 errors for these non existent endpoints.

**Comment by reddog** [comment]
@shouston3 Thanks for that.

So you'd be expecting to see a `Page not found` message now?

Tested with http://www.londonminds.co.uk/something/talk-about-it-here/?utm_source=facebook&utm_medium=cpc&utm_campaign=august-test&utm_content=11-3

Looks okay (in that secret information isn't displayed any more!)

**Comment by samhstn** [comment]
@reddog can we close this?
