### ISSUE TITLE
Database on AWS EC2?  Not AWS RDS or Heroku?  Can we have a little info on why?

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#247]
A few questions about the Wagtail database:

1.  It looks like it's on an AWS EC2 instance.  Is this the case?
2.  What other services/usage is the AWS EC2 instance for?
3.  Why is it on an AWS EC2 instance and not AWS RDS?  See https://aws.amazon.com/rds/postgresql/
4.  Why isn't it on Heroku Postgres?  See https://www.heroku.com/postgres

I'm not asking for any changes to be made at this stage, just wanting to understand what the current situation is and why.

**Comment by samhstn** [comment]
We are using Heroku postgres.

If you go through their [provisioning the addon](https://devcenter.heroku.com/articles/heroku-postgresql#provisioning-the-add-on) guide, heroku postgres just uses ec2 under the hood.

**Comment by reddog** [comment]
I should have read further - thanks for confirming that.
