### ISSUE TITLE
'Results loading' message on 'personalise your results' section

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#248]
Need for something to alert users that their results are dynamically updating as they work through the 'personalise your results' section

@sarahwelton has highlighted that this is quite a high priority due to it negatively impacting the user experience in testing - users have expressed that they don't currently think anything is happening as they click through the questions

If this means that something else might need to drop off the end of the sprint to make it fit, then that can be arranged I'm sure...!

**Comment by ellemindwave** [comment]
@Danwhy @shouston3 @Cleop What might your suggestions be for possibilities? Easiest/quickest way we could achieve this....?

**Comment by Cleop** [comment]
For loading takes time you often see:
<img src="https://user-images.githubusercontent.com/16775804/29912381-62266ada-8e29-11e7-99e1-edf98ab75210.png" width=60px />
However, the results load so quickly that I don't think this would be noticeable. I think we're less in need of a loading message and more in need of an updated message. An alternative that springs to mind would be a bit like a **flash message saying something like 'results updated' or 'results customised':**
![image](https://user-images.githubusercontent.com/16775804/29912446-99ae1f0c-8e29-11e7-9682-e957c149fd26.png)
Not sure if anyone else has any thoughts...

**Comment by ellemindwave** [comment]
@Cleop Could we go for a green overlay flash message that says 'Results updated'.

On clicking 'next question' it would flash on at the bottom of the question card (in the space between previous and next question buttons) for a second or two (need to test this) and then take you to the next question. Let's start with a 1 second pause.

Is this achievable?

**Comment by Danwhy** [comment]
Live on http://ldmw-staging.herokuapp.com/
