### ISSUE TITLE
Create anchor link to global nav on homepage

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#259]
<img width="669" alt="screen shot 2017-09-01 at 09 02 02" src="https://user-images.githubusercontent.com/26305143/29960608-481d723e-8ef4-11e7-98b9-4cd66ed61376.png">

- [x] Remove search. 

- [x] Replace with arrow and "Browse topics below" 

- [x] Create an anchor link from the text and arrow saying "Browse topics below" to scroll the user so that the global navigation menu sits at the top of the browser (I am or know someone who is feeling: bar)

@indiamindwave24 we'll need hover states for this.

**Comment by Danwhy** [comment]
Live on http://ldmw-staging.herokuapp.com/
