### ISSUE TITLE
Duplicate resources

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#261]
Visiting http://www.londonminds.co.uk/?q=fear+fighter#results shows:

1 Result

But 2 Fear Fighter resources

**Comment by Danwhy** [comment]
I'm guessing this is something to do with the pagination, it must be always be returning a second set of results, and if there isn't a second set, returning the first set again. http://www.londonminds.co.uk/?q=brain#results
So, if there are less than three results, we want to return nothing for the second request.

**Comment by samhstn** [comment]
Cool sounds like you understand the problem much better than I do.

I don't mind taking #262 if your up for tackling this one

**Comment by samhstn** [comment]
This has been fixed on [staging](https://ldmw-staging.herokuapp.com/?q=fear#results)
