### ISSUE TITLE
What are we to do with the alpha sections?

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#268]
The alpha sections (currently bottom of the homepage) are not in the designs.
Should we look at removing them from the site and also from the admin view?

**Comment by ellemindwave** [comment]
Hi @shouston3 - thanks for raising. 

Sarah says: 
We don't need Alpha sections anymore. Probably best to remove or repurpose - depending on how long this takes. If it takes a long time to get rid of them from Wagtail, then we could hide from the site and leave them in for now...

**Comment by samhstn** [comment]
It's very quick to delete them, we'll remove them
