### ISSUE TITLE
Disqus usernames

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#270]
In order to assign moderators, or transfer over disqus admin rights, I must do this based on @ellemindwave @sarahwelton your disqus usernames.

![screen shot 2017-09-04 at 12 09 41](https://user-images.githubusercontent.com/15983736/30024056-f73b2f50-9169-11e7-9beb-3021874bcdea.png)

Could you sign up to disqus and provide me your usernames.

This link might fast forward some things: https://disqus.com/profile/signup/?next=https://newsite-6.disqus.com/admin/settings/moderators/

**Comment by samhstn** [comment]
You can find your username here: https://disqus.com/home/settings/account/

**Comment by ellemindwave** [comment]
Thanks @shouston3 - my username is ldmw

**Comment by sarahwelton** [comment]
my username is goodthinkingsarah

**Comment by samhstn** [comment]
Great, I've added you both as admins

![screen shot 2017-09-15 at 11 24 04](https://user-images.githubusercontent.com/15983736/30478315-7b0c313e-9a08-11e7-97cd-dc382ee0b2ea.png)

You should get notified whenever someone comments so that you can moderate it.

**Comment by sarahwelton** [comment]
@shouston3 how do I get into that account?

**Comment by samhstn** [comment]
Can you access https://good-thinking.disqus.com/admin/

**Comment by samhstn** [comment]
Seems like this is all sorted
