### ISSUE TITLE
Expert 24 API

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#274]
View the current assessment at (client-side): https://ldmw-staging.herokuapp.com/resources/assessment/
Server-side: https://ldmw-staging.herokuapp.com/server-assessment/

Place to add all information about integrating the E24 algorithm into the site.

We **will** require:

- client side *traversal* client - JavaScript code to take the current set of questions or outcomes and display them, and take client input and format for return to the E24 engine
- client side front-end styling for questions and inputs
- mockups / assets for all user input/display elements, eg previous/next buttons, progress bar, etc.

We **may** require:

- server-side proxy to take client responses, feed them to E24, get the response from E24 and send back to the client.  It *can* all be done client side - will depend on information security, authorisation, etc issues.

**Comment by reddog** [comment]
There is a client-side demo site at http://apps.expert-24.com/WebBuilder/TraversalService/Traversal.html  This uses their *JavaScript Traversal* client.

![image](https://user-images.githubusercontent.com/151362/30070445-57a206e2-925b-11e7-9a46-3e0e0ac4f206.png)

**Comment by reddog** [comment]
The example Traversal client-side code is at http://apps.expert-24.com/WebBuilder/TraversalService/TraversalClient.js

**Comment by reddog** [comment]
Self-assessment algorithm within E24's site, and with their front-end styling, looks like:

![image](https://user-images.githubusercontent.com/151362/30072710-17a04f56-9263-11e7-99cb-05667ee68023.png)

**Review** currently looks like:

![image](https://user-images.githubusercontent.com/151362/30072880-a7a2cf16-9263-11e7-8245-13cf3fcbfe67.png)

**Summary** currently looks like:

![image](https://user-images.githubusercontent.com/151362/30072907-c22036a8-9263-11e7-86f7-ad4fb86fb6f1.png)

**Comment by ellemindwave** [comment]
Expert 24 - w. Mike and David
- display questions - w. Mike and David
- style questions
- ability to jump to partial stage of the questionnaire - create param in url to jump to this part using token
- contact details not stored by Expert 24 - tbc on tues

**Comment by Cleop** [comment]
Customising resources at the end of a survey:
- Client-side - can't really attach resources
- Server-side - would be possible to attach resources

IG and CG decision about responsibility client-side or server side - meeting tomorrow?

Need to be able do modules of assessment, awaiting from Kat at Expert 24
Will need to implement this.

Friday morning - UI from Sarah
- Client-side UI will be tricky 
- Server-side would be normal styling time (1/2 day for styling hook up)

**Comment by sarahwelton** [comment]
![ldmw_assessment-styling_20170914](https://user-images.githubusercontent.com/26305143/30476257-5fbd15da-9a01-11e7-9e1d-521e8889db0f.png)

**Comment by ellemindwave** [comment]
@shouston3 @Danwhy 

Latest on the segmentation:
 
Anxiety is algoid 4623
Depression is algo id 62
Stress is algo id4706
