### ISSUE TITLE
Feedback loop updates without refreshing the page

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#278]
On returning to the site after clicking on a third party link, the feedback loop will have activated and will be waiting for the user to enter their feedback.

Currently the page needs refreshing before this will display.

V2 put in via AJAX (not estimated for here)

**Comment by ellemindwave** [comment]
@shouston3 This now works on the staging site on desktop, but on mobile, when I click the URL it doesn't actually open the third party site, it just triggers the feedback loop to work....

Is this a new issue?

**Comment by samhstn** [comment]
Nice spot @ellemindwave. I think this should be a new issue.
