### ISSUE TITLE
Force all access over HTTPS

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#281]
Currently both test and live sites are available over both HTTP and HTTPS.

All web traffic should be forced over to HTTPS.

**Comment by reddog** [comment]
@shouston3 Does your fix apply to production only?  https://github.com/LDMW/cms/pull/288/commits/bafa95764ac17beb3faf7c28d36fa7c612a90b8f references `production.py`

Will there be no such force to https on test?

**Comment by samhstn** [comment]
We only run development on localhost and the test environment on travis and locally.

Both heroku apps run in production

**Comment by samhstn** [comment]
Can't test this until we deploy to the live site as heroku automatically forwards http -> https

**Comment by reddog** [comment]
@shouston3 Looks like the live site is now auto-forwarding to the https version.  Is this complete?

**Comment by reddog** [comment]
@shouston3 Isn't this already tested?  Anything else to do?
