### ISSUE TITLE
Header banner - find out more link - not a domain-relative URL

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#283]
1.  Visit the test site at http://ldmw-staging.herokuapp.com/
2.  Click on `Find out more` in the header banner
3.  The following link will be opened http://ldmw.herokuapp.com/#alpha  This is a link on the live site, no the test site

**Comment by samhstn** [comment]
This can be changed in the cms. [This should be link to edit it](https://ldmw-staging.herokuapp.com/admin/pages/3/edit/)

**Comment by reddog** [comment]
@shouston3 Thanks for that.

The link on the live site is as expected.  Looks good.

**Comment by reddog** [comment]
@shouston3 Is there a CMS setting that sets the DNS name of the Wagtail instance?

The setting you've linked to is showing that the `Find out more` link is set to go to the **relative** URL of `/#alpha`, see:

![image](https://user-images.githubusercontent.com/151362/30273876-c622ec44-96f2-11e7-9e7b-e6da7a7e7fb9.png)

That *should* go to https://ldmw-staging.herokuapp.com/#alpha but it's actually going to http://ldmw.herokuapp.com/#alpha

**Comment by samhstn** [comment]
Sorry, I gave you the wrong link (the link may have actually changed since then). [This](https://ldmw-staging.herokuapp.com/admin/pages/139/edit/) is actually where you edit the banner and it works as it should.

The other link was to the `Home` app which is no longer used (`Main` is what we are using now).

Removing `Home` is currently in a pr: https://github.com/LDMW/cms/pull/244, but we can't remove it for reasons described in the pr

**Comment by reddog** [comment]
@shouston3 Thanks for that.  Changed the link to a relative link and that works in terms of displaying the correctly URL, however the `#alpha` section isn't displaying, see https://ldmw-staging.herokuapp.com/#alpha

With regard to PR #244, does that mean that the `Home` app will be kept long term?  Does the previous home page that you linked to previously need removing from the CMS?  Is that the solution to that point?

**Comment by samhstn** [comment]
The alpha banner has been removed see https://github.com/LDMW/cms/issues/268#issuecomment-326980470

No the `Home` app won't be kept long term, we will delete it when the static landing pages are no longer needed.

**Comment by reddog** [comment]
Closing.  Link fixed (in a no-longer used piece of text!)
