### ISSUE TITLE
Missing robots.txt (to tell Google not to index site)

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#287]
1.  Access http://ldmw-staging.herokuapp.com/robots.txt (test site)
2.  `Page not found` error will be shown

or

1.  Access http://www.londonminds.co.uk/robots.txt (live site)
2.  `Page not found` error will be shown

The robots.txt file should be available on both sites to block search engine indexing (this will be changed at go-live point).

**Comment by samhstn** [comment]
Now on staging: https://ldmw-staging.herokuapp.com/robots.txt

**Comment by reddog** [comment]
Tested on staging and live and both are coming up with the same robots.txt file which looks like:

```
User-agent: *
Disallow: /
```

![image](https://user-images.githubusercontent.com/151362/30273665-e5ad2ec2-96f1-11e7-92b0-59c8c28e7b88.png)
