### ISSUE TITLE
Site responsiveness

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#289]
For some unknown reason the http://www.londonminds.co.uk/ site is more reliable than http://londonminds.co.uk/

I quite often don't get a response from the second one while I always get a response from the first.

**Comment by reddog** [comment]
Looks like DNS needs fixing up, see https://github.com/LDMW/cms/issues/290

**Comment by samhstn** [comment]
Looks like @reddog has identified the problem in #290, working from that issue
