### ISSUE TITLE
DNS settings mismatch between www and non-www domains for live site

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#290]
The live site should be accessible from both www.londonminds.co.uk and londonminds.co.uk (with and without leading www).  However, the DNS for the two FQDNs are different:

**www.londonminds.co.uk**
```
 www.londonminds.co.uk	canonical name = londonminds.co.uk.herokudns.com.
 Name:	londonminds.co.uk.herokudns.com
 Address: 46.137.160.82
 Name:	londonminds.co.uk.herokudns.com
 Address: 46.137.174.111
 Name:	londonminds.co.uk.herokudns.com
 Address: 54.228.216.104
 Name:	londonminds.co.uk.herokudns.com
 Address: 54.228.245.152
 Name:	londonminds.co.uk.herokudns.com
 Address: 54.247.89.141
 Name:	londonminds.co.uk.herokudns.com
 Address: 54.247.109.213
 Name:	londonminds.co.uk.herokudns.com
 Address: 46.137.79.23
 Name:	londonminds.co.uk.herokudns.com
 Address: 46.137.94.167
```

**londonminds.co.uk**
```
 Name:	londonminds.co.uk
 Address: 184.168.221.1
```

The non-www version is non-responsive and need altering.

**Comment by reddog** [comment]
Actually the current configuration isn't actually that bad.  As detailed in RFC1034 http://www.faqs.org/rfcs/rfc1034.html see section 3.6.2, *Aliases and canonical names*

> If a CNAME RR is present at a node, no other data should be present

Hence it is correct and valid that the *naked* domain name does not redirect to Heroku via a CNAME record.

DNS is managed by GoDaddy.  It is possible that GoDaddy's redirection isn't working well.  It does appear as though web forwarding is set up correctly in GoDaddy:

![image](https://user-images.githubusercontent.com/151362/30114354-8b0341ae-930f-11e7-849b-ca573f6f05f6.png)

**Comment by reddog** [comment]
`londonminds.co.uk` is working from the office on one wifi, but not the other....  It appears as though it could be a DNS resolution issue.

Unsure yet if that's because of bad caching by the point of presence (possible, but unlikely and would be *hard* to fix), or if there are one or more GoDaddy *forwarding* servers that isn't working (maybe more possible).

When connected via `mindwave` wifi:

```
$ nslookup
Default Server:  vodafone.connect
Address:  192.168.1.1

> londonminds.co.uk
Server:  vodafone.connect
Address:  192.168.1.1

Non-authoritative answer:
Name:    londonminds.co.uk
Address:  184.168.221.30
```

![image](https://user-images.githubusercontent.com/151362/30116160-bce9c396-9314-11e7-8196-2b6d38386f4c.png)

**Comment by reddog** [comment]
Over **one hour** later, GoDaddy support are looking in to it and will get back to us.  It seems to me that it could be a DNS propagation issue at their end or one of their "forwarding" servers misbehaving/misconfigured.

Will report back when I hear more (in the next day or so).

**Comment by Cleop** [comment]
@reddog - is this issue still relevant for good-thinking.uk?  Perhaps you could update or close it?

**Comment by reddog** [comment]
I never heard back from GoDaddy support.

I've also not heard of any further issues from users.

@ellemindwave Can we close this now?
