### ISSUE TITLE
Adding search console to the live site

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#294]
Has come in as a request from Fresh Egg, ahead of going live on 20th:

Add Search Console to the live website so that we can start to track and report on the Google search visibility

https://support.google.com/webmasters/answer/6001104?hl=en

**Comment by Danwhy** [comment]
@ellemindwave I need to add owners to the site using their google account emails. What email addresses would you like me to use?

**Comment by ellemindwave** [comment]
@Danwhy , if you can add me for the time being, that it's fine. 

eleanor@mindwaveventures.com

I am assuming that we can change this / add users when we wish to?
