### ISSUE TITLE
Generation of friendly URLs

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#296]
In 'personalisation of results' section, the use of one filter (first question) should generate a friendly URL when 'next question' is clicked. 
This friendly URL can then be used to direct users into a pre-filtered page. 
Friendly URLs - format for the urls : /sleep-deprived/just-can't-sleep  as an e.g. for one filter only

Format for friendly urls tbc by Sarah.

Any URLs that are generated following the clicking of filter 2 or 3 will be 'unfriendly' URLs.

**Comment by Cleop** [comment]
* results will no longer update dynamically, only on the clicking of the 'next' button
* this issue and its estimate does not cover unfriendly urls for multiple filter searches
