### ISSUE TITLE
Transfer onto new Heroku site (Mindwave's account)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#297]
- David & Katy looking into setting this up

**Comment by reddog** [comment]
Seems as though this shouldn't be done right now, in the rush to get other items fixed.

**Comment by iteles** [comment]
@ellemindwave Estimated on the basis that the ownership of the existing heroku app will be transferred to MV (rather than a different heroku site).

@reddog Could you please provide the account details for the transfer?

**Comment by reddog** [comment]
Both staging and live Heroku apps are to be moved over.

@iteles Rather than just pass over the account details, can we do this together (both teams available) early on in the sprint in order to avoid any developer access issues, etc.

**Comment by reddog** [comment]
@ellemindwave @Cleop @Danwhy Would it be convenient to do this Tuesday 3rd October (tomorrow)?

**Comment by ellemindwave** [comment]
email address is info@mindwaveventures.com

**Comment by ellemindwave** [comment]
@Danwhy any update on this - has the invite been sent to the email address?

@reddog it would be good to get this done today please, as once the site is up on the new URL, Fresh Egg can then go ahead and do all of their Google Analytics stuff

**Comment by Danwhy** [comment]
@ellemindwave I've just made the transfer of ownership.
@reddog Could you let me know when you've accepted the ownership, and I'll make sure there are no access problems

**Comment by ellemindwave** [comment]
Thanks @Danwhy ! Katy has just accepted the ownership 👍

**Comment by reddog** [comment]
@Danwhy We have the https://ldmw.herokuapp.com/ showing in our Heroku account.  Thanks for that.  Are you able to transfer the staging app also?

Would you like/need to be added as a collaborator on these projects?

**Comment by ghost** [comment]
I got some email alerts so have transferred both apps into the mindwave team account on heroku.  Hope that's right!

**Comment by reddog** [comment]
@katyedwards You beat me to it - thanks.

**Comment by Danwhy** [comment]
@reddog I should remain as a collaborator anyway

**Comment by reddog** [comment]
@Danwhy Okay, there is a Gmail address showing as a collaborator.  Let me know if there's anything else you need.

**Comment by Danwhy** [comment]
@reddog I've managed to deploy to staging, so it doesn't look like there are any issues with access

**Comment by reddog** [comment]
@Danwhy Great stuff.  Let me know if anything else turns up.
