### ISSUE TITLE
Swiping functionality for tips (like PYR section)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#298]
- Tips appearing in the listings should be on a carousel so that the user can swipe through various tips 
- The tips will no longer take up as much room in the listings and make room for more important resources

- Swipe functionality to be same as for the 'Personalise your Results' section
- Styling to be confirmed by @indiamindwave24

**Comment by sarahwelton** [comment]
<img width="1027" alt="screen shot 2017-09-14 at 15 36 56" src="https://user-images.githubusercontent.com/26305143/30435823-a330a754-9962-11e7-9736-c1ede43d42e3.png">
<img width="1020" alt="screen shot 2017-09-14 at 15 37 17" src="https://user-images.githubusercontent.com/26305143/30435824-a34c45c2-9962-11e7-9584-0ff23a857b3f.png">


As discussed - option to "share a tip" a nice to have. Until this is implemented, remove button from tip carousel

**Comment by ellemindwave** [comment]
@Danwhy I have added some dummy tips into the staging CMS to test this, but I can't find them on the front end of the staging site, even when the filter for 'tips' is selected
