### ISSUE TITLE
Customisable resource button text

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#299]
Button that currently says 'read reviews and join the discussion' on the resources on listings page. 

Depending on time this sprint, this needs to either 

a) be made customisable so that we can edit text (which would change all buttons like this across the site) (2 hours)

b) be hard coded to say the same thing on all buttons like this across the site (according to @sarahwelton 's wording) (25 mins)

**Comment by samhstn** [comment]
According to @sarahwelton's slack message, this button should say: "Get more info and discuss with others"

![screen shot 2017-09-12 at 16 10 42](https://user-images.githubusercontent.com/15983736/30333523-0aadc086-97d5-11e7-9948-6c7b64e4926c.png)

**Comment by samhstn** [comment]
@ellemindwave we've implemented (b), let us know if you would like us to go about implementing (a)
