### ISSUE TITLE
'Local' badge appears within 1 mile of user

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#302]
Relates #275 

When a user is searching, any resource (offline) that is located within 1 mile of them will show a 'local' badge on the listings page

**Comment by ellemindwave** [comment]
@shouston3 have you been using a particular resource to test this? Just wondering how I can test this if I am currently sat in Walthamstow!

**Comment by samhstn** [comment]
@ellemindwave 
Assign a resource latitude, longitude of within 1 mile of where you are.
Open a new browser window (you should see the location tracking message at the top of the page).
When you view the resource which is within 1 mile of you, it should have the `near me` badge.
When you view another resource which is not within 1 mile of you, you shouldn't see it.
We can go through this together tomorrow if you'd like.

**Comment by ellemindwave** [comment]
@shouston3 I have managed to do this on The Sleep School 👍 

However, it also has my badge that I added to another resource (can't remember which one!) earlier to test simply being able to add a badge to a resource

Is this because right now whether or not the badge shows is not due to which resource it has been put on but on how close the resource is to me?

There is not an option on the back end to get rid of the pink 'test' badge from The Sleep School

![screen shot 2017-09-13 at 15 17 03](https://user-images.githubusercontent.com/26304634/30382669-ab77eb0a-9897-11e7-9d2e-e99ba3b0b341.png)

**Comment by samhstn** [comment]
@ellemindwave 
Strange, I couldn't manage to remove the badge from the admin view either. I removed it from the database manually and put it in again with the admin view, it should all behave normally now.

See https://ldmw-staging.herokuapp.com/admin/pages/96/edit/

If you manage to make that bug occur again, make a note of how you managed it and we can look at fixing it.
