### ISSUE TITLE
Images are personalised according to first 2 letters of postcode

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#303]
The hero image on landing page is dependent on the postcode of the IP address of the user. 

Example, someone searching in North West, gets the 'NW' image as their landing page image.

Wagtail needs to know to discount numbers from this, for instances where the postcode only has one letter, i.e. E17

**Comment by ellemindwave** [comment]
@shouston3 @Danwhy Where will these images get stored, just in the normal image library on Wagtail along with everything else? and what is the process for labelling them to make sure they will appear?

**Comment by samhstn** [comment]
@ellemindwave I was planning for these images to be added to each `home` resource and that resource hero image could be overwritten if there is an appropriate postcode specified from the cms and the user is in that location
