### ISSUE TITLE
Ability to add postcode of a resource in Wagtail 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#304]
Need to be able to add the location (postcode) of an offline resource in Wagtail

This is needed for the system to know when to show the 'local' badge on a resource, and will be needed for more Geolocation development down the line

**Comment by Cleop** [comment]
@ellemindwave this issue is a step in the process of https://github.com/LDMW/cms/issues/302, the time estimate applied to #302 is for the completion of the whole feature. That is why I haven't added an estimate to this one in case you were wondering!

**Comment by samhstn** [comment]
@reddog suggested inputting latitude and longitude as this will be much easier to implement from our side and we can look at postcodes if we have more time.

This has been implemented with respect to #302
