### ISSUE TITLE
Some titles are missing on resources 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#309]
- Elefriends
![screen shot 2017-09-08 at 09 53 57](https://user-images.githubusercontent.com/26304634/30203939-b6889794-947b-11e7-8c59-544688f2df6a.png)

- NHS Choices Anxiety page
![screen shot 2017-09-08 at 09 54 03](https://user-images.githubusercontent.com/26304634/30203944-bb5cddc0-947b-11e7-9fea-f11849b010f0.png)

**Comment by Danwhy** [comment]
This was because the heading field had accidentally been removed at some point, meaning when new resources were created you didn't get the option to add a header. Should be fixed on the live site now
