### ISSUE TITLE
Recurring internal server error

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#312]
Appears when I clicked on 'view live' for the resource 'Quora' from Wagtail. Happens fairly frequently, I will drop examples in here when it happens again

![screen shot 2017-09-08 at 10 01 31](https://user-images.githubusercontent.com/26304634/30204555-ca7b9b82-947d-11e7-82fe-f9e5fea1f9b1.png)

**Comment by samhstn** [comment]
There is no longer internal server errors for this url. The problem was occurring whenever a url ended with `sleep/`.

This should be fixed on https://ldmw-staging.herokuapp.com/

**Comment by ellemindwave** [comment]
@shouston3 I can't find the Quora resource page on the staging site, and I'm not sure which one is the correct staging CMS! All the times I have tried to open it just now it has still given me the error, but I'm assuming this isn't reflected on the live site. 
Would you mind pasting the Quora staging link on here so I can check? Thanks

**Comment by samhstn** [comment]
I've just adjusted it in the admin view.

Here you are:
Admin view - https://ldmw-staging.herokuapp.com/admin/pages/106/edit/
Live view - https://ldmw-staging.herokuapp.com/resources/quora-sleep/
