### ISSUE TITLE
No text box underneath ' Are we missing something? ' on homepage

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#313]
The text box has disappeared 
![screen shot 2017-09-08 at 10 10 14](https://user-images.githubusercontent.com/26304634/30204619-fe19162c-947d-11e7-9ab8-527d73ff5d23.png)

**Comment by samhstn** [comment]
Should be testable on https://ldmw-staging.herokuapp.com/

**Comment by ellemindwave** [comment]
Thanks @shouston3 . When I enter something and press the submit button, I am met with an internal server error: 

![screen shot 2017-09-12 at 14 54 47](https://user-images.githubusercontent.com/26304634/30329507-5a1a7c64-97ca-11e7-8cc7-135038c30fa0.png)

**Comment by samhstn** [comment]
We'll fix that
