### ISSUE TITLE
Full 4 section footer on all pages

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#317]
All pages ( static Ts & Cs, Project background etc and individual resource pages) to have the full 4 section footer

**Comment by samhstn** [comment]
There is a 4 section footer on https://ldmw-staging.herokuapp.com/

**Comment by ellemindwave** [comment]
@shouston3 Just checking that this doesn't interfere with the ability to add logos into the footer?

**Comment by samhstn** [comment]
I've added a couple of footers to the [staging site](https://ldmw-staging.herokuapp.com/)

**Comment by ellemindwave** [comment]
👍  Thanks!
