### ISSUE TITLE
Generation of URLs on clicking 2nd and 3rd filters

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#321]
In addition to the friendly URL (#296) that is generated after the first filter, further URLs should be generated when user clicks through the second and then third, filters. 

The URLs generated from the second and third filters will be unfriendly.

**Comment by Danwhy** [comment]
@ellemindwave @sarahwelton Currently urls such as https://www.londonminds.co.uk/sleep-deprived/?issue=insomnia&reason=often&content=paid work to prepopulate the tags on the page, with the parameters being `issue`, `reason`, and `content` to match the tags.

Are these tags ok, or would you prefer something more generic such as `q1`, `q2`, `q3`? (https://www.londonminds.co.uk/sleep-deprived/?q1=insomnia&q2=often&q3=paid). I know that the `reason` tag doesn't really match up with it's corresponding question in the filter list any more (It's now '_How often are you (or they) affect by this? (select most relevant)_', when it used to be '_Is anything in particular affecting your sleep?_'

**Comment by ellemindwave** [comment]
@Danwhy I think something more generic here would be best, as the questions will vary from page to page, and also may change lots as we develop further. Q1, Q2, Q3 works well
Is this an easy thing to do?

**Comment by Danwhy** [comment]
:+1: No problem, just a matter of changing the names in a few places
