### ISSUE TITLE
Topic cubes cards on homepage should be vertically aligned and same size

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#327]
1.  Visit https://www.londonminds.co.uk/
2.  Current landing page cards are for `Anxious` and `Sleep deprived`.

Should these be top vertically aligned?

![image](https://user-images.githubusercontent.com/151362/30281316-fa11fbe6-9709-11e7-9be6-1499152ecb0d.png)

@ellemindwave / @sarahwelton If they should, could you alter the title of this issue so that it's addressed (at some point)

**Comment by Danwhy** [comment]
@ellemindwave @sarahwelton 
Top vertically aligning the boxes would cause them to not be aligned at the bottom, is that ok?

The only way to prevent this would be to fix the height of the boxes so they're all equal. But this would require setting a character limit for the description to ensure it fits in the box.

**Comment by ellemindwave** [comment]
@Danwhy please can we fix the height of the boxes so they are all equal?

The character count should be 200
