### ISSUE TITLE
Missing feedback option / link on homepage

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#328]
1.  Visit homepage at https://www.londonminds.co.uk/
2.  In the `Are we missing something?` the statement ends with a `:` inviting users to leave feedback but there's no box to do so or link to go elsewhere to do so

![image](https://user-images.githubusercontent.com/151362/30281416-40a41b52-970a-11e7-8d64-c7137f94ddb1.png)

**Comment by ellemindwave** [comment]
@reddog I have already highlighted this bug in issue #313 . Will close as it's a duplicate

**Comment by reddog** [comment]
Argh - sorry!
