### ISSUE TITLE
Expert 24 - distinguishing between users of LDMW and other platforms

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#331]
Email from Mike at E24: 

"Kat has pointed out to me that she will need to distinguish between LDMH users and users from other platforms. We do this by setting the UserType when we make the Member call to the API. May I suggest the following simple change to the code created on Friday?
 
When we call the endpoint
 
http://apps.expert-24.com/WebBuilder/TraversalService/Member
 
We pass the payload :
 
{
  "callback" : "raw"
}
 
If we add a @UserType parameter to this, we can flex our algorithms for LDMH accordingly.
 
The new payload will look like this:
 
{
  "callback" : "raw",
  "@UserType" : "300"
}
 
Can you pass this onto Dan, I’m sure he’ll know exactly what to do."

**Comment by shouston3** [comment]
@ellemindwave I don't really know how you could test this.

It has been implemented and we can reopen this issue if Expert24 need more user distinguishing.
