### ISSUE TITLE
Open Graph

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#349]
Suggested as important to have on the site by David at Fresh Egg

Open Graph
The Open Graph protocol enables any web page to become a rich object in a social graph. For instance, this is used on Facebook to allow any web page to have the same functionality as any other object on Facebook.
These four properties are required to implement Open Graphs tags:
• og:title - The title of your object as it should appear within the
• og:type - The type of object (e.g." article"). Depending on the type specified, other properties may also be required.
• og:image - An image URL, which should represent your object within the graph.
• og:url - The canonical URL of your object that will be used as its permanent ID in the graph
Furth information can be found at: http://ogp.me/

**Comment by ellemindwave** [comment]
@shouston3 Similarly, how can I test this and show Fresh Egg it is done?

**Comment by samhstn** [comment]
One way to check is to view the html for the page and see that there are the correct tags for twitter and og to read. I can show you tomorrow if you'd like
