### ISSUE TITLE
Twitter cards

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#350]
Also suggested as important to have on the site by David at Fresh Egg

Twitter Cards
Twitter Card tags look similar to Open Graph tags, and are based on the same conventions as the Open Graph protocol. With Twitter Cards, you can attach rich photos, videos and media experiences to Tweets, helping to drive traffic to your website and allowing you to go beyond the 140-character limit of the platform.
Once you have added the Twitter card code to your website, use the Twitter Card Validator to make sure it’s working.
You can learn about the different mark-ups here: https://dev.twitter.com/cards/getting-started

**Comment by samhstn** [comment]
@ellemindwave For the twitter cards we need to know what to fill in for the following fields:

- [x] twitter @ handle for the site
- [x] twitter @ handle for whoever is the content manager
- [x] Image for the site (should we use whatever the background image is - currently the St Pauls image)

**Comment by ellemindwave** [comment]
@shouston3 

Twitter handle is @goodthinkinguk
Twitter handle for content manager, by this would this be the person who is going to be interacting with users on Twitter?
Image - will this dynamically pull through whatever is the homepage image on the site or do we need to specify an image?

**Comment by samhstn** [comment]
We can just make the content manager @goodthinkinguk

**Comment by ellemindwave** [comment]
@shouston3 how can I test this and show Fresh Egg that it is sorted?

**Comment by samhstn** [comment]
Same way as #349
