### ISSUE TITLE
Cookie banner should not cover footer

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#355]
According to UX and Accessibility guidelines, cookie banners shouldn't actually obscure or hide information, and as not everyone closes them, we wouldn't want things to be hidden from those that don't close it. 

How much work would be involved in making the cookie banner just appear at the bottom of the page but not over the footer?

**Comment by samhstn** [comment]
I'd say less than 1 hour.

@Danwhy would it just be as simple as dynamically adding a blank div below the footer which is the same height as the cookie banner, then removing it dynamically when cookies are accepted?
