### ISSUE TITLE
Website name not in browser title tab - should it be?

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#357]
1.  go to a page at https://ldmw-staging.herokuapp.com/
2.  the website name, currently "London Minds", isn't displayed in the browser tab

Should it be?

Should it be shown something like "Sleep Deprived | London Minds", or "London Minds | Sleep Deprived"?  Don't know if content/marketing people should be asked?

If so, please change the issue title and prioritise.

![image](https://user-images.githubusercontent.com/151362/30432491-c33e3740-9959-11e7-894a-a5e80086dcae.png)

**Comment by sarahwelton** [comment]
Name should be eg "London Minds | Sleep Deprived" in tab

**Comment by samhstn** [comment]
@sarahwelton should I make it "Good Thinking | Sleep Deprived"

**Comment by ellemindwave** [comment]
@shouston3 Yes please 👍
