### ISSUE TITLE
On first question of PYR section, not all options are shown at the start

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#361]
On mobile, when on the first question of the personalise your results section, you can't see all the options as standard, you need to scroll. There isn't anything that indicates you need to scroll, though...

![image uploaded from ios 13](https://user-images.githubusercontent.com/26304634/30439687-60cb1304-996c-11e7-8b7c-906255996b79.jpg)

**Comment by sarahwelton** [comment]
There shouldn't be a scroll option - they should all be visible.

**Comment by ellemindwave** [comment]
@sarahwelton thanks
@shouston3 @Danwhy what implications does that have for the size of the boxes in the scroll through?
It might mean that the section is huge and takes up the whole screen on mobile...? 
Could there be a little arrow to indicate more are there but hidden?

**Comment by sarahwelton** [comment]
The width of the question block can be wider - eg 5px space between edge of screen and start of block so will get a couple more in. 

On my phone, there is room for all to appear plus the "next question" button as well... can we try it?

**Comment by samhstn** [comment]
We can add a permanent scrollbar

**Comment by sarahwelton** [comment]
Id rather it was all visible than have a scroll if poss - but aware we need to see if thats feasible first. Perhaps a scroll bar can be fall back at a certain height?

**Comment by samhstn** [comment]
@sarahwelton Agreed, I've implemented scrollbars only for mobile when there are more than 4 tags, this was easier than basing it on height.
