### ISSUE TITLE
Is it possible for there to be a field for mobile topic section name?

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#375]
On desktop, there is the line 'I am , or someone I know, is feeling...' above the topic cubes which then makes sense that the topic cubes are named as adjectives i.e. anxious, sleep deprived... etc

On mobile, this appears a bit random as it says 'browse topics below' but the topic cubes are still called 'anxious' 'sleep deprived' etc. 
Is it possible for them to have different names on mobile i.e. the noun; 'anxiety' , 'sleep deprivation' so that they make more sense?

**Comment by samhstn** [comment]
Yea that's possible, we'll add another title called `mobile title` to the resource which we can show when the user is on mobile

**Comment by ellemindwave** [comment]
Awesome - thanks @shouston3

**Comment by ellemindwave** [comment]
Hi @shouston3 can you please link me to where I can test this? I can't see it on the staging CMS

**Comment by samhstn** [comment]
In each of the home pages, inside of the `link block` section, there will be a `mobile title` which will show only on mobile.

Here is the [sleep-deprived homepage](https://ldmw-staging.herokuapp.com/admin/pages/138/edit/)
