### ISSUE TITLE
Drop down is stuck on selection, can't reselect or change choice

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#382]
(iPhone 5, safari)

After having selected order by 'most recommended', you then cannot click into the dropdown to change your selection:

![image uploaded from ios 17](https://user-images.githubusercontent.com/26304634/30491649-cf857c3e-9a35-11e7-82c1-1400d5dc5dec.jpg)

**Comment by samhstn** [comment]
We are currently unable to replicate this bug. @ellemindwave could you try and describe how you ran into this situation.

We can go through this tomorrow if not.
