### ISSUE TITLE
Menu on mobile

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#387]
Burger menu on mobile has disappeared. Need to bring this back on all pages.

**Comment by samhstn** [comment]
This seems to have been removed on the landing page, we've added this back in

**Comment by ellemindwave** [comment]
Menu is back, but the white band it appears on is now obscuring the header

(chrome, iphone 6)

![image uploaded from ios 18](https://user-images.githubusercontent.com/26304634/30550364-22770164-9c8f-11e7-8cef-bf80998e6a6b.jpg)


Also, spacing of wording on cookie banner is off. will add a different issue for that!

**Comment by ellemindwave** [comment]
@shouston3 is this to do with having removed the logo and there needing to be padding at the top of the page? If so, the menu is back so I will close this issue and there is another for the padding (in @Cleop 's styling tweaks list)
