### ISSUE TITLE
All external links to open in new tab, not just URLs for resources

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#393]
Currently the URLs do, but we need all links to open in new tab, including those in body text.

**Comment by Danwhy** [comment]
By body text, do you mean text coming from Wagtail? If so that would vastly increase the time for this issue as it would involve writing code to change what comes from wagtail, which we'd have to be very careful not to break.

**Comment by reddog** [comment]
@Danwhy How are these pages currently generated?

Could a Django template filter work?  Something like a combination of:

- https://stackoverflow.com/questions/35477483/how-to-replace-a-comma-with-an-underscore-in-django-template-filter example of template filter
- https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#force-escape example of adding filtering to built-in `body` tag

I guess the requirement here wouldn't be to replace a comma, but to augment the `<a href...` tag.

**Comment by Danwhy** [comment]
@reddog The text from wagtail is being run through a richtext function, so I think you're right and we could probably just chain another function to augment the anchor tags after they've been generated.

The only other thing to consider is how to differentiate between external and internal links, but it could just be a case of using a regex to check whether or not it's a relative url.

**Comment by reddog** [comment]
@Danwhy Thanks for that.  Does that give you enough to provide a time estimate?

**Comment by Danwhy** [comment]
This is now on staging to test, there's an external link on [sleepio](https://ldmw-staging.herokuapp.com/resources/sleepio/) that can be used to test it
