### ISSUE TITLE
Space for explanatory copy above PYR section

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#396]
Space for line of copy just above question block. 
Field for editing this copy in Wagtail

![screen shot 2017-09-18 at 14 49 24](https://user-images.githubusercontent.com/26304634/30545145-b34e4382-9c80-11e7-82dd-83baa0f46e29.png)

**Comment by Cleop** [comment]
@ellemindwave - above or underneath the title 'personalise your results'?

**Comment by katbow** [comment]
I'm adding this section to wagtail as PYR text. Let me know if you want it to display above or below "Personalise your results:" @ellemindwave and I will add it in to the html 👍

**Comment by katbow** [comment]
asked @sarahwelton and it will be going below the title. Also, the title was changed to "To personalise your results, answer three quick questions below:" which was to cover not having an explanatory section. It will be changed back to "Personalise your results:" and the explanation will be editable on wagtail.

**Comment by katbow** [comment]
@ellemindwave I've added sample text for this page in wagtail for staging site. https://ldmw-staging.herokuapp.com/trouble-sleeping/
