### ISSUE TITLE
Add space for copy underneath “Showing XX Results” 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#397]
![screen shot 2017-09-18 at 15 14 09](https://user-images.githubusercontent.com/26304634/30546258-0dbeb204-9c84-11e7-9826-e59817d99319.png)

**Comment by Cleop** [comment]
@ellemindwave - How big should this space be? Do you want a new field on wagtail or does one already exist? Do you want the space to be there even if there is no copy?

**Comment by reddog** [comment]
@Cleop Just wanted to check, this issue isn't in a sprint to be addressed at the moment.  Other than that, your comment is definitely valid and required!

**Comment by ellemindwave** [comment]
This issue is no longer needed due to the new 'missing x, x & x' tags that appear above search
