### ISSUE TITLE
Feedback loop has disappeared on mobile

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#403]
No longer appears after having visited a third party site on mobile 
(chrome, iphone 6)

**Comment by shouston3** [comment]
It turned out to not be possible to refresh a page while opening a new tab on mobile.

We just open the link in a new page.

When the user refreshes the page or comes back to that page, they will then see the feedback loop.

**Comment by samhstn** [comment]
Can we delete this issue in favour of #402 ?

**Comment by ellemindwave** [comment]
Woops! My GH did something funny there. Deleted this one
