### ISSUE TITLE
some of text in feedback loop hidden on mobile

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#405]
Just says 'why have you chosen', as you can't see the rest. 

Can this be fixed?

![image uploaded from ios 19](https://user-images.githubusercontent.com/26304634/30553985-d93dbf7c-9c9a-11e7-8c25-7ed9e1e59bf4.jpg)

**Comment by katbow** [comment]
@ellemindwave I can make it go across the length of the box (with padding), but if the text happens to be longer than that still I would suggest a reword. I'm just starting this now so I will post a screen shot of how it looks when the text input is wider!

**Comment by katbow** [comment]
![image](https://user-images.githubusercontent.com/1287388/31831597-f504c3ec-b5bb-11e7-903c-74f0ca69aff2.png)

@ellemindwave on mobile screens this will be cut off even at full width. Is there any other wording we can use so it's not cut off? Above is the smallest mobile screen.

**Comment by ellemindwave** [comment]
@katbow please can we change the text to : 

'Tell us why'

Thanks
