### ISSUE TITLE
scroll transition search to results/homepage arrow

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#415]
On the homepage chevron down to topics

and

When clicking 'search' from PYR section down to results

**Comment by reddog** [comment]
@Danwhy What's the proposed solution here?

Should be straightforward with jQuery and/or native browser (available in some cases, see https://caniuse.com/#search=scrollintoview ), see https://css-tricks.com/snippets/jquery/smooth-scrolling/ for a fairly full jQuery and native examples.

**Comment by ellemindwave** [comment]
@katbow @Danwhy this appears to work fine on desktop but not on mobile

**Comment by katbow** [comment]
@ellemindwave can you let me know which mobile devices and if it is on the actual device or using dev tools? Works alright on the phones I tested in dev tools & on my phone. Also, is it both the chevron & the search button that are not smooth scrolling to the item, or just one of them? They were implemented slightly differently, so I will need to know which implementation to look at for the fix.

**Comment by ellemindwave** [comment]
iphone 6, chrome - chevron doesn't go pink and doesn't jump
search button jumps

iphone 6 safari - chevron jumps, search button jumps

**Comment by katbow** [comment]
This is about half done now (so about half time left to complete the rest). The implementation needs to be done for the PYR search button.
