### ISSUE TITLE
When submitting single resource feedback, suggestions submitting successfully is a bit large

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#416]
reduce to look neater

**Comment by reddog** [comment]
@ellemindwave Reduce to what size?

**Comment by katbow** [comment]
![image](https://user-images.githubusercontent.com/1287388/31890369-ce7112da-b7fa-11e7-9532-3870e281e044.png)

Here's the current look. Is the text too large or the green box, or both?

**Comment by katbow** [comment]
@ellemindwave we can also change the text to a shorter message which will help with size more on mobile if that was the concern.

**Comment by sarahwelton** [comment]
"Thanks for your feedback"

**Comment by ellemindwave** [comment]
@katbow The green box is too big, please could it be reduced so that there is the same amount of padding between either side of the text and the edges of the box?

And please change to what @sarahwelton suggested above. Thanks!

**Comment by katbow** [comment]
@ellemindwave when checking this you'll notice there's a prob with the burger menu. I picked it up already and put it in #725!
