### ISSUE TITLE
Transfer of code from DWYL to MV GH

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#469]

**Comment by reddog** [comment]
@Cleop Do you need to make me an owner of the LDMW repos for us to do this?

**Comment by Danwhy** [comment]
@reddog I've made you an admin of this repo, so you should be able to transfer it to the mindwave organisation

**Comment by reddog** [comment]
@Danwhy Thanks for that.  Is there a point in the near future that you or someone else from the Dwyl team are working on the project?  If so it would seem to be good to move it then in case of any issues, rather than do it now and not be able to fix up anything that breaks.

**Comment by iteles** [comment]
@reddog I believe @ellemindwave will know the answer to this question better than we do at the moment 😊 

At the moment, we are not scheduled to be working on LDMW in the near future, but our earliest availability to be 'on standby' is Monday of next week 👍

**Comment by reddog** [comment]
This was completed, see https://github.com/mindwaveventures/cms
