### ISSUE TITLE
Add new favicon

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#470]

**Comment by ellemindwave** [comment]
![01_favicon](https://user-images.githubusercontent.com/26304634/31775596-f2f46c32-b4e0-11e7-994c-ede18d1348e0.png)

**Comment by ellemindwave** [comment]
@katbow The favicon is still the same on staging ? and still not on the live site

**Comment by katbow** [comment]
@ellemindwave that's probably due to caching. It's not deployed to live site yet, only staging. I'll add an external dependency label and we'll have to check back on it.

**Comment by ellemindwave** [comment]
Okay, I will close this so we can deploy to live site, as it is essential for the favicon to be there!
