### ISSUE TITLE
Add arrows to tips to make it obvious that you can scroll through

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#477]
Currently the tips can only be scrolled through by seeing there is one after it horizontally. Needs to be more obvious

**Comment by ellemindwave** [comment]
Same arrow as the ones in the 'most recommended' drop down

**Comment by Cleop** [comment]
- Arrows to be clickable so that they scroll you to the next tip
- Use the same triangle in a circle asset that is on personalise results

**Comment by ellemindwave** [comment]
On iPhone 6, Chrome, I can see the arrow and it has the correct hover state, but when clicking it doesn't take me to the next tip. 

Works fine on desktop. I am trying it on the sleep-deprivation homepage on staging

**Comment by ellemindwave** [comment]
working now on mobile
