### ISSUE TITLE
When top menu open on mobile - page had massive white space and flashes when scrolling

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#479]
<img src="https://user-images.githubusercontent.com/26304634/30736159-942e26f6-9f79-11e7-9648-2b24ec7d5a4f.jpg" width=200px/>
To replicate: 
On mobile, go to a topic homepage.
Open the top menu
Try scrolling down the page

Big white space appears and the page won't load properly

<img src="https://user-images.githubusercontent.com/26304634/30736154-8e1df778-9f79-11e7-8f97-1a7e164eae55.jpg" width=200px/>

**Comment by Cleop** [comment]
- Discussed with @ellemindwave - bug is that you shouldn't be able to scroll on mobile when the menu is open. Only a bug on safari/iPhone

**Comment by katbow** [comment]
Note for self as I was finally able to get hold of an iPhone to check this out!

The burger menu has a set amount of whitespace to take up the height of the screen. When on iPhone, you can scroll up on this white space and even scroll past it to reveal the content below. Likely to do with [this section](https://github.com/mindwaveventures/cms/blob/533fd39a7ad0aedf194dc5cbae45f391182cf3ff/cms/static/js/hamburger.js#L31) in `hamburger.js`
