### ISSUE TITLE
Restyle location tags (1 mile away)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#486]
Text size 14 in #2dccd3 rounded rectangle 

![screen shot 2017-09-22 at 09 53 23](https://user-images.githubusercontent.com/26304634/30736749-f1a0f83e-9f7b-11e7-9d93-f29fddd17757.png)

- [ ] location icon to be provided by @indiamindwave24 (svg) to appear inline
- [x] New colouring
- [x] New rounded borders

**Comment by sarahwelton** [comment]
Need to match the above style too. Eg colour and border

**Comment by katbow** [comment]
We will still need the location icon for this one @indiamindwave24. How will it be positioned? Within the button and left/right of text? @ellemindwave @sarahwelton

**Comment by ellemindwave** [comment]
Hi @katbow , @indiamindwave24 will be doing this tomorrow and sending over

**Comment by indiamindwave24** [comment]
We have decided that this is no longer needed. This issue can be closed.
