### ISSUE TITLE
Increase block size on self assessment so that the options sit on one line?

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#488]
Currently quite hard to read:

![screen shot 2017-09-22 at 09 56 17](https://user-images.githubusercontent.com/26304634/30736849-52d74414-9f7c-11e7-8065-401a9b56df4f.png)

**Comment by reddog** [comment]
@ellemindwave What sort of display should there be for narrower screens?  Any responsive requirements?

**Comment by Cleop** [comment]
Revised scope: center the options, no size change.
