### ISSUE TITLE
Allow intro text on landing pages to have a "see more". 

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#496]
On topic landing pages, hide anything more than one paragraph of text in the intro copy behind a "see more" link. Once clicked, the additional paragraph content will reveal (and other page content will move down to accommodate)

**Comment by iteles** [comment]
The key here will be to ensure the JS and CSS are working across multiple devices.

**Comment by reddog** [comment]
@sarahwelton Can you clarify

> other page content will move down

Do you mean there should be an *animated movement* down to reveal the text behind `see more`, or just that the other page content will be vertically offset in order for the other text to be displayed?

**Comment by iteles** [comment]
@reddog This is an excellent question, we had assumed no _animation_ but at this final sprint stage, this is definitely a possible requirement!

**Comment by Cleop** [comment]
@ellemindwave to add word limit, and exact wording ie. '...continue reading' or 'see more'

**Comment by ellemindwave** [comment]
Further discussion on this, we are waiting until @sarahwelton is back to decide whether or not it might be beneficial to have the chevron on these topic homepages like on the homepage to jump people down to the 'personalise your results' question, OR make the whole paragraph hidden so that it doesn't take up so much room, especially on mobile

**Comment by ellemindwave** [comment]
Have spoken with @sarahwelton on this issue and she would like one paragraph to show. The word limit should be 90 words // 520 characters.
Anything further than that should be hidden with a 'continue reading' link, like on the resources in the results below.

The paragraph in **bold** that tells people what to do with the 'personalise your results' section should remain visible, and not be counted as another paragraph.

![screen shot 2017-10-04 at 16 56 42](https://user-images.githubusercontent.com/26304634/31185879-07f92054-a925-11e7-93ff-001140fcbf6f.png)

**Comment by reddog** [comment]
@ellemindwave With

> The word limit should be 90 words // 520 characters.

Should this be 90 words **or** 520 characters **or** something else (max of 90 words *or* 520 characters)?  What separates a word?  Just a space?  Hyphens don't separate words?  Will this length be sufficient to cover all cases?

> Which Way to West Water Way?

is much longer visually than

> I live in a tiny, tiny house.

(both 28 characters, I think!)

Just wanting to make sure there are no unexpected overflow cases.

**Comment by ellemindwave** [comment]
90 words should be fine. 
@sarahwelton do you have a preference?

**Comment by sarahwelton** [comment]
I'd usually do character limit rather than word - so 520 characters please. That negates the issue of spaces and hyphens. Yes this length will be sufficient (otherwise we would ask for more characters!) 

We will write to this spec - with additional paragraphs appearing when the user selects "read more". 

Animation not required. I was trying to be specific to ensure that the additional text reveals without overlapping the other content.

**Comment by Cleop** [comment]
Summary from Friday meeting:
- Apply 520 character limit to existing box with see more button. Internal team will be responsible for ensuring that characters are not splitting words.
- Create separate box on wagtail for bold section.

**Comment by Danwhy** [comment]
@sarahwelton Would it be easier for you if we just displayed the first paragraph and hid the rest? Then you could just format the paragraphs in wagtail as you want them, and not have to worry about sticking to an exact character limit.
It would be easier from a technical perspective too, as it means we don't have to worry about the html tags when counting/truncating the html string from wagtail.

**Comment by ellemindwave** [comment]
@Danwhy sorry for delay on answering this - Sarah was off sick yesterday and is on annual leave today. 
Just showing the first paragraph sounds like a good idea to me, especially if it is easier from a technical perspective. Thanks
