### ISSUE TITLE
Add corner curves to feedback submit bar, as on buttons

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#499]
Add corner curves on the feedback submit input, as on buttons

![screen shot 2017-09-25 at 15 02 20](https://user-images.githubusercontent.com/26304634/30812402-8fa4719a-a202-11e7-9aed-ce8505ac9974.png)

**Comment by katbow** [comment]
@ellemindwave the submit button here doesn't currently have curved corners either - would you like this added to that as well?

**Comment by ellemindwave** [comment]
@katbow Yes please, all should be consistent. Thanks!
