### ISSUE TITLE
Can we lower opacity of shadow on click (ie. light, more subtle)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#500]
![screen shot 2017-09-25 at 15 42 20](https://user-images.githubusercontent.com/26304634/30814536-680d507e-a208-11e7-9387-687abce9b061.png)

**Comment by katbow** [comment]
How much softer are you thinking? Here are a couple of options @ellemindwave. Let me know what you think.

![#949494](https://user-images.githubusercontent.com/1287388/31226342-ac625496-a9cd-11e7-9259-85fcd1f663bc.png)

![#464646](https://user-images.githubusercontent.com/1287388/31226393-da297026-a9cd-11e7-8fec-59e095ad4af9.png)

**Comment by ellemindwave** [comment]
Hi @katbow - the first option, please!
