### ISSUE TITLE
Round corners as on buttons for drop down

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#502]
![screen shot 2017-09-25 at 15 56 17](https://user-images.githubusercontent.com/26304634/30815103-1854a328-a20a-11e7-8fd5-f49806b7928c.png)

**Comment by iteles** [comment]
@ellemindwave We're assuming that this is only for this one filtering drop down, could you please confirm that this is the only one you're thinking of? (Checking because of the plural in the title of this issue)

**Comment by katbow** [comment]
@ellemindwave question for you here which I also have before starting 🙂  ^

**Comment by ellemindwave** [comment]
@katbow yes, just this dropdown please! Thanks for checking :)
