### ISSUE TITLE
Q2 and Q3 to filter and then re-order if no results

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#503]
An example: 

If a user selects "offline" but all of the other tags that are selected match, it is confusing to see online resources showing... 

Suggest the following solution:

**There are 2 resources that meet all of your criteria**
First set of results = matches ALL tags

**There are 17 resources that meet most of your criteria**
 minus "offline" 

**There are 34 resources that meet some of your criteria**
minus "offline"    |      minus "free"

**Comment by sarahwelton** [comment]
@ellemindwave can you check this makes sense?

**Comment by reddog** [comment]
@ellemindwave & @sarahwelton it would seem (from previous comments) that maybe this issue should be *sanity checked*?

If there is any ambiguity or uncertainty it should be re-checked that @Danwhy has the same understanding of what this issue is and what the require fix is.

**Comment by ellemindwave** [comment]
It makes sense, but I guess we would need to define what the **criteria** is for 'matches most' and 'matches some' of your criteria'

I.e. to match most, can it only have **one** tag that doesn't match, and to 'match some' can it only have **two** that don't match?

What would then happen for the rest of the resources, if there was something that only had one tag that matched?

Also, what if there is nothing that matches ALL of the tags? Does a message say that, too?

My worry is that if it says '
**There are 34 resources that meet some of your criteria 'minus 'can't sleep cause I can't stop thinking' and 'trouble getting up'**
It is making the search results area very busy, especially on mobile. But maybe not! :)

Also, how would you want this to affect the way that the results load currently? (3 to start with, and then the rest)

Would be good to maybe do a mock-up of how this would look on the listings page.

**Comment by sarahwelton** [comment]
I'll mock up on Weds

**Comment by Cleop** [comment]
What if I select both online and offline? As I may be open to results from both?

To be revisited once the conversations and implications for offline/online tagging have been had. Estimated will be revised accordingly. @Danwhy not to work on this until further notice.

**Comment by sarahwelton** [comment]
We are amending tagging so that they are either online OR offline ("digital" and "offline" as the tags to be more clear). 

But - even if you selected "paid" and "free" because you're open to both, you would still be able to see those results. Eg: 

<img width="650" alt="screen shot 2017-10-04 at 12 06 21" src="https://user-images.githubusercontent.com/26305143/31172706-89cd09fc-a8fc-11e7-98cf-2f3d64d902b6.png">


So 

**There are 2 results that match all of your critera** = ALL tags match

** There are 7 results that match most of your criteria** = "Most" (all but 1 or 2 tags) 

**There are 14 results that match some of your criteria** = "Some" (at least half)

Less than half results = hide 

I'll do a mock up

**Comment by Cleop** [comment]
**From user testing @sarahwelton informs us that the following things were established:**
- too many resources was overwhelming
- recommendations not being founded (leave this for now)
- relevance - not understanding that their favourite filter may be missing

**Decision:** 
- @sarahwelton / @indiamindwave24 - to mock up designs
-  As per google, missing filters will be listed so a user is able to see what is not there and understand their results better
- The MV team are going to review tagging to make sure some resources haven't been tagged too much.

**Comment by indiamindwave24** [comment]
![updated listings page copy](https://user-images.githubusercontent.com/25007700/31273019-e9bcbbe4-aa84-11e7-8a54-78226a31c697.png)

**Comment by Cleop** [comment]
@indiamindwave24 says that ignore the fonts of this wireframe, the tags should look exactly as they do elsewhere on the site apart from with the strikethrough. They should move onto a second line in the same way they currently do if there are multiple or you're viewing on a narrow screen.

**Comment by ellemindwave** [comment]
@Danwhy I can't seem to test this on staging, nothing looks any different. Do you have an example of a search that it works on?

**Comment by Danwhy** [comment]
@ellemindwave https://ldmw-staging.herokuapp.com/trouble-sleeping/?q1=sleep%20deprivation&q2=often&q2=relationships
