### ISSUE TITLE
Image on homepage should sit behind semi transparent global navigation

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#507]
As per the topic pages (but nav sits at bottom of image rather than top)

**Comment by iteles** [comment]
@sarahwelton We're not entirely sure what you mean here with this portion:
> but nav sits at bottom of image rather than top

Could you please paint us a picture? 😊

**Comment by sarahwelton** [comment]
<img width="1046" alt="screen shot 2017-09-29 at 16 29 41" src="https://user-images.githubusercontent.com/26305143/31023348-77aed8bc-a533-11e7-9504-3f83f713d5b8.png">

IGNORE ALL COLOURS! (And other differences, eg size of chevron...!) This is **just** to illustrate the image behind the nav bar. Hope that makes sense.

@indiamindwave24 - this is because the pattern has gone from behind the topic blocks. If you'd rather have the pattern back and not use the image behind the nav, then please could you close this issue and open a new one - thanks!
