### ISSUE TITLE
Titles on static pages to be same as other pages (to make them look better)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#509]
Static pages to have clear headers/titles

**Comment by sarahwelton** [comment]
Eg either have space for an image and white h1 over the top

OR

dark blue h1 as per other pages (eg LARGE text!)

**Comment by reddog** [comment]
@sarahwelton / @ellemindwave could we clarify which **or** is required here?  Are there different outcomes for different types of pages, or is a decision on one of these required?

**Comment by ellemindwave** [comment]
@indiamindwave24 please can you mock this up?

**Comment by Cleop** [comment]
Proposal to be able to make the headings on this page bigger so they stand out more. No need for image requirements.

**Comment by ellemindwave** [comment]
@Danwhy I can't test this as I just tried to create a static page on staging to play around with the header and I got an internal server error
![screen shot 2017-10-05 at 10 54 15](https://user-images.githubusercontent.com/26304634/31221445-a39a4308-a9bb-11e7-9a24-ffdd1f5fb911.png)

**Comment by ellemindwave** [comment]
Ignore me! tested and done 👍
