### ISSUE TITLE
Rearchitechuring some of the ways we are storing our data

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#51]
From #50 

### Resources

We currently have the resource page as the same type as the home page which leaves it with some unused fields.

We are planning to make Resources it's own page type (not a child of the home page) and ensure each resource is a child of the resources page

### Other static pages

The static pages are currently each their own page type, we should decide if we should keep these pages as a child of the home page or to have them on the top level

**Comment by Danwhy** [comment]
### Resources

Resources as their own page type, which we currently have, is a suitable way to display the resources, we just need to make sure their containing page is structured appropriately, ie: make a resources_index template which is rendered on the homepage, and itself renders all of the individual resources.

Resources should have their tags as they already do, but the top level tags we recently created would likely be better as 'categories'. Categories are a top level way to group content into pre-defined categories (These can be added via the wagtail admin panel), which are selected when a resource is created. These can be edited at any time, and more than one can be selected, but it should reduce the complexity of having so many types of tag.

**Comment by Danwhy** [comment]
`python manage.py move_pages {id} {from}` is the command used to move pages in wagtail. This means we don't have to worry too much about getting the structure exactly right in the first place, as it's relatively simple to change later.

**Comment by Danwhy** [comment]
Previously, we had a lot of different django apps, one for each type of page. This is not an ideal way of working with Wagtail, as it is not easy to render data between different templates in different apps. 

Now, we're going to keep the individual models for the different page types, but keep all related templates in the same apps. Initially, this means the homepage, the resources, and the resource_index page are all defined in the same django app. This allows us to get the resource data and render it on the home page, as well as allowing us to render the resources as individual pages if we wish to later.

**Comment by reddog** [comment]
@Danwhy This sounds like an interesting point.  Could you expand a little on how the *different django apps* are currently organised and in what way that will change?  Would be great to understand implications in terms of time to implement vs future flexibility.

It is certainly a near-term requirement for resources to render as individual pages, see *Sprint 8* in the milestones document at https://mhl20.slack.com/archives/C4TUL6HH9/p1499961956062412

> Resources have individual page

**Comment by Danwhy** [comment]
So the current/former structure of the django apps was very abstract, as we had no real requirement to structure the pages/data, we would just pull it through to the Phoenix side and organise it from there. So we had no real organisation, which now leads to a lot of different data completely disconnected from each other.

Moving heavily connected pages into one app means that the pages can access each others data easily, which is necessary for the filtering by tags/categories we'll want to do on the homepage. I've experimented with moving the pages together locally, and have had no real trouble, so the cost to development time should be minimal.

**Comment by samhstn** [comment]
#61 was the major change to restructuring the data, there is a little on the feedback page (see migration changes in #68), but in terms of planning this has been thought about and we are happy with the current plan for this. I don't think any further effort is needed to go into this. Closing for now.
