### ISSUE TITLE
Transfer 'app' code repo over to Mindwave

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#511]
Please make @reddog an owner so that we can also transfer this repo over. Thanks

**Comment by reddog** [comment]
This is for the repo at https://github.com/LDMW/app

**Comment by Danwhy** [comment]
@reddog I've given you admin privileges, so you should now be able to transfer the repo

**Comment by reddog** [comment]
Transferred to https://github.com/mindwaveventures/app
