### ISSUE TITLE
Move site onto new URL

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#513]
Move site onto good-thinking.uk

**Comment by iteles** [comment]
Will need access to the DNS for the new URL.

**Comment by ellemindwave** [comment]
@iteles if we have the (two, staging and live) Heroku apps transferred to us first, then we can do the DNS changes, which will save time.

**Comment by iteles** [comment]
In that case, we'll carry this out in #297 and this issue will sit with you 👍

**Comment by reddog** [comment]
Chosen domain name is `good-thinking.uk`

I have changed DNS nameservers and set up DNS for www.good-thinking.uk

Going to www.good-thinking.uk gives the following error:

![image](https://user-images.githubusercontent.com/151362/31135407-cf8c980e-a85c-11e7-9389-876d766bc792.png)

@Danwhy Is this a Wagtail configuration issue?  Is it expecting requests to come to www.londonminds.co.uk ?

**Comment by Danwhy** [comment]
Ah yes, I'll have to add the new url to the allowed hosts

**Comment by reddog** [comment]
@Danwhy Thanks for that.

Do we need the `www` version adding as well?

**Comment by Danwhy** [comment]
@reddog Apparently yes, [the new url](https://www.good-thinking.uk/) should be working now

**Comment by reddog** [comment]
@Danwhy Thanks for that.

**Comment by reddog** [comment]
Accessing site from https://www.good-thinking.uk/ is giving a SSL certificate error (because it's issued in the name of londonminds.co.uk not good-thinking-uk ):

![image](https://user-images.githubusercontent.com/151362/31136345-e2974702-a85f-11e7-8245-c830d8c9ab62.png)

**Comment by reddog** [comment]
Looks like Heroku's Automatic Certificate Manager has fixed things up:

![image](https://user-images.githubusercontent.com/151362/31137946-a59e78d4-a864-11e7-9bf0-28cb1f3bd513.png)

**Comment by ellemindwave** [comment]
@reddog What do we do about the fact that londonminds.co.uk is still live? Do we make it redirect to good-thinking.uk?

**Comment by reddog** [comment]
@ellemindwave options are:

1. Redirect to www.good-thinking.uk
2. Have it go "nowhere"

The domain (londonminds.co.uk) has Google Apps configured for it at the domain. Is email maybe set up for this domain? Is it required for good-thinking.uk ?

**Comment by ellemindwave** [comment]
Which option is the more standard procedure/ quickest?

Yes, so all of the apps that are configured for londonminds need to be transferred over to good-thinking.
Email was set up for londonminds, and GSuite is also required for good-thinking

**Comment by iteles** [comment]
I would suggest that in the immediate term you forward `londonminds` to `good-thinking` so that anyone who has been using `londonminds` isn't faced with an error rather than a webpage.

In the medium term, you might choose to drop londonminds altogether, particularly in light of any potential friction with other similarly named organisations!

**Comment by reddog** [comment]
@ellemindwave Who's doing the GSuite setup?  Who did it for londonminds.co.uk?  I can make the DNS changes required.

**Comment by ellemindwave** [comment]
@reddog Katy is going to look into it tomorrow

**Comment by ellemindwave** [comment]
Update @reddog - Gsuite is now set up! info@good-thinking.uk is the email address

**Comment by reddog** [comment]
Looks like @katyedwards has set up GSuite and the corresponding MX and DKIM DNS records - thanks :-)

**Comment by ghost** [comment]
Don't thank me - gsuite must have done that for me!

**Comment by ellemindwave** [comment]
Is there anything else remaining in this issue, or can I close it? 
The redirecting?

**Comment by reddog** [comment]
I've set the *naked* [londonminds.co.uk](https://londonminds.co.uk) to go to https://www.good-thinking.uk/

Redirect of www.londonminds.co.uk can be achieved with code.  We can add it to the list if it's required.
