### ISSUE TITLE
Further E24 integration

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#515]
We need to be able to attach our resources onto the various dispositions that come out of the Expert 24 algorithm, and determine ones that could be shown that relate to hidden tags. 

Mike from E24 is coming in on Friday 6th October to work with us on this, and by then Sarah & I will have a clearer idea and will have mapped out mock ups of what we need it to be able to do, including having run our ideas past Kat at E24 to see whether or not they are possible first. 

Estimated 1 day, and potentially more if needed on Monday 9th

**Comment by Cleop** [comment]
**Basic version**: providing resources linked to final assessment results
**Detailed version**: providing resources linked to individual assessment question answers in your final results page
Estimates tbc and revised on Friday with Mike

**Comment by ellemindwave** [comment]
@Danwhy is there anything still left to do on this from your side, or are @sarahwelton and I waiting for Mike to create an authoring system so that we are able to tag the dispositions ourselves?

**Comment by Danwhy** [comment]
@ellemindwave The functionality on my end should be fully complete. The only thing there may be left for me to do is a little ui/copy, as at the moment the resources are just appearing underneath the assessment results. I remember @sarahwelton had a quick mockup of the way the attached resources should display, but I can't find it on github. Do you think you could add that to this issue please?

**Comment by ellemindwave** [comment]
![screen shot 2017-10-12 at 12 00 03](https://user-images.githubusercontent.com/26304634/31492986-291c1e5a-af45-11e7-8b79-ca87afde8329.png)



![screen shot 2017-10-12 at 11 59 51](https://user-images.githubusercontent.com/26304634/31492957-0d7ee77c-af45-11e7-9ac4-9fca4fa327a3.png)

**Comment by ellemindwave** [comment]
@Danwhy Sorry it is fragmented, for some reason the whole file wouldn't upload - does that give you enough to go on?

**Comment by Danwhy** [comment]
@ellemindwave :+1: It's just the 'manage your mood' text that we're missing. Did you want that to come from the assessment on wagtail, so it can be customised per assessment?

**Comment by ellemindwave** [comment]
Yes please, sounds like a sensible option! thanks @Danwhy
