### ISSUE TITLE
Transfer templates 

### ISSUE THREAD

**Issue by Danwhy** [LDMW/cms#52]
Part of #50 
We need to take our existing Phoenix templates, convert them to Django syntax and transfer them into this repo. 

It would be good to look into django components, to avoid having to duplicate code.

- [x] Homepage #57 
- [x] Feedback page
- [x] Static pages

**Comment by reddog** [comment]
@Danwhy Has this been completed now?

**Comment by Danwhy** [comment]
:+1: Site has now been completely transferred to Django
