### ISSUE TITLE
Get rid of 'previous question' button on first page of self-assessment

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#520]
As it doesn't make sense here

**Comment by ellemindwave** [comment]
If possible, could we get rid of 'previous question' , and 'next question' read 'start' ?


![screen shot 2017-10-03 at 11 14 45](https://user-images.githubusercontent.com/26304634/31120375-1b9b15bc-a82c-11e7-867c-ff0880774205.png)

**Comment by Danwhy** [comment]
Now on [staging](https://ldmw-staging.herokuapp.com/self-assessment/) to test
