### ISSUE TITLE
'Continue reading' is not a clickable link on some resources

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#524]
For example - Stop, Breathe and Think

![screen shot 2017-10-02 at 15 32 12](https://user-images.githubusercontent.com/26304634/31082457-fe4f79ee-a786-11e7-9ba5-18b0bb3faff5.png)

**Comment by ellemindwave** [comment]
hi @Danwhy I can't test this on staging as the one it was broken on isn't on staging! :) Any way I can test?

**Comment by Danwhy** [comment]
@ellemindwave I'll deploy the fix with everything else to the live site and you can check the one that was broken before
