### ISSUE TITLE
Responsiveness - break point on topic homepages

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#528]
Breaking this down into its own issue for clarity. 

I am testing this on Chrome on desktop, macbook air

On topic homepages (listings pages), @indiamindwave24 and I have identified the point after which the site would need to switch to mobile view (otherwise the spacing and positioning of text starts to look bad)

I have taken a screenshot below, but to specify...
It is the point at which:
- [x] the two buttons are still sitting side by side in the beta banner, not one on top of each other

Like this:
![screen shot 2017-10-03 at 15 54 46](https://user-images.githubusercontent.com/26304634/31131876-4234604e-a853-11e7-8079-886e83c07423.png)
*NOT* like this: 
![screen shot 2017-10-03 at 15 55 31](https://user-images.githubusercontent.com/26304634/31131894-52a39e04-a853-11e7-8b1a-9d8874b3b332.png)

- [ ] the 'order by' and 'more resources' dropdown with its arrow are still all on one line

like this:
![screen shot 2017-10-03 at 15 56 17](https://user-images.githubusercontent.com/26304634/31131956-7955baaa-a853-11e7-98c5-ffd9a47b379c.png)

*NOT* like this:
![screen shot 2017-10-03 at 15 57 16](https://user-images.githubusercontent.com/26304634/31131992-8f2af17e-a853-11e7-97e5-f080973e2db3.png)

**After this point**, the view should change to be the same as mobile (i.e. pros and cons expandable etc)

**Comment by katbow** [comment]
@Danwhy this was completed as part of #549 and #550.

**Comment by ellemindwave** [comment]
@katbow if this was completed as part of the other responsiveness issues, shall I close this issue?

**Comment by katbow** [comment]
Sure thing. I referenced this issue in each of those now!
