### ISSUE TITLE
Set-up Search Console and attach to the new domain

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#536]
(and then give Fresh Egg the login details)

**Comment by katbow** [comment]
@ellemindwave it's attached to the new domain and you've been added as an owner!

**Comment by ellemindwave** [comment]
Thanks @katbow - how do I log in and add another user to this?

**Comment by reddog** [comment]
@ellemindwave Is this issue referring to Google Search Console, part of Google Webmasters?  https://www.google.com/webmasters/#?modal_active=none

**Comment by reddog** [comment]
@ellemindwave Is this issue for Google Search Console or some other thing?
