### ISSUE TITLE
Search description when individual resource link is unfurled is from homepage, not resource page

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#540]
When copying the URL for an individual resource page into Slack or elsewhere, the page/search description that comes with it is an old piece of text that used to be on the homepage 'body' field. 

@sarahwelton has now deleted that old homepage text from Wagtail, but it still remains when pasting a link for any individual resource page. 

We need to pull in the 'search description' from the 'promote' tab on the individual resources pages in Wagtail, rather than a description from the homepage, when sharing a link.

Hopefully the below screenshots help:
This description should be pulled from the 'search description' field in the 'promote' tab from the 7cups page in Wagtail
![screen shot 2017-10-05 at 09 46 44](https://user-images.githubusercontent.com/26304634/31221121-907fedf0-a9ba-11e7-8ecf-73e8eb94a65a.png)

**Comment by ellemindwave** [comment]
For some reason the links that I copy from the staging site don't unfurl in the same way as the links from the live site, so I can't test whether or not this is working correctly

**Comment by katbow** [comment]
It could be that the resource you were looking at didn't have a content description, like below.
![image](https://user-images.githubusercontent.com/1287388/31279624-940da470-aaa1-11e7-920b-da69458635b9.png)

If this were the case, it wouldn't show any extra info.

I added a description to the [sleep station resource](https://ldmw-staging.herokuapp.com/resources/sleepstation/) for you to check out.

![image](https://user-images.githubusercontent.com/1287388/31279722-f82ba06a-aaa1-11e7-86c5-9c638aca8f46.png)
