### ISSUE TITLE
Responsiveness on Self-assessment 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#543]
@sarahwelton @indiamindwave24 
What should the self-assessment look like on mobile?
It currently falls off the page, but as there is so much text, not sure of best option or how this should look?

(iPhone 6, chrome)
![22279097_10154762572616143_271575766_o](https://user-images.githubusercontent.com/26304634/31225497-486995ec-a9ca-11e7-9d0a-c5fe39380efa.jpg)

**Comment by katbow** [comment]
Option for this is horizontal scroll.
