### ISSUE TITLE
Provide David with project details needed for deployment switch

### ISSUE THREAD

**Issue by Cleop** [LDMW/cms#547]
@Danwhy to provide @reddog with env var details and any other relevant info he requires for the deployment switch. Feel free to add anything missing as a comment below.
Relates #284

**Comment by Danwhy** [comment]
@reddog I've created a document that hopefully should have everything you need: https://docs.google.com/document/d/1GfWkLJqKr9xjbXb8fIxATLymmXO7s3KqfSFEq4Ue_jg/edit
Let me know if there's anything missing

**Comment by reddog** [comment]
@Danwhy Thanks for that.
