### ISSUE TITLE
Update Thumbs up / down icons

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/cms#548]
[Thumbs_up_Thumbs_down.zip](https://github.com/mindwaveventures/cms/files/1362258/Thumbs_up_Thumbs_down.zip)

**Comment by Cleop** [comment]
Note from @indiamindwave24 - if these images when replacing the old ones look as thin as the old ones look on the site then let her know. These images are meant to be thicker and so if they don't look thicker she will give you a new version.

Current site thickness:
<img src="https://user-images.githubusercontent.com/16775804/31272771-ffcb1274-aa83-11e7-98c8-f6df6749dbfd.png" width=200px />

**Comment by katbow** [comment]
New thickness
![image](https://user-images.githubusercontent.com/1287388/31394276-d6190300-add5-11e7-8d1c-cf8c3275b978.png)
