### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Danwhy** [LDMW/cms#55]
Part of #50 
Look into Python/Django testing with `unittest`: https://docs.djangoproject.com/en/1.11/topics/testing/
We should also try to find a module we can use for code coverage.

**Comment by samhstn** [comment]
From here: http://django-testing-docs.readthedocs.io/en/latest/coverage.html

It looks like Django uses a moduled called [`django-nose`](https://pypi.python.org/pypi/django-nose)

We should look at getting travis to run this too

**Comment by Danwhy** [comment]
Tests setup, will continue as needed
