### ISSUE TITLE
Inactive / Selected buttons

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/cms#554]
#C0C0C0 colour

When on a page The button navigating to that page appears inactive. ie. the 'home' button when on the home page.

<img width="583" alt="screen shot 2017-10-06 at 3 03 45 pm" src="https://user-images.githubusercontent.com/25007700/31281649-013f303a-aaa8-11e7-9e44-f6be13e865f5.png">

**Comment by ellemindwave** [comment]
@Danwhy This works for the 'Home' button, but not the 'Get urgent support' and 'Take assessment' buttons also in the banner when you are on the associated pages
