### ISSUE TITLE
Consistent spacing across the whole site

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#558]
Spacing should be consistent: 

- [x] In between topic cards when stacked on mobile homepage
- [x] In between resource cards on mobile #584
- [x] Between the header and topic cards, and the 'are we missing something?' box and the footer (both currently have too much white space in between)

**Comment by katbow** [comment]
Extra space on the anxiety resource page (and possibly the others)
![anxious- nexus 5](https://user-images.githubusercontent.com/1287388/31340199-471ef08e-acfd-11e7-82b4-63f85a2e9f86.png)

There is an extra div, which is from when tips exist - they will display in this section.
![image](https://user-images.githubusercontent.com/1287388/31340264-7f344154-acfd-11e7-9324-2fb94910acf6.png)

**Comment by katbow** [comment]
I'm going to split the second part into it's own technical issue, as it will take more time than the original estimate due to the comment above.
