### ISSUE TITLE
Database Setup for Likes

### ISSUE THREAD

**Issue by Danwhy** [LDMW/cms#56]
part of #50 
We need to set up the database for storing/retrieving like/dislike data, and for storing the rest of the data that we send to the Google Sheets.

We're already using the [psycopg2](http://initd.org/psycopg/docs/) module for wagtail, so it would probably be a good idea to use for our other db needs.

**Comment by reddog** [comment]
Is the database not already set up for this (ie this data is already captured/displayed)?

Does this issue relate to the Python code required to do the storing/retrieval as opposed to the database set up itself?

**Comment by Danwhy** [comment]
Yes, sorry I could have chosen a clearer title. This issue just relates to writing the python/sql code using psycopg.

**Comment by Danwhy** [comment]
Closed with #70
