### ISSUE TITLE
Alignment across site

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#565]
Please can the following things align: 

- [x] ‘Are we missing something’ box should be exactly the same width as the topic cubes above them on all devices
![image uploaded from ios 1](https://user-images.githubusercontent.com/26304634/31337222-3bf4dad0-acf2-11e7-94a4-1bd0186ef024.png)

- [x] On mobile - make resources cards the same width as the 'personalise your results' boxes above them
![image uploaded from ios 2](https://user-images.githubusercontent.com/26304634/31337299-9160ca92-acf2-11e7-9128-aa0dd54639e3.png)

- [x] On mobile, ‘Would you recommend this’ should be left aligned to sit same as text above it
![image uploaded from ios 3](https://user-images.githubusercontent.com/26304634/31337363-ed3aa70c-acf2-11e7-8ffe-696990e2d667.png)

- [x] footer should line up with the resource cards above

**Comment by katbow** [comment]
@ellemindwave is this okay for when on larger devices once the topic cards no longer stack? 

iPad landscape
![image](https://user-images.githubusercontent.com/1287388/31382197-c3691276-adae-11e7-818d-2f89255bf8e9.png)

desktop, chrome
![image](https://user-images.githubusercontent.com/1287388/31382703-75dc3964-adb0-11e7-84af-0119e47f47bb.png)

I imagine we don't want it stretching all the way across to take up the width of 2 boxes!

**Comment by ellemindwave** [comment]
Update from @indiamindwave24 : yes, the box is to stretch all the way across and take up the width of two boxes please.

On a side note, the submit button on the top example you put there is very squished! Hopefully stretching it out will help that?

**Comment by katbow** [comment]
yep, that will help with that button looking squished.

**Comment by ellemindwave** [comment]
@katbow the 'Are we missing something?' box seems to have disappeared and the bar is just floating but not on a card:

iPhone 6, Chrome

![image uploaded from ios 6](https://user-images.githubusercontent.com/26304634/31438460-1b3f5f4c-ae80-11e7-9253-475820a7ffc5.png)

**Comment by katbow** [comment]
I thought that's what you were asking for when you confirmed [this comment](https://github.com/mindwaveventures/cms/issues/573#issuecomment-335446916). For that issue, I thought the "AWMS box" meant the entire box that section was in, rather than the text box itself. I'll add it back in.
