### ISSUE TITLE
Depression assessment button not sitting correctly on android

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#566]
![screenshot_2017-10-06-15-52-18](https://user-images.githubusercontent.com/26304634/31337557-c4e27a0e-acf3-11e7-95e5-9dffd4855de2.png)

**Comment by katbow** [comment]
@ellemindwave what is the correct way for it to be sitting? Is it with more padding underneath, or is it meant to hang over the bottom of the box (like the topic cards on the home page)?

**Comment by ellemindwave** [comment]
@katbow I just went to look on iPhone to check, and it appears the same on iPhone. 
It should hang over the bottom of the box like the topic cards on the homepage please!
Thanks

**Comment by katbow** [comment]
Sorry @ellemindwave, I know you answered this already but as I was going to do this one, I noticed on mobile the pattern is that the buttons *do not* overhang the edge of the box. 

Like this from the homepage
![image](https://user-images.githubusercontent.com/1287388/31379989-e474c5ac-ada7-11e7-92ed-7f919cfcdc4f.png)

or the get more info buttons on the same page
![image](https://user-images.githubusercontent.com/1287388/31380027-0582e83c-ada8-11e7-9630-744a5928ac51.png)

Would you still like this one to overhang or be in the box with more padding underneath like the images above?

**Comment by ellemindwave** [comment]
@katbow thanks for checking in - please can it be consistent with the rest of the buttons on the site - therefore, inside the box with extra padding.
