### ISSUE TITLE
On iPhone 5, individual resource pages the pros and cons box hangs off a line

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#568]
needs padding to separate them

![image uploaded from ios 3](https://user-images.githubusercontent.com/26304634/31338048-c0266d98-acf5-11e7-87f9-2ec1814ca9b4.png)

**Comment by katbow** [comment]
@ellemindwave I want to make sure I understand this right. When you say 

> the pros and cons box hangs off a line

is this referring to the `View pros and cons` button touching the grey dividing line above it?

**Comment by ellemindwave** [comment]
Yes - exactly ! Thanks @katbow

**Comment by katbow** [comment]
This has been merged, but I will need to wait to assign it. The change to how the pros and cons display on mobile is working on the list of resources, however on the individual resources it is breaking (it just shows as a list).

I checked this locally and it was working, so I'll take another look now that everything is merged together.
