### ISSUE TITLE
Padding to be consistent across all cards and blocks

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#569]
- [x] On the PYR section - ‘Next question’ and icon shouldn’t sit so close to the edge, should have same padding as left:

![image uploaded from ios 4](https://user-images.githubusercontent.com/26304634/31343835-b59d68fa-ad08-11e7-9c79-b8e1f6486260.png)

**Comment by katbow** [comment]
@ellemindwave what device is this happening on? Also, the padding between the icons for previous and next and the edges of the box look the same to me in that image. Can you further clarify or provide another example?

**Comment by ellemindwave** [comment]
Hi @katbow - apologies for not having given enough info.
I meant that the previous and next buttons should have the same padding from the edge of the card as the text above it does, i.e. the text and tags of the question look like they are further in from the side of the box that then previous/next question buttons

**Comment by katbow** [comment]
iPhone5
![image](https://user-images.githubusercontent.com/1287388/31385552-9d906966-adbb-11e7-95e7-983a4bd4bdf6.png)
iPhone5 with search button
![image](https://user-images.githubusercontent.com/1287388/31385576-b213a150-adbb-11e7-90f6-9a3e81e069d5.png)

iPad pro
![image](https://user-images.githubusercontent.com/1287388/31385677-f7225aca-adbb-11e7-864e-7a8b3bb3ba99.png)
