### ISSUE TITLE
Some of the footer text on topic pages is in italics

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#570]
On the anxiety homepage, for example, the text in the footer is in italics for some reason

**Comment by katbow** [comment]
@ellemindwave I have gone to https://www.good-thinking.uk/anxious/ on chrome and for me it looks like this:

![image](https://user-images.githubusercontent.com/1287388/31380511-7fc87408-ada9-11e7-8959-3f9cddcef71f.png)

Can you post some screenshots of where you see this happening, along with the url it happens on & device you are using?

**Comment by ellemindwave** [comment]
Hi @katbow - typically I can't recreate this now, they all seem to look normal and there is no random italics.... I will keep a look out for this again but for now will close this issue as it seems to be resolved
