### ISSUE TITLE
Ability to move tags to bottom of page

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#577]
On branded partner pages, such as Be Mindful & Sleepio, how easy would it be to move the tags to the bottom of the page?

**Comment by ellemindwave** [comment]
@katbow would this involve making it possible for the tags to be at the bottom of the page on a page by page basis, or once at the bottom of the page, would it be like that on all pages?

**Comment by Danwhy** [comment]
@ellemindwave We could make it so that any page that has branding information has the tags display at the bottom of the page. We'd just need you to give us an idea of how you'd like it to look

**Comment by ellemindwave** [comment]
Cool - sounds good. Will just need @sarahwelton to do a mock-up of how she would like them (she isn't in today)

**Comment by ellemindwave** [comment]
( issue on hold - don't work on it yet as not sure if it is needed)

**Comment by ellemindwave** [comment]
Have spoken with Sarah on this and it seems that if there were just a way to make the tags smaller and take up less space on the branded pages then this would be fine at this stage.
Any ideas of a revised estimate for doing that?

**Comment by sarahwelton** [comment]
Did we specify any requirements / provide any mock ups for this? @Danwhy @ellemindwave

**Comment by ellemindwave** [comment]
@sarahwelton nope, we didn't
