### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#58]
Like in the phoenix app (see here: https://github.com/LDMW/app/tree/master/web/templates/component), we should have a similar component setup.

It seems like the way to go is down the lines of [inclusion-tags](https://docs.djangoproject.com/en/dev/howto/custom-template-tags/#inclusion-tags)

**Comment by samhstn** [comment]
Inclusion tags look like the way to go for components. I have been unable to get them going and would like to put this on hold for now.

We should simply paste in each component for now and then abstract out components later

Example of how you can use them here: https://github.com/wagtail/wagtaildemo/blob/master/demo/templatetags/demo_tags.py#L30

For when the time comes to re-tackle doing this

**Comment by Danwhy** [comment]
Started implementing this in #67, will carry on with it

**Comment by Danwhy** [comment]
Implemented using [include tags](https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#include)
