### ISSUE TITLE
Break line in between questions on self assessment on mobile

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#580]
On the pages with lots of questions, on mobile it would be great to have faint grey break lines in between each question, to help the user read the questions and answer them more easily.

![image uploaded from ios 5](https://user-images.githubusercontent.com/26304634/31384171-ade5058e-adb5-11e7-948b-12242c74ba38.png)

**Comment by katbow** [comment]
@ellemindwave I just realised I added this for mobile **and** desktop. If that's not desirable let me know and I will remove on desktop.
