### ISSUE TITLE
Question from Fresh Egg around location functionality

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#585]
Question from Fresh Egg around 'near me/within 1 mile' location functionality:

"With regards to the 'location personalisation' functionality, are you able to find out how the website is storing that information (i.e. what format)? It would be useful as we might then be able to use it from reporting to show where people are accessing the service across London."

Are you able to expand on how the location of a user is stored by the site?

**Comment by Danwhy** [comment]
We're not storing users locations, we only have access to it while they're on the site
