### ISSUE TITLE
E24: Javascript validation for self assessment questions

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#587]
Javascript validation

This is for questions on the self assessment where there are several answer options, or a radio button that says 'none of the above'

From Mike: 

"After every input event, a JavaScript function is run to clear the contents or checked status of other inputs for the same question with differing input types.
 
    answers.e24ForEach(function(f) {
        if (f.name === input.name && f.type !== input.type) { // If the input element is from the same question but of a different type
            if (f.type === "radio" || f.type === "checkbox") f.checked = false; // clear checked
            if (f.type === "text") f.value = ""; // empty text
        }
    });
 
I will add the server side validation as well so that invalid combinations cannot be submitted."

**Comment by katbow** [comment]
Note: this is for when there is a list of checkboxes, which also have a radio button at the end marked "None of the above". When none of the above is true, then it should deselect all of the other checkboxes, if any.
