### ISSUE TITLE
Disposition properties

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#588]
Disposition properties

From Mike:

I have added a random selection of DispositionProperties for all endpoints reachable from the sleep algo. These will appear as an array of string in the DispositionProperties property.
 
{
    "Report": {
        . . .
        "DispositionProperties": {
            "Tags": [
                "dontpanic",
                "dontworry",
                "athome"
            ]
        }
    },
    . . .
    "AlgoName": "Sleep algo"
}

@Danwhy Is there an easy way that @sarahwelton and I can test whether or not this tagging works and we are able to tag resources and have them appear at the end of the assessment?

**Comment by Danwhy** [comment]
Anything that you add a hidden tag to, eg "dontpanic", will display for the disposition tagged with that tag, as long as the resource and assessment both have the same topic tag.

So if you add a 'dontpanic' hidden tag to a resource that has a 'depression' topic tag, when you get to the end of the depression assessment, that resource will show (if the disposition is also tagged 'dontpanic')

**Comment by Danwhy** [comment]
If it only works on the full algorithm at the moment, you may need to add one or more topic tags to the full assessment we currently have on the site
