### ISSUE TITLE
Get rid of legacy 'London Minds' from page titles

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#590]
![screen shot 2017-10-11 at 10 33 28](https://user-images.githubusercontent.com/26304634/31432908-c3b5bdbc-ae6f-11e7-9a0b-fa6bcddef336.png)

**Comment by katbow** [comment]
@ellemindwave all of the references to london minds in the titles now, but as @Danwhy mentioned in another issue, this is also dependent on google caching, so we will need to wait to see the change on search results.
