### ISSUE TITLE
Submit site map to Google

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#591]
It's a key SEO requirement to get the site understood much better by google. Not 'critical' for next Weds, but needs doing this month

**Comment by Danwhy** [comment]
Wagtail can be used to generate the sitemap: http://docs.wagtail.io/en/v1.12.2/reference/contrib/sitemaps.html

**Comment by Danwhy** [comment]
I've created the sitemap and submitted it to Google on the search console:
<img width="972" alt="screen shot 2017-10-12 at 17 26 54" src="https://user-images.githubusercontent.com/8939909/31507452-a3acd498-af72-11e7-9a07-ada2b1460029.png">
