### ISSUE TITLE
Page titles and descriptions for Google search

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#596]
From Kate: 
@ellemindwave @Danwhy
The page titles and search descriptions put into Wagtail for the resources don't seem to be pulling through / showing up on a Google search. 
The screen grab below shows that it seems to be the first paragraph pulling through, rather than the search description... Please can you look into this as we need Google to pick up the wagtail page titles and descriptions for SEO. 

![image](https://user-images.githubusercontent.com/26304634/31437102-07632d4a-ae7c-11e7-91ef-b7c2420b4590.png)
![image](https://user-images.githubusercontent.com/26304634/31437115-108e49c2-ae7c-11e7-98fc-03044741fa15.png)
![image](https://user-images.githubusercontent.com/26304634/31437120-14ea7fb8-ae7c-11e7-921e-034d48fc024c.png)

**Comment by Danwhy** [comment]
Just waiting on Google caching to update for this now
