### ISSUE TITLE
increase vertical padding for line break self assessment questions

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#598]

**Comment by katbow** [comment]
@ellemindwave just checking in on this - are we waiting on the change from displaying them vertically before committing to this one?

**Comment by ellemindwave** [comment]
@katbow this one isn't as relevant anymore due to the new layout, however, it would perhaps make sense to increase the vertical padding in between the questions that are just check boxes, i.e. ones like this, as they are still quite hard to read on mobile and on desktop:

And it would be great if the ones that go onto two lines could be aligned with the first row, i.e. the word 'sleep' of the 4th question.


![image uploaded from ios 9](https://user-images.githubusercontent.com/26304634/31507045-369cef42-af71-11e7-9846-ac2da70ed5b6.png)
