### ISSUE TITLE
Layout of self-assessment

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/cms#601]
Can the self assessment be vertically positioned? Rather than scrolling horizontally.
How much work would be required to change this?

eg.

Question
[] option 1
[] option 1
[] option 1
[] option 1

Question
[] option 1
[] option 1
[] option 1
[] option 1

even if they have the same answers.

___ 

This should overcome the issue we are having with overcrowding due to everything trying to be fit into the horizontal  space

**Comment by Danwhy** [comment]
@indiamindwave24 @ellemindwave Would this be an alternative to the current table layout (ie, just show like this on mobile), or would it replace it completely?

**Comment by ellemindwave** [comment]
@Danwhy  just checked with @indiamindwave24 and it would replace it completely, but let's wait to see what  @sarahwelton 's thoughts are tomorrow

**Comment by ellemindwave** [comment]
@Danwhy across all devices, please!

**Comment by sarahwelton** [comment]
![assessment styling](https://user-images.githubusercontent.com/26305143/31501283-b20ec52a-af61-11e7-84e5-69a60cd0c008.png)
