### ISSUE TITLE
Check redirect from londonminds is working on all browsers

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#609]
Chrome, IE and Canary - on my phone is fine, but not on desktop

Also - londonminds.co.uk is still a live site?
This needs to be 301 redirected (and the same for all it's associated URLs - to the appropriate pages on Good Thinking)
This is possibly causing problems we are seeing! (legacy URL issues)

**Comment by reddog** [comment]
@ellemindwave See https://github.com/mindwaveventures/cms/issues/513#issuecomment-334467065

The root/naked/apex domain [londonminds.co.uk](https://londonminds.co.uk) has been set to HTTP 301 redirect to https://www.good-thinking.uk, see 

![image](https://user-images.githubusercontent.com/151362/31491573-b1ec68c6-af3f-11e7-9043-a12ff6bfb335.png)

The `www` subdomain of www.londonminds.co.uk has to redirected in code.

@Danwhy has any work been completed to perform HTTP 301 redirects of requests on www.londonminds.co.uk over to www.good-thinking.uk ?

**Comment by Danwhy** [comment]
No, no redirect work has been done on our end. I'll see if I can get it done today

**Comment by Danwhy** [comment]
www.londonminds.co.uk now permanently (301) redirects to good-thinking.uk
