### ISSUE TITLE
Add 'get urgent support' and 'take assessment' into mobile menu

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#623]
Currently they are on the top banner on desktop, but on mobile you can't easily get to them.
This will be very important for stakeholders

**Comment by katbow** [comment]
@ellemindwave where would you like these placed? 

![current-layout](https://user-images.githubusercontent.com/1287388/31505809-abf48c90-af6d-11e7-8844-ce010fe56493.png)

Should it go between "Home" & "I am, or know someone who is, feeling:"? And would you like it as "Take assessment" then "Get urgent support", or vice versa?

**Comment by ellemindwave** [comment]
This is the order it should be: 

Home
Take Self Assessment
Get Urgent Support

_I am or I know someone who is feeling:_
Sleep deprived
Anxious
Stressed
Sad
