### ISSUE TITLE
Headers don't seem to be centred on the images anymore

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#640]
Headers now seem to have more space above them than they used to, and the images at the top of topic homepages appear larger.
Has this been caused by a change to the banners at the top of the pages, or something else?
The headers need to sit in the centre of the images with equal space above and below them

![image uploaded from ios 13](https://user-images.githubusercontent.com/26304634/31544195-9179ced0-b011-11e7-9c5e-815379daa66f.png)
![image uploaded from ios 14](https://user-images.githubusercontent.com/26304634/31544196-9191eb50-b011-11e7-8d20-94c7efc7b051.png)

**Comment by katbow** [comment]
@ellemindwave I noticed this as I was adding the new logo in and making the hamburger menu transparent. It may have been when the nav bar/menu was raised up to fix the gap that was between them previously.

I'll change this to please test once that PR is merged in so you can check if it's better with the changes there.
