### ISSUE TITLE
Once thumbs are selected, cannot change response

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#651]
Once you have 'thumbs upped' or 'thumbs downed' a resource, you are unable to change your response

**Comment by katbow** [comment]
@ellemindwave can you give more detail on this? If I go to the resource list & like a resource, then I can either click thumbs up again and it removes it, or I can click thumbs down and it changes my response to dislike. If I click a response, then leave the site and come back then I am still able to change my response in a particular way.

**Comment by Cleop** [comment]
I've tried to replicate this on iPhone 5C on both chrome and safari and don't seem to have this problem... where is it you experienced it @ellemindwave?

**Comment by ellemindwave** [comment]
Weird! I tried it earlier on iphone 6 chrome, and Sarah was the one that flagged it, but I can't seem to make it happen again - I will check with @sarahwelton

**Comment by sarahwelton** [comment]
I've checked on my Samsung and it seems fine now too. Shall close the issue!
