### ISSUE TITLE
Beta banner is overlapping navbar on desktop, chrome

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#658]
Is this to do with the size of the logo at all? 
The beta banner has become fatter since the logo was added

<img width="510" alt="screen shot 2017-10-16 at 09 53 21" src="https://user-images.githubusercontent.com/26304634/31618480-f82536c2-b289-11e7-8ed6-887dfdea5a0a.png">

**Comment by indiamindwave24** [comment]
![a934ab44-7f94-4380-a8c6-2fba4ce016c8](https://user-images.githubusercontent.com/25007700/31813513-9aa7334a-b57e-11e7-920f-5b4d13d5d457.png)


Macbook

**Comment by indiamindwave24** [comment]
![31e94bb7-81ba-4422-8a42-58954f222fef](https://user-images.githubusercontent.com/25007700/31813611-f934c74c-b57e-11e7-90f5-271c8ba85f6d.png)

Desktop (iMac)

**Comment by katbow** [comment]
@ellemindwave yes it is to do with the logo size. If I made the logo any smaller, then it was pretty squished. I thought I went through all the screen sizes to see that it still worked but I guess I ended up focussing most on mobile fixes!  I don't have iMac unfortunately, but I will fix for mac now and we can test how it is on iMac with those changes.

**Comment by katbow** [comment]
@indiamindwave24 what size macbook is that on? Can't replicate on 13".

**Comment by katbow** [comment]
I am assuming that must be the larger macbook since there is no overlap or gap on my mac. I used a larger monitor to fix it on larger screens, but I don't have those exact screens to replicate it. 

This may require further testing/I may need to be able to use those devices to check the fix does not cause an overlap or gap.

**Comment by ellemindwave** [comment]
@katbow my macbook is 13inch and it is slightly overlapping, needs slightly more padding between the 'I am or know someone who is feeling' and the beta banner

![screen shot 2017-10-20 at 15 52 07](https://user-images.githubusercontent.com/26304634/31827164-0e20ece6-b5af-11e7-81cd-0ba9aedcbd5c.png)

**Comment by katbow** [comment]
@ellemindwave I did notice that part and I fixed it for macbook 13". Sorry that was unclear, I meant it wasn't as large of an overlap as in [this comment](https://github.com/mindwaveventures/cms/issues/658#issuecomment-338150901).

**Comment by ellemindwave** [comment]
@katbow great - no worries. Thanks for explaining.

**Comment by katbow** [comment]
I assigned to all for this one for whoever has the relevant devices. If the fix I did for the screen sizes I had available isn't good for your device I will need to check them out on the device for precisely how I will need to update it for those sizes. Thanks!

**Comment by ellemindwave** [comment]
@katbow closing this issue so that it can be deployed and properly tested on live site, re the issue I showed you with the slight gap between beta bar and nav bar on staging site
