### ISSUE TITLE
Topic cubes now too close together on desktop

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#659]
<img width="1351" alt="screen shot 2017-10-16 at 09 28 16" src="https://user-images.githubusercontent.com/26304634/31618504-0944e880-b28a-11e7-910b-48ca4a717add.png">

**Comment by reddog** [comment]
Are there acceptance criteria for this issue?  What should the gap be (at various screen sizes, etc)?

**Comment by indiamindwave24** [comment]
I think this is a bug as there used to be padding around each box. 

Please make the vertical and horizontal padding around the topic modules the same as the vertical padding below the bottom modules (stressed and sad) and the ‘are we missing something?’ Module. 

Or if the previous padding can be used again that would be ideal as it was perfect before.
