### ISSUE TITLE
Set 'personalise your results' events on interaction

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#662]
set events for the following:

![screen shot 2017-10-16 at 15 57 04](https://user-images.githubusercontent.com/26304634/31618754-b99b8e1e-b28a-11e7-95a8-e0d502b5cbc7.png)

**Comment by ellemindwave** [comment]
@Danwhy from Fresh Egg: 

The 'personaliseResults' event is set twice when clicking just once on 'next question' or 'previous question'. It's fine on the item selections. Also, the event doesn't fire when clicking on 'Search' at the end.

**Comment by Danwhy** [comment]
I'm only seeing one event firing for `next question`:
<img width="796" alt="screen shot 2017-10-20 at 14 54 47" src="https://user-images.githubusercontent.com/8939909/31824365-b35f6ccc-b5a6-11e7-8b65-c4d4364fd815.png">

Search was using the wrong id to trigger, I'll fix that

**Comment by ellemindwave** [comment]
Fresh Egg: 
#662 is now firing one event which is correct. However, it's still not firing the event when I click the 'Search' button.

**Comment by Danwhy** [comment]
The fix for the search button has been deployed now

**Comment by ellemindwave** [comment]
@Danwhy from Fresh Egg:

' I've just tested again and clicks on the 'Search' button are working now. However, it's triggered twice. The same goes for when I click on the 'next question' and 'previous question' links. This should only be once.'

**Comment by ellemindwave** [comment]
FYI @Danwhy - if there are any questions on this, we should contact Fresh Egg's head of insight, julian.erbsloeh@freshegg.com

**Comment by Danwhy** [comment]
I figured out why I wasn't having this problem, the double trigger only occurred after selecting a tag, which I hadn't done. It should be fixed now
