### ISSUE TITLE
Large gap between PYR section and resources on ipad pro landscape

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#664]
(also Javascript error!?)

![image uploaded from ios 27](https://user-images.githubusercontent.com/26304634/31619347-2b7913f2-b28c-11e7-9042-28c61e059661.jpg)

**Comment by katbow** [comment]
@ellemindwave do you know how to disable JavaScript? You'll need to for this one when testing.

**Comment by indiamindwave24** [comment]
Seems to be okay now - although something off with the text below? words overlapping: 'showing 8 resources for'
![img_0162](https://user-images.githubusercontent.com/25007700/31998869-381f56e4-b989-11e7-9b2f-ca31f58c803f.PNG)

**Comment by katbow** [comment]
@indiamindwave24 I tried Chrome & safari for this & couldn't get it to show up like that. Can you let me know browser & steps to reproduce please?

Thanks!

**Comment by indiamindwave24** [comment]
Ipad pro - safari - javascript disabled 

Went from home to anxiety page and scrolled

**Comment by indiamindwave24** [comment]
Yes this is fixed now 👍
