### ISSUE TITLE
Wagtail character count isn't counting correctly

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#665]
There are 199 characters here. 

In this screenshot, Wagtail says there are 211 characters
<img width="908" alt="screen shot 2017-10-16 at 18 52 35" src="https://user-images.githubusercontent.com/26305143/31626915-4e2d4a78-b2a3-11e7-832b-aa75a36465a0.png">

I haven't changed the text and this screenshot, Wagtail says there are 206 characters. 
<img width="918" alt="screen shot 2017-10-16 at 18 53 50" src="https://user-images.githubusercontent.com/26305143/31626954-76accc9e-b2a3-11e7-9bbc-5ff35788b5df.png">

**Comment by Danwhy** [comment]
For some reason, for rich text fields, wagtail includes the html tags as part of the character count:
https://github.com/wagtail/wagtail/issues/2268
So 199 characters plus `<p>` and `</p>` makes 206. I assume in the top screenshot there was an additional empty paragraph. The character limit could be increased by seven to account for this.
