### ISSUE TITLE
Event triggered when submitting 'ResourceFeedback' form

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#667]
Request from Fresh Egg:

When submitting the resource feedback form, the 'ResourceFeedback' event is triggered in the dataLayer. It also sets a variable called 'reviewed', but as you can see in the screenshot below, it's set to 'null' instead of 'Thrive: Feel Stress Free'. Can you ask the devs to update this so the correct value is returned?

![image](https://user-images.githubusercontent.com/26304634/31660133-58e03c42-b32e-11e7-82ef-17b532d86e3c.png)

**Comment by ellemindwave** [comment]
@Danwhy from Fresh Egg:

The 'ResourceFeedback' event is fired when clicking in the textbox not when the form is submitted. The 'reviewed' value is still set to 'null' for both 'ResourceFeedback' and when the form is submitted.

**Comment by Danwhy** [comment]
Strange, it's working for me

<img width="826" alt="screen shot 2017-10-20 at 14 32 38" src="https://user-images.githubusercontent.com/8939909/31823309-a72a5c08-b5a3-11e7-861b-d9ea143889ca.png">
<img width="880" alt="screen shot 2017-10-20 at 14 35 36" src="https://user-images.githubusercontent.com/8939909/31823410-fe93a666-b5a3-11e7-9849-e44f9ead2e20.png">

Could you find out which browser/OS they're using?

**Comment by ellemindwave** [comment]
Stu Bowker [17 hours ago] 
#667 Is working for me too now. Weird!


Stu Bowker [17 hours ago] 
However, the ResourceFeedback event fires twice when I submit the form.
![screen shot 2017-10-24 at 09 16 28](https://user-images.githubusercontent.com/26304634/31931770-27281b20-b89c-11e7-9974-907579934659.png)
