### ISSUE TITLE
Add 'feedback-link' ID to feedback link

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#669]
@U3M6NM542 last thing, for the feedback link can you add the 'feedback-link' ID to the link as it's not there any more < a href="/feedback/">give feedback</a > :disappointed:

So @Stu Bowker the 'feedback-link' ID should be put into the code somewhere? In that case, what should the code look like from your above example? < a href="/feedback/">give feedback</a >

@elle < a href="/feedback/"  id="feedback-link ">give feedback</a >

**Comment by ellemindwave** [comment]
from @reddog : 

The long term, sustainable, solution is to make that text box (and others?) some kind of richer text input so that the raw HTML can be changed.  A workaround would be to put an id on the parent container (which is in the template and that is something Dwyl can change), add jQuery (just to make life easier) and refer to the a-link as a child of it's parent (since we'll have the id of the parent now added).

The XCode can be used to locate the a-link element.  But, hmmmm.... it's not very useful in Internet Explorer:  https://caniuse.com/#search=xpath  

I think the easiest thing would be:  put an id on the parent container (which is in the template and that is something Dwyl can change), add jQuery (just to make life easier) and refer to the a-link as a child of it's parent (since we'll have the id of the parent now added).

**Comment by reddog** [comment]
@Danwhy How will this be achieved?  It doesn't appear possible to edit the HTML from the admin page (note old "feedback" message shown here):

![image](https://user-images.githubusercontent.com/151362/31722466-118c9840-b414-11e7-80d4-1ac7ab6ca423.png)

**Comment by Danwhy** [comment]
@reddog No, the simplest way would be to add it with javascript on page load

**Comment by reddog** [comment]
@Danwhy Thanks for your reply.  Adding an `id` tag with JS on page load doesn't really *feel* like the right sort of solution - it certainly feels like a *fix for now*.

@ellemindwave is a *fix for now* required or something a little more?

@Danwhy Would your suggestion work if the banner message had multiple links in it?  Or none?  Would it be possible to change the `id` of the link using your method?

Would https://github.com/mindwaveventures/cms/issues/685 provide a more flexible solution?

**Comment by ellemindwave** [comment]
@reddog that depends on how much time it would take to achieve something a little more vs the fix for now

**Comment by reddog** [comment]
@ellemindwave In that case do we need a time estimate from @Danwhy on https://github.com/mindwaveventures/cms/issues/685 ?
