### ISSUE TITLE
Change all ''>" to "submit" on buttons

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/cms#670]
Change '>' to 'submit'

<img width="1915" alt="screen shot 2017-10-17 at 2 40 46 pm" src="https://user-images.githubusercontent.com/25007700/31668098-3180f39c-b349-11e7-8995-d8198b63ff30.png">

**Comment by Cleop** [comment]
@indiamindwave24 - is that in the same style so to look like this:
![image](https://user-images.githubusercontent.com/16775804/31724007-6c69d300-b418-11e7-8d40-ceaa4f27f5e7.png)
Or is it the same style as an existing button type e.g. primary / secondary buttons?

**Comment by indiamindwave24** [comment]
The same styles as the ‘get support to manage your anxiety’ button :)

**Comment by katbow** [comment]
@indiamindwave24 this is how it looks on mobile. Would you like to keep it this way, or move the submit button underneath & centred?

![image](https://user-images.githubusercontent.com/1287388/31885543-ca5e66fa-b7e8-11e7-867a-7866d6c3d1e8.png)

**Comment by katbow** [comment]
Also @indiamindwave24 I have styled it on desktop to look like this. Is this what you were imagining?

![image](https://user-images.githubusercontent.com/1287388/31885896-09e7c63a-b7ea-11e7-91af-3e1ca6f56e81.png)

**Comment by indiamindwave24** [comment]
Yes, thats great :)

**Comment by indiamindwave24** [comment]
on mobile, can it please sit below?
