### ISSUE TITLE
Thumbs up/thumbs down not aligned

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#671]
The thumbs up and down are out of alignment on iPad safari landscape

![image uploaded from ios 28](https://user-images.githubusercontent.com/26304634/31670569-ced80738-b34f-11e7-8c54-0ea895cfd050.jpg)

**Comment by katbow** [comment]
Also occurs on safari for iPhone 5.

**Comment by katbow** [comment]
@ellemindwave I fixed this in the list page but didn't realise it's also occurring on the individual resource. Can you still check out the resource list in safari and let me know if that looks good? I'll apply the same fix to the individual resources if so.

**Comment by ellemindwave** [comment]
The resource thumbs up/thumbs down don't align perfectly on Safari iphone 6 either:

![image uploaded from ios 16](https://user-images.githubusercontent.com/26304634/31951627-910d845a-b8d6-11e7-9cf3-ebf03848102a.png)

**Comment by katbow** [comment]
yeah that's what I was saying lol. For all devices I didn't see it was on the individual resource as well. I thought it was only the list. Can you verify the resource **list** now looks how it should so I can apply the fix to the individual as well @ellemindwave ?
