### ISSUE TITLE
Update robots.txt file

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#673]
Robots.txt file needs updating – ensure line break is in place (Google reads this fine, but belt & braces), add query string parameters where necessary (TBC)

**Comment by ellemindwave** [comment]
From Fresh Egg - further clarification @Danwhy 

The personalisation questions create quite lengthy query strings on the URLs:
https://www.good-thinking.uk/anxious/?q1=can%27t%20leave%20the%20house&q1=can%27t%20switch%20off&q2=sometimes&q3=with%20a%20professional

There's obviously many different combinations. I _think_ Google won't be able to access these through crawling the site - the 'next question' CTA is an anchor link but all the different options are <button> elements. Nothing currently shows in the URL parameters report in Search Console, so I don't think they've found any of them yet at least.

However, if people start sharing and linking to these extended URLs it may lead to some of these being indexed - so keeping an eye on the URL parameters report would be a good idea so that they can see if Google starts finding them. Another option would be to use rel=canonical on these pages, but there's a chance Google may ignore that if it can see the content is different (which it would because the results are filtered based on the query string parameters.

That 'TBC' was written by Mark (SEO team here) and he wrote it in to remind himself to give the explanation above

So we can keep a 'watching brief' on which URLs get noticed by Google and add them to the robots.txt file as they appear

Both the sitemap.xml and robots.txt file are dynamic files - in that we expect to keep modifying them to direct Google to pages to visit and index (sitemap.xml) and pages to ignore (robots.txt)

**Comment by reddog** [comment]
Useful feedback @ellemindwave.  Does this mean that there are effectively two **new** issues that are required:

1.  add ability to edit the `sitemap.xml` file from within the admin panel *somehow*
2.  add ability to end the `robots.txt` file from within the admin panel *somehow*

I believe these are both fully auto-generated at the moment.  Would that be right @Danwhy?

When exploring these new issues fully, we could then check if there is already some method of white-listing/black-listing links or if something new needs to be built for this.

**Comment by Danwhy** [comment]
@reddog The sitemap is auto generated by wagtail, the robots.txt was manually created by us. Editing the robots.txt through the admin would probably be reasonably simple, the sitemap not so much, as we'd have work out a way to extend what is generated by wagtail.

**Comment by ellemindwave** [comment]
More info from FE:

'Some of those 'personalisation question queries' we will want Google to index over time.. and we will also want to create friendly URLs for important combinations. We will find out which combinations as people start using the service from GA page visit stats. Once we have that data, we can make sure Google knows about those pages in the sitemap.xml (even if the URL is packed full of parameters, we can still add it), so that the key pages are at least indexed and searchable directly from Google.'

**Comment by reddog** [comment]
@ellemindwave Could these "friendly URLs for personalisation question queries" be achieved with https://github.com/mindwaveventures/cms/issues/677#issuecomment-337564653 ?

![image](https://user-images.githubusercontent.com/151362/31773979-537a0436-b4dc-11e7-9e8f-20d9a8725cb2.png)

Worth trying?

**Comment by ellemindwave** [comment]
Hi @Danwhy - have checked with Fresh Egg on this, and yes please, we would like the robots.txt file to be editable in the CMS. 
As we discussed this morning, I think you mentioned that this would have a time estimate of 2-3 hours?

**Comment by Danwhy** [comment]
It looks like the simplest way to implement this would be to upload a txt file to the documents section of wagtail, that we could then serve as the robots.txt. Then anybody from Fresh Egg or Mindwave with access to the cms would be able to change the file at any time.

This would also avoid any complications with formatting that could arise from pulling the robots.txt through from a wagtail field.

@ellmindwave Does that sound like an ok solution?

**Comment by ellemindwave** [comment]
@Danwhy for some reason I can see the following comment from you in my email notification but it's not here on the issue itself..! Sounds good to me, though. Thanks

'It looks like the simplest way to implement this would be to upload a txt file to the documents section of wagtail, that we could then serve as the robots.txt. Then anybody from Fresh Egg or Mindwave with access to the cms would be able to change the file at any time.

This would also avoid any complications with formatting that could arise from pulling the robots.txt through from a wagtail field.

@ellmindwave Does that sound like an ok solution?'

**Comment by Danwhy** [comment]
The robots.txt file is now served from wagtails documents: https://www.good-thinking.uk/admin/documents/
This file can be now be changed whenever, as long as it remains a txt file called `robots.txt`
