### ISSUE TITLE
Ensure plain text URLs can't be picked up by search engines

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#674]
Crawling tools picked up /get_json_data/ URLs which return plain text (see https://www.good-thinking.uk/get_json_data/?&order=relevance&q=&slug=anxious&page=initial). 

Set a rule Disallow: /get_json_data/ * to ensure these URLs cannot be picked up by search engines.

**Comment by ellemindwave** [comment]
From Fresh Egg:
The Robots.txt file is missing
Robots.txt (#674)
Currently returns ‘page not found’ on the live site – once reinstated we can reassess.

If the team can reapply the robots.txt file, we can test it.

**Comment by Danwhy** [comment]
https://github.com/mindwaveventures/cms/issues/673#issuecomment-339302150
@ellemindwave it should be working now, and editable too
