### ISSUE TITLE
Friendly URLs for segmented resources

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#676]
Friendly URLs for segmented resources (e.g. https://www.good-thinking.uk/sleep-deprived/insomnia/) are present but are not included in the sitemap and have not been linked to at any point. This prevents people and search engines from finding these useful pages

a.     This structure allows any URL to return a 200 page, e.g. https://www.good-thinking.uk/sleep-deprived/sausages/

b.     Other pages that appear valid have no results, e.g. https://www.good-thinking.uk/anxious/ocd/

c.     None of these URLs have optimised page titles or meta descriptions, which are simply duplicates of the parent URL

**Comment by reddog** [comment]
@ellemindwave This looks like several issues in one which could be confirmed by @Danwhy's `T1d` time estimate.  Can it please be broken in to multiple issues to ensure that we're all clear on what the issues are and what the acceptance criteria for each issue is?

**Comment by ellemindwave** [comment]
@Danwhy @reddog Would the separate issues for this be:

1. Add friendly URLs to sitemap and link to them
2. Make sure no pages return at 200 error message (some URLs which seem valid produce no results)
3. Optimise friendly URLs' page titles and meta descriptions, which are currently just duplicates of the parent URL

**Comment by Danwhy** [comment]
:+1: For part 2, pages that have no results should actually return a 404, and I'll need to make sure the tag names are not case sensitive (OCD working vs ocd not working)

**Comment by ellemindwave** [comment]
Closing this issue as it has now been broken down into: 

#711 
#712 
#713
