### ISSUE TITLE
Internal redirects

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#678]
Internal redirects - too many internal links miss out the trailing '/' on the URL causing a redirect. These links need to be updated.

**Comment by reddog** [comment]
@ellemindwave Is this two issues in one?  Can they be separated out if they are?

**Comment by ellemindwave** [comment]
Have separated them out 👍

**Comment by ellemindwave** [comment]
Self-assessment links on the mobile navigation still need updating:
![image](https://user-images.githubusercontent.com/26304634/31995877-22f0abd4-b97e-11e7-9acb-bb0a80639fed.png)

Also the ‘cookies policy’ links here – less important, but good to update for completeness:

![image](https://user-images.githubusercontent.com/26304634/31995914-450a7150-b97e-11e7-8904-67c6151eb1e0.png)

Internal links to /crisis/ now also need updating due to URL change – these should point to /urgent-support/:

![image](https://user-images.githubusercontent.com/26304634/31995944-65471ae0-b97e-11e7-8b61-485dc9af47be.png)

**Comment by ellemindwave** [comment]
Fresh Egg:
We can see it goes to the right page and the redirect is OK as a catch all, but best practice is to have the internal linking correct, so the button points straight to the correct page without the redirect.  This increases performance and reduces server load.

**Comment by Danwhy** [comment]
The banner button text and links can now be changed from wagtail, so the correct page can now be linked directly (which I've already done for the crisis page) : https://www.good-thinking.uk/admin/pages/153/edit/

**Comment by ellemindwave** [comment]
the desktop link is now correct, but the mobile link on the Get Urgent Support button is still a redirect from /crisis
