### ISSUE TITLE
Accessing the site via  https://good-thinking.uk error

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#681]
Accessing the site via https://good-thinking.uk/ (HTTPS but non-www) appears to throw an error. This should redirect as the other variants correctly do

**Comment by reddog** [comment]
This is a problem with HTTPS redirection, see https://uk.godaddy.com/community/Managing-Domains/Forwarding-from-HTTPS/td-p/55176#U55735

**Comment by reddog** [comment]
@Danwhy Could this be achieved by adding `good-thinking.uk` (no leading `www`) to the `RedirectFromLMMiddleware` method at https://github.com/mindwaveventures/cms/blob/55c8f8998f588b7cd9636f333d72f03f408bd1b6/cms/middleware.py#L15 ?

If so I can then make the DNS change to point the apex `good-thinking.uk` A record to the Heroku hosting.

Also, should the plain `londonminds.co.uk` (no leading `www`) be added also?

**Comment by Danwhy** [comment]
@reddog I'm not sure if this would work, as I don't think the request to `https://good-thinking.uk` is reaching us at all, and so wouldn't trigger the middleware to redirect.

**Comment by reddog** [comment]
@Danwhy It's not, not at the moment.  If you are able to make the change listed in https://github.com/mindwaveventures/cms/issues/681#issuecomment-337611198 then I can alter DNS so that `https://good-thinking.uk` does get to this site.  Would that work?

**Comment by Danwhy** [comment]
@reddog Ok that makes sense. So I would add a list to check the host containing `['www.londonminds.co.uk', 'londonminds.co.uk', 'good-thinking.uk']`, right?

**Comment by reddog** [comment]
@Danwhy I think that's what we need to try.

**Comment by Danwhy** [comment]
@reddog I've added the host list, and this has been deployed, so you can try changing the DNS now

**Comment by reddog** [comment]
@Danwhy We/you/anyone should be able to test this in advance of making the DNS change (which will effect everyone, whether it works or not) by adding an entry in the local `.hosts` file.  Are you able to give this a go to test this fix has worked?

**Comment by Danwhy** [comment]
@reddog what would I need to add to my hosts file to test this locally?

**Comment by reddog** [comment]
@Danwhy There are instructions for editing a `hosts` file on a Mac here:  https://www.imore.com/how-edit-your-macs-hosts-file-and-why-you-would-want

Add an entry for `good-thinking.uk` to resolve to any IP address that `www.good-thinking.uk` currently goes to:

```
C:\Users\dave>nslookup
Default Server:  google-public-dns-a.google.com
Address:  8.8.8.8

> www.good-thinking.uk
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    www.good-thinking.uk.herokudns.com
Addresses:  46.137.94.167
          46.137.79.23
          54.228.216.104
          46.137.174.111
          46.137.118.177
          46.137.160.82
          54.228.245.152
          54.247.109.213
Aliases:  www.good-thinking.uk
```

So the entry in your local `hosts` file would look like:

```
46.137.94.167   good-thinking.uk
```

And then visit http://good-thinking.uk and https://good-thinking.uk in your browser (probably with the Chrome developer console open in order to turn off cache - otherwise cached DNS queries might linger around).

**Comment by Danwhy** [comment]
@reddog Thanks, I've done that and both links seem to be working fine
