### ISSUE TITLE
Thumbs up and thumbs down are pixelated

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#683]
<img width="134" alt="screen shot 2017-10-17 at 3 07 30 pm" src="https://user-images.githubusercontent.com/26304634/31673321-da047b26-b356-11e7-94f0-c28a4aea33da.png">

**Comment by Cleop** [comment]
@ellemindwave - I seem to recall that @Danwhy was aware the asset looked like this when he received it from @indiamindwave24. Could you get @indiamindwave24 to provide another one?

**Comment by indiamindwave24** [comment]
Is it better provided as an svg?

**Comment by ellemindwave** [comment]
@indiamindwave24 yes please, can you provide it as an svg?

**Comment by indiamindwave24** [comment]
let me know if anything needs changed on this
[Thumbs up:down.zip](https://github.com/mindwaveventures/cms/files/1414317/Thumbs.up.down.zip)
