### ISSUE TITLE
Reviewing & Implementing performance changes

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#686]
More from @reddog soon on this

**Comment by reddog** [comment]
A round of database query refactoring was completed in https://github.com/mindwaveventures/cms/issues/516#issuecomment-335133404 by @Danwhy which looks like it will certainly lead to a better situation in terms of scaling numbers of resources on the site.

From a very initial inspection there seem to be a number of possible areas to move on to (in no particular order):

- template caching
- database caching
- further database query refactoring (other page types, further work on resources page, etc)
- larger scale refactoring - using a more *API* type structure with the less changing page elements separated out from the more changing elements (eg on resource page, the thumbs up/down may change a lot more frequently from the rest of the page content).

Anticipated benefits of further performance-related work:
1. faster page load times for users
2. lower server load (leading to cheaper infrastructure costs)
3. greater flexibility in infrastructure options (eg caching layer, memcached, etc)

I don't yet know:
1. how much *spare* time there is in this sprint
2. what priority is to be associated to performance issues - the site *works* as it is and performance issues can, to some degree, be *fixed* by greater infrastructure costs - this is not a scalable solution.

At this stage it would be great to have a conversation with @Danwhy about what he sees as the next area that would give the best performance boost and how long it would take to implement.

**Comment by ellemindwave** [comment]
@reddog in answer to your 'I don't yet know' comments:

- There could be time for this in this sprint - it is important and therefore we would like to know more on how long some of the above tasks might take so that we can see what could be done in this sprint. 
- It is important, after bugs and the tweaks that are in sprint already, this is likely to be prioritised as we need the site to be performing at its best  

It would be great to get some more information on which area to start with to gain most impact on the site performance, and how long you see the various tasks above taking. 
Thanks

**Comment by reddog** [comment]
@ellemindwave I think what I'd like to do as a next step is to

> have a conversation with @Danwhy about what he sees as the next area that would give the best performance boost and how long it would take to implement.

Maybe I could do that next week?

**Comment by Danwhy** [comment]
Current plan is to implement some refactoring for the templates that reduces the load time.
Template profiler:
<img width="1061" alt="screen shot 2017-10-24 at 13 37 07" src="https://user-images.githubusercontent.com/8939909/31943396-8391065a-b8c0-11e7-8639-71686a235595.png">

**Comment by reddog** [comment]
@Danwhy Would be interesting to see a template load waterfall *post-improvements*.  It would give a clear insight in to what the improvements actually mean.  Would you be able to add that?

**Comment by Danwhy** [comment]
<img width="1069" alt="screen shot 2017-10-24 at 16 30 22" src="https://user-images.githubusercontent.com/8939909/32043897-ecd412dc-ba33-11e7-9958-7436a20c596a.png">
It looks like we've managed to reduce the time by about 50%. Still more that could be done, but definitely an improvement.
