### ISSUE TITLE
JS error when clicking Search in PYR bar on a resource

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#692]
To reproduce:

1.  go to https://www.good-thinking.uk/anxious/
2.  click on the `next question` button in the PYR section to move to question 2, and again to move to question 3
3.  click on `Search` in the question 3 box.  A JS error will be thrown as shown below.  No further functionality requiring JavaScript will function until the page has been reloaded (eg clicking `previous question` in the PYR section, choosing `order by` above the results, etc.)

```
Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided.
    at Array.<anonymous> (scripts.js:4)
    at Function.r [as func] (scripts.js:2)
    at l (scripts.js:1)
    at r (scripts.js:2)
    at Object.callback (scripts.js:2)
    at d (scripts.js:2)
    at v (scripts.js:2)
```

Browser Chrome on Windows

![image](https://user-images.githubusercontent.com/151362/31767856-ade88cac-b4c4-11e7-8ee7-fd99dc598301.png)

Could be related to https://github.com/mindwaveventures/cms/issues/415 ?

**Comment by katbow** [comment]
Hey @reddog I tried this in chrome on my computer (Version 61.0.3163.100 (Official Build) (64-bit)), had a few people on other machines try and tried on saucelabs with windows/chrome and couldn't replicate this. What is your version of chrome?

**Comment by reddog** [comment]
@katbow I tested on Chrome on Windows.  Version 60.0.3112.101.  This is not the most current version.

It looks like the `window.scrollTo` call at https://github.com/mindwaveventures/cms/blob/16e60938132b5f25e5cc61b2dcee8222c17a2a79/cms/static/js/personalise.js#L114-L118 is using a *new* method signature.  What the test Chrome I'm using is picking up is the *regular* `scrollTo` method, see https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo where the syntax is:

```
window.scrollTo(x-coord, y-coord)
```

Although it's been around for a little while, it looks like there might be limited support for scroll `behaviour`, see https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

![image](https://user-images.githubusercontent.com/151362/31832988-fdc26da4-b5c0-11e7-833b-0f2128622310.png)

![image](https://user-images.githubusercontent.com/151362/31832999-06f6816c-b5c1-11e7-91dc-a2b096ee816d.png)

There is a fallback implementation at https://hospodarets.com/native_smooth_scrolling which uses jQuery as one fallback method.

I listed a jQuery example at https://github.com/mindwaveventures/cms/issues/415#issuecomment-333079027  One benefit of a jQuery implementation might be that *someone else/others* have already done the heavy lifting in terms of various mobile/desktop browser support.

**Comment by katbow** [comment]
Yes I saw the jquery implementation, but I was going with native JS due to the discussion on #684. We hadn't used jQuery for anything else up until that point and it would be a lot to add for only smooth scroll. 

Does this also occur on the homepage for you? I realised that I used `window.scroll` on the home page chevron and `window.scrollTo` on the search button. 

If there are no problems on the home page I can change this to also use `window.scroll`.

**Comment by reddog** [comment]
@katbow Thanks for that.

I'm not sure what you mean by "a lot to add" - could you clarify this?

Would it be worth estimating how long it would take to implement the jQuery solution and then see if it's worth giving it a go?

On my Android mobile I don't have a JS error but I also don't have smooth scrolling - the page just jumps to the results section.

Yes, I get a similar error on the homepage:

![image](https://user-images.githubusercontent.com/151362/31899965-f0d03274-b814-11e7-8281-2b299b6fd3ab.png)

```
Uncaught TypeError: Failed to execute 'scroll' on 'Window': No function was found that matched the signature provided.
    at scrollToElement (smooth_scroll.js:8)
    at HTMLAnchorElement.<anonymous> (smooth_scroll.js:17)
```

**Comment by katbow** [comment]
> I'm not sure what you mean by "a lot to add" - could you clarify this?

I mean that adding a library that is ~ 90kb seems excessive for one piece of functionality. Because there have been previous issues regarding the performance of the site, I think we need to consider the cost/benefit before adding it in.

**Comment by reddog** [comment]
@katbow I can't locally test this now (Chrome has self-upgraded).  However I can see that the jQuery function has been added and the scroll effect is now visible when testing on an Android phone.
