### ISSUE TITLE
Update OG/Twitter cards to include trailing

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#695]
OG/Twitter card tags also need the URLs updating to include the trailing ‘/’

relates to #678

**Comment by ellemindwave** [comment]
From Fresh Egg:
Unfortunately these are still not correct – all pages need changing to include ‘www’ and some pages reference the homepage. Please see the attached spreadsheet – the address and og:url columns should match, I’ve highlighted those that don’t.
[custom_extraction-og-tags.xlsx](https://github.com/mindwaveventures/cms/files/1414352/custom_extraction-og-tags.xlsx)

**Comment by reddog** [comment]
@ellemindwave From the spreadsheet it would look like *this* issue has been resolved - all the `og:url` values now have a trailing `/`.

It looks like there are two new issues with the OG/Twitter cards:

1.  all `og:url` values should include `www` in the URL.

2.  some `og:url` values are showing as the homepage URL and not the URL for the page displayed.  These all currently look like self assessment links.

@Danwhy with regard to adding the `www` to the URL, could https://github.com/mindwaveventures/cms/blob/cf68921b751d45cc2d4795b315c2db0863efb482/cms/templates/base.html#L41 be changed to use `BASE_URL` as defined at https://github.com/mindwaveventures/cms/blob/149bc057384abc4c040c189dfdfce807ca64d86b/cms/settings/base.py#L200 ?  This would mean that the URL is not duplicated across the codebase and would require changing in only one place (or fewer places if it's still elsewhere) if it should change again.

**Comment by reddog** [comment]
@katbow Is it not possible and/or useful to use the `BASE_URL` setting here?  See https://github.com/mindwaveventures/cms/issues/695#issuecomment-339299529
