### ISSUE TITLE
Tags overlapping on text - Q1 stress

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/cms#701]
iPad Pro portrait Safari

Samsung galaxy A5 Chrome

This does not appear to happen on iPhone 6 safari

![68015686-8971-40fd-b8f8-37af91ecd87f](https://user-images.githubusercontent.com/25007700/31812767-fe68e3d6-b57b-11e7-9c13-13140518b71b.png)

**Comment by indiamindwave24** [comment]
![cb32d9bc-2455-4253-84f9-a9af54ee365c](https://user-images.githubusercontent.com/25007700/31813088-0efc9ec6-b57d-11e7-8418-52c14cf5fc5e.png)

**Comment by katbow** [comment]
Note for myself. This is happening because the tallest tag height and tallest text height are on different cards. For some reason, the JS is grabbing the height for the text height from the card with the tallest tag height. 

Looking at how to ensure the test height is grabbed from the correct card, and not influenced if the tallest tag height is on a different card.

**Comment by reddog** [comment]
@katbow Just to check, is styling being done in JS?  Is the solution not wholly CSS?  Are there reasons for this?

**Comment by katbow** [comment]
Ah @indiamindwave24 I see what this is. When you are switching between devices on the browser, the javascript is not called again which is what determines the height. So when you switch to a different device, the height is determined already which causes it to overlap. This is not something that would happen when loading the page on the actual device, as you aren't switching between different device screen sizes.

You can verify this by going to a device, and if it looks overlapped, refresh the page. It will show the correct styling.

**Comment by katbow** [comment]
@reddog it's in JS. It's because the height of all cards needed to be the same, so it is determined by the tallest height of the tags and the tallest height of the text, then this is applied to all cards for the PYR section.

**Comment by reddog** [comment]
@katbow Thanks for that.  Do you know if any any wholly-CSS solutions tested?

**Comment by indiamindwave24** [comment]
@katbow this was not testing devices through the browser, this was on the actual devices.

**Comment by katbow** [comment]
@reddog No, because it needs to be done dynamically. It will differ for each of the topics.

@indiamindwave24 okay thanks. We just checked on @Danwhy 's phone and can see it, so will take a look at fixing it on there & will need to test if fixing that fixes the other devices.

**Comment by reddog** [comment]
@katbow Does this basically boil down to a *equal height columns* issue?  If so, this is a common CSS problem with a number of great articles online, including https://css-tricks.com/fluid-width-equal-height-columns/

Would something like that provide a wholly CSS based solution?  If so, equal height boxes when the screen width is wide enough, and stacked boxes with no extra spacing (see https://github.com/mindwaveventures/cms/issues/704 ) for narrower screens could be completed is CSS alone.

**Comment by indiamindwave24** [comment]
Yes this is all working well now 👍
