### ISSUE TITLE
URL running off page on individual resources

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/cms#703]
URL is running off the page on some individual resource pages

iPhone 5, safari, individual resource pages

![bd80178e-ce30-4f39-99b8-5d584a500373](https://user-images.githubusercontent.com/25007700/31813156-4f33d842-b57d-11e7-84d6-5c40ed8d0b3c.png)

iPhone 5 safari

**Comment by katbow** [comment]
Here's a resource I made with a very long url:

https://ldmw-staging.herokuapp.com/resources/long-url-test-sleep/
