### ISSUE TITLE
Thumbs misaligned on iPhone 5

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/cms#705]
![78fda577-8ad5-4992-9fd5-9c10ffa90a95](https://user-images.githubusercontent.com/25007700/31813258-a08d8fee-b57d-11e7-8b2a-fcccd87f6bea.png)

**Comment by katbow** [comment]
@indiamindwave24 I'm going to combine this with #671 as it's a similar issue. This is something that appears to be happening on safari only from what I can see. Can you confirm if this happens or not on chrome?
