### ISSUE TITLE
Reduce homepage text size on iPhone 5 and smaller 

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/cms#706]
Reduce by 10pt font size (eg 30px to 20px) 

![f3e20265-eaf0-44b9-ba59-e63d55952722](https://user-images.githubusercontent.com/25007700/31813370-fa05b538-b57d-11e7-93ff-390a20562d71.jpeg)

**Comment by indiamindwave24** [comment]
![img_8640](https://user-images.githubusercontent.com/25007700/31996684-482f9eca-b981-11e7-9254-15094fff01f3.PNG)


V confused with this: iphone 5 on safari

- Burger bar is oddly floating again
- Burger bar is overlapping text

**Comment by ellemindwave** [comment]
@indiamindwave24 re the last point - the staging site is not the same imagery as the live site. We could have updated it all as we went along but that would have taken time that was better spent elsewhere with regards to images etc.

**Comment by ellemindwave** [comment]
@katbow @indiamindwave24 I think this maybe has something to do with the staging site being a bit weird sometimes and not the same as live - it has done this a number of times. 
Maybe best to deploy this and then see how it looks on the live site?

**Comment by katbow** [comment]
I got hold of an iphone5 to check this out myself, and I am only seeing it happen on the home page. Is this your experience as well @indiamindwave24 ? I'm a bit confused as well, as it's another one that's not occurring in the browser and only on the device. I will see if there's any difference in how the CSS we're using for this portion is interpreted on safari vs. chrome, and if there is anything being used that generally doesn't behave nicely on iPhone 5.

**Comment by katbow** [comment]
I had a look at the changes in this section since the issue was first made, and the only changes I'm seeing are:

* vertical padding on the beta-banner is increased from `1rem` to `1.25rem` for portrait mobile screens.
* top margin on the hero image text is `4rem` for the home page only. 
I think it is likely something with the `margin-top: 4rem;` as this sometimes displays differently on iphone.

**Comment by katbow** [comment]
found the problem @indiamindwave24 , just needs to be merged in!

**Comment by indiamindwave24** [comment]
![img_8641](https://user-images.githubusercontent.com/25007700/32008409-1071b40a-b9a4-11e7-82c9-7411f7dc8779.PNG)

The burger bar is still overlapping -- when you scroll down and back up again it doesn't but this is how it appears naturally
