### ISSUE TITLE
All buttons on site to have same double transition

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#708]
The way the buttons in the top beta banner double transition is the way that all the buttons on the site should work.

Roll over the Take Self-assessment button for example.  The button changes to be filled-in blue, and then the text changes to white. 

This is not the case for:

1.  the cookie policy "accept & close" button
2.  the "order by" dropdown above the results

Please can this be made the same on the above buttons

**Comment by katbow** [comment]
Placing an example of each here to compare the difference between the 2.

Self assessment button:
```
<a href="/self-assessment/" class="f6 f7-m link dib ph3 pv2 br1 pointer nunito tracked inner-shadow-active lm-bg-white lm-bg-dark-turquoise-hover lm-dark-turquoise lm-white-hover ba b--lm-dark-turquoise" id="assessment">Take self-assessment</a>
```

Cookies accept & close:
```
<button class="f5 dib ph3 pv2 br1 pointer montserrat tracked inner-shadow-active lm-white lm-bg-dark-turquoise lm-bg-white-hover lm-dark-turquoise-hover mv3 b--lm-dark-turquoise ba word-normal">Accept and close</button>
```

**Comment by katbow** [comment]
The only ones that this affects are non-`<a>` tags. The a tags all have the `link` class which includes a transition. I'll add this on to the other buttons mentioned.
