### ISSUE TITLE
Resources order is not working correctly

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#716]
Yoga with Ariane is 2nd in the list, even though it is tagged with 'free' in the CMS.

Ordering is not correct as Yoga is free and meets all the tag requirements but is below a paid resource - Anxiety page, MacBook, Chrome

<img width="1030" alt="screen shot 2017-10-23 at 14 06 42" src="https://user-images.githubusercontent.com/26304634/31896408-99be952e-b80b-11e7-9eb4-dc5ba0be2f70.png">

**Comment by Danwhy** [comment]
@ellemindwave Could you add the link to the page so I can see all the tags you've selected?

**Comment by ellemindwave** [comment]
Here is another example that @sarahwelton has spotted: 

Surely Meditation Studio that is only missing 3 tags should be higher than Headspace which is missing 5?

<img width="1076" alt="screen shot 2017-10-24 at 10 01 34" src="https://user-images.githubusercontent.com/26304634/31934305-a010d066-b8a3-11e7-9d5d-483e5a216941.png">

<img width="1090" alt="screen shot 2017-10-24 at 10 01 43" src="https://user-images.githubusercontent.com/26304634/31934318-a6a8bd9e-b8a3-11e7-9b13-04822b2e34ae.png">

<img width="1033" alt="screen shot 2017-10-24 at 10 01 48" src="https://user-images.githubusercontent.com/26304634/31934326-adfa987e-b8a3-11e7-9070-e96d72dd8755.png">

<img width="1065" alt="screen shot 2017-10-24 at 10 01 54" src="https://user-images.githubusercontent.com/26304634/31934331-b3e09ea0-b8a3-11e7-9f55-969afec669e6.png">
