### ISSUE TITLE
Tidy up intro copy on resources on listings page 

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#731]
Only the bold text should appear on this page (do we need to have two separate fields as we do with the topic intros?)

Remove the "continue reading" link (the button to get more info plus the header link should suffice) 

<img width="1032" alt="screen shot 2017-10-25 at 10 48 35" src="https://user-images.githubusercontent.com/26305143/31992436-3c740df0-b972-11e7-8838-77e7c8ec43bf.png">

**Comment by katbow** [comment]
Added a separate tagline & body [here on the sleep genius resource](https://ldmw-staging.herokuapp.com/trouble-sleeping/). It shows the tagline only in the list and both the tagline & body on the full resource.
