### ISSUE TITLE
Add button to go straight to the resource provider

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#732]
Underneath the "Get more info and read comments" button (on all resources on listings page), add an identical button with the copy "Go to resource site" - with the external link to the resource provider opening in a new tab.

**Comment by ellemindwave** [comment]
@katbow The thin grey lines that separate the sections seem more pronounced now and the resource cards are sparser - is this something to do with issue #731 ? Do we now need to go through and put all the bold text into its relevant field?

![image uploaded from ios 17](https://user-images.githubusercontent.com/26304634/32006766-87b47818-b99f-11e7-83df-04b27994b2c2.png)

**Comment by katbow** [comment]
@ellemindwave yep that's to do with #731. I added the new field to one resource for now for checking it out, but the others that do not have it will be more sparse. For the live site, the body will need to be split into the tag line (bold text that will display in the resource list) and the body (additional information about the resource that will display with the tagline on the full resource.
