### ISSUE TITLE
Submit button on iMac needs more vertical padding

### ISSUE THREAD

**Issue by Cleop** [LDMW/cms#749]
![image](https://user-images.githubusercontent.com/16775804/32051092-38f48cf2-ba4b-11e7-85fa-844b0dd2f2b2.png)
Submit button on iMac needs more vertical padding to look more similar to 13' display:
![image](https://user-images.githubusercontent.com/16775804/32051116-52364b06-ba4b-11e7-887d-d651060abea6.png)

**Comment by katbow** [comment]
@indiamindwave24 @ellemindwave this seems to have been caused by the accidental font size change as described in #663 .

**Comment by indiamindwave24** [comment]
Yes 'submit' button now fine but rest of text is tiny..?
<img width="2560" alt="screen shot 2017-10-26 at 3 30 18 pm" src="https://user-images.githubusercontent.com/25007700/32058969-9d517edc-ba62-11e7-9c3f-af0290370a7e.png">

**Comment by ellemindwave** [comment]
submit button and whole bar should be same height as all the other buttons above them
