### ISSUE TITLE
Emphasis on getting the app to a state where we can show something

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#75]
From the call yesterday with @reddog there was an emphasis made on getting the app deployed and to a state where MW can use it.

It was said that google analytics and testing should come as a high priority only after the current changes which have been worked on have been deployed.

@reddog Can you confirm that this is the current plan until the review on Wednesday.

**Comment by reddog** [comment]
@shouston3 Sorry for not replying sooner - I think, generally yes - anything that we can get out there for more eyes to get on it the sooner we can provide feedback.  This period of user testing might then leave space for the more *behind the scenes* stuff like GA, test code, etc.
