### ISSUE TITLE
Words shouldn't break over two lines on self asssessment

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#757]
iphone 5 safari

![image uploaded from ios 18](https://user-images.githubusercontent.com/26304634/32449533-b8d93b90-c309-11e7-9403-e109b7b92e15.png)

**Comment by Danwhy** [comment]
@ellemindwave The screenshot in this issue is the feedback page, is this happening on the self assessment page too?

**Comment by ellemindwave** [comment]
@Danwhy apologies, I don't know why I wrote self-assessment! 

This is the feedback page, you're correct.
I have not seen it happening on the self-assessment
