### ISSUE TITLE
E24 - span text not working

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#767]
Span text not working

The span text includes a class declaration of e24subtext which has the following style applied to it.
 
.e24subtext {
  font-size: 12px !important;
  font-style: italic;
}
 
This is probably something you should mirror on your front end.
 
Below is a screenshot.
 
PS. I know it’s not the best idea to have markup in the content, but this is where we are currently, and the builders required the ability to add or diminish emphasis and this is how we do it.
 
How it currently appears:
<span class="e24subtext">If unsure, choose 'Other or none'.</span>
![screen shot 2017-11-08 at 12 35 06](https://user-images.githubusercontent.com/26304634/32549422-4935e580-c481-11e7-870e-e677fef2293d.png)

How it should appear:
![screen shot 2017-11-13 at 17 50 04](https://user-images.githubusercontent.com/26304634/32740510-1ce80328-c89b-11e7-972e-15078e16636e.png)

**Comment by iteles** [comment]
@ellemindwave Could you please add a little more to this requirement? We're not entirely sure we understand what the issue is 😊

**Comment by ellemindwave** [comment]
@iteles I have requested more detail about this issue from E24

**Comment by ellemindwave** [comment]
See updated info above ^^
