### ISSUE TITLE
E24 - Bulleted list is bolded

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#768]
[Does he/Do you] have periods {012-121yof a week or more} when [he has/you have] any of the following? 
<span class="e24subtext">(Must be markedly different from [his/your] behaviour during periods before and after):
{lbextreme hyperactivity or destructive rages|
significantly reduced need for sleep (may get only a couple of hours a night) or a sense of feeling wired|
easily distracted |
more talkative than usual {004-008yor overly silly or elated behaviour}|
extreme sense of wellbeing and self confidence for example some people may believe they have a special relationship with God or celebrities|
inappropriate behaviour e.g. wearing unusual clothing or taking clothes off in public|
{003-121yparticipate in risky behaviour or activities, such as trying to jump out of a moving car}{012-121y, excessive gambling or shopping}|
{009-121yinappropriate sexual behaviour e.g. using explicit sexual language or talking or thinking excessively about sex}}</span>

![screen shot 2017-11-08 at 12 36 09](https://user-images.githubusercontent.com/26304634/32549459-702813c0-c481-11e7-8320-d85539505420.png)

**Comment by katbow** [comment]
@ellemindwave how is this meant to look? Is it normal text?

**Comment by ellemindwave** [comment]
@katbow I think so, but I'm just double-checking for you! Will update asap

**Comment by katbow** [comment]
@ellemindwave FYI on this, I added the css from #767 
```
.e24subtext {
  font-size: 12px !important;
  font-style: italic;
}
```

which makes the bulleted list look like this, as it is within a `<span>` with that class.

![image](https://user-images.githubusercontent.com/1287388/32781864-6a262bee-c93e-11e7-903e-a97ee0d70c1f.png)

I'm not sure if you would like to pass this along to see if that's the desired result!

**Comment by ellemindwave** [comment]
@katbow yes, they have just responded saying that small and italic is the desired effect! 
Thanks
