### ISSUE TITLE
E24 - Answer option too long so leaving a gap 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#770]
Line too long so leaving space.

Answers should always be on the same line as their respective check-box

![screen shot 2017-11-08 at 12 43 22](https://user-images.githubusercontent.com/26304634/32549732-6f25ba30-c482-11e7-8126-0f10f4bf3c30.png)

**Comment by ellemindwave** [comment]
Display when using 100% on a smaller screen – this is happening on pretty much all of the multiple choice questions. 

![screen shot 2017-11-08 at 12 44 22](https://user-images.githubusercontent.com/26304634/32549782-9ca7f0f4-c482-11e7-9ba0-cbb234a69862.png)

**Comment by katbow** [comment]
@ellemindwave does this happen for all input types? e.g. radio button, checkboxes, etc.

**Comment by katbow** [comment]
@ellemindwave whoops nvm just answered that one myself.

**Comment by katbow** [comment]
With radio buttons
![image](https://user-images.githubusercontent.com/1287388/32788775-0ecbaf58-c952-11e7-8be2-9a7366cfb3d6.png)

With checkboxes
![image](https://user-images.githubusercontent.com/1287388/32788883-4fd3ed8a-c952-11e7-83f3-60e881b383a0.png)
