### ISSUE TITLE
E24 - Library Links are not working on all conclusions

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#772]
Library Links are not working on all conclusions – when clicking on link get this message:

![screen shot 2017-11-08 at 16 44 35](https://user-images.githubusercontent.com/26304634/32561429-21ab1d64-c4a4-11e7-8563-c8d3476b2dbd.png)

https://ldmw-staging.herokuapp.com/Health/Information.aspx?ArticleID=CFHG0073SLEEP

![screen shot 2017-11-08 at 16 45 09](https://user-images.githubusercontent.com/26304634/32561464-33a3b49a-c4a4-11e7-8bb7-9b69a7d6e880.png)

**Comment by reddog** [comment]
@ellemindwave I believe this issue was down to the E24 team which I raised with them.  Mike's made a change that he thinks should fix this.  It needs re-testing to ensure the fix is good, but that should be about it.
