### ISSUE TITLE
Favicon still not there

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#775]
It may still be a caching issue, but surely the favicon can't take this long to appear?! 
Can anything be done to make it appear?

**Comment by katbow** [comment]
@ellemindwave was it showing in the first place with the old one? I used the same format as before, but I think in both cases it needs to be .ico file format (we were given .png). See [this answer](https://stackoverflow.com/a/23734416) for favicon requirements.

**Comment by ellemindwave** [comment]
@katbow I have just put it through a favicon generator - let's see if this works!

[favicons.zip](https://github.com/mindwaveventures/cms/files/1470567/favicons.zip)


<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

**Comment by katbow** [comment]
Finally got this showing on my local version!
![image](https://user-images.githubusercontent.com/1287388/32793803-e0490826-c95e-11e7-93c8-ad269eb5beb8.png)


I double checked on the live site to see if the file path I used would be relevant (as some things are bundled together). Should work the same when it's deployed 🤞 👍

**Comment by ellemindwave** [comment]
Awesome, thanks @katbow . Finally!
