### ISSUE TITLE
Site-wide error page to appear if site is down

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#779]
If the site, for whatever reason, happens to be fully down and not working, what are our options for displaying a site-wide error page that is in Good Thinking branding to alert users that we are working on the glitch and that the site should be back up again soon?

@reddog had a couple of initial suggestions for how to fulfil this:

a.  a "maintenance" page - maybe it's possible to put Wagtail in "maintenance" mode?

b.  if the site *fully* isn't working, then there would have to be a page *somewhere else*.  This page would ideally be styled and branded the same as the rest of the Good Thinking site.
To be able to switch over to a page *somewhere* else we'd have to do some DNS stuff - which is possible.

It would be good to know the feasibility and possible time estimations for both of the above options so as to choose what is the best solution to go for.

**Comment by Danwhy** [comment]
I know heroku has a maintenance mode which you can configure to serve a custom page: https://devcenter.heroku.com/articles/maintenance-mode, and it looks aws have something similar: https://aws.amazon.com/blogs/aws/create-a-backup-website-using-route-53-dns-failover-and-s3-website-hosting/
 
Creating the error page would probably be very similar to #778. After that it's just the setup, which for heroku would be fairly quick, but for aws we'd probably require some assistance from @reddog

**Comment by ellemindwave** [comment]
Here is a mock up of the "site down" page.

@jaderichardson will provide the png for the image below.

Hex code for background colour is #4ea1af
Text styling to be as per rest of site (eg montserrat, #04091a)
All text outside the png to be live text.

![33183099-688099a0-d06e-11e7-8653-9d6d07055f16](https://user-images.githubusercontent.com/26304634/33183762-17f6bd86-d071-11e7-98cb-76f33aa9c316.png)

**Comment by ellemindwave** [comment]
Small / mobile version will be added tomorrow.

**Comment by ellemindwave** [comment]
![33183529-1daee394-d070-11e7-9ad0-7994fd8a9725](https://user-images.githubusercontent.com/26304634/33183803-3b073f26-d071-11e7-8187-c74b6d5b731e.png)

**Comment by ellemindwave** [comment]
@Danwhy from conversations today, it seems likely that we will remain on Heroku for the time being, therefore only the Heroku maintenance page is needed

**Comment by iteles** [comment]
Thanks @ellemindwave @jaderichardson - would you be able to send us the assets for these designs please?

**Comment by sarahwelton** [comment]
![down mobile](https://user-images.githubusercontent.com/26305143/33203849-5fcf352e-d0f9-11e7-9e33-d59bf39a0aa2.png)

Mobile version (for mobile up to portrait tablet).

**Comment by jaderichardson** [comment]
Hex code for background colour is #4ea1af

![down mobile 2](https://user-images.githubusercontent.com/33458059/33209563-58e0de24-d10e-11e7-90eb-d0eb7da3a747.png)

**Comment by Danwhy** [comment]
@jaderichardson Do you have a version of these images with a transparent background?

**Comment by jaderichardson** [comment]
@Danwhy  ![transparent desktop-04](https://user-images.githubusercontent.com/33458059/33210863-bf5e3f8e-d113-11e7-9515-bdd806ea9ef9.png)

![transparent mobile-04](https://user-images.githubusercontent.com/33458059/33210875-cccfca52-d113-11e7-85b5-0e6c7d4039b8.png)

**Comment by Danwhy** [comment]
@ellemindwave Where should the 'contact us' link on this page lead? The site will be down, so the normal contact page will be unavailable

**Comment by ellemindwave** [comment]
@Danwhy please can it be a mailto link to info@good-thinking.uk ? 

Thanks!

**Comment by Danwhy** [comment]
This can be tested by going to the settings on the heroku app for staging (https://dashboard.heroku.com/apps/ldmw-staging/settings) and turning on maintenance mode, then visiting the staging site. (It also already works on live)
