### ISSUE TITLE
Site down 

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#786]
Here is a mock up of the "site down" page.

@jaderichardson will provide the png for the image below.

Hex code for background colour is #4ea1af
Text styling to be as per rest of site (eg montserrat, #04091a)
All text outside the png to be live text.

![gt-site-down_20171123](https://user-images.githubusercontent.com/26305143/33183099-688099a0-d06e-11e7-8653-9d6d07055f16.png)

Small / mobile version will be added tomorrow.

**Comment by jaderichardson** [comment]
![down](https://user-images.githubusercontent.com/33458059/33183529-1daee394-d070-11e7-9ad0-7994fd8a9725.png)

**Comment by ellemindwave** [comment]
Merged into #779
