### ISSUE TITLE
Styled 404 error page

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#787]
Here is a mock up of the 404 page. 

@jaderichardson will provide the png for the image below.

- Text styling to be as per rest of site (eg montserrat, #04091a)

- All text outside the png to be live text. 

![gt screen 404_20171123](https://user-images.githubusercontent.com/26305143/33183294-29ca22ac-d06f-11e7-8d42-e4a2b39bd9a7.png)

Small / mobile version will be added tomorrow.

**Comment by jaderichardson** [comment]
![404](https://user-images.githubusercontent.com/33458059/33183494-fc1ceb0e-d06f-11e7-98dd-652caa86ff55.png)

**Comment by iteles** [comment]
Thanks @ellemindwave @jaderichardson - would you be able to send us the assets for these designs please?

**Comment by sarahwelton** [comment]
Hi @iteles - the image that Jade has uploaded _is_ the asset. We assumed that it would be much easier to develop with one image rather than individual assets. We are short of time and don't want to complicate the responsiveness with individual pieces to code. 

Would you like us to also email or Slack the image for ease?

**Comment by sarahwelton** [comment]
![404 mobile](https://user-images.githubusercontent.com/26305143/33203864-710deeca-d0f9-11e7-9de9-f7a3a8671704.png)


Mobile version (for mobile up to portrait tablet).

**Comment by Danwhy** [comment]
@sarahwelton @jaderichardson Is there a different image file for the mobile version?

**Comment by ellemindwave** [comment]
^ @Danwhy yes, as posted above by @sarahwelton ?

**Comment by Danwhy** [comment]
@ellemindwave Sorry, I meant the image without the text

**Comment by jaderichardson** [comment]
![404 mobile 2](https://user-images.githubusercontent.com/33458059/33209554-4cffd416-d10e-11e7-89bf-26ab2771b40e.png)

**Comment by jaderichardson** [comment]
@Danwhy 

![transparent desktop-05](https://user-images.githubusercontent.com/33458059/33210884-dc5f67d4-d113-11e7-9adc-538901dc2de6.png)

![transparent mobile-03](https://user-images.githubusercontent.com/33458059/33210889-df94bb34-d113-11e7-8b62-07be0af49007.png)

**Comment by Danwhy** [comment]
This can be tested on staging now: https://ldmw-staging.herokuapp.com/non-existent/
