### ISSUE TITLE
E24 - Add button at end of traversal 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#791]
Add a button to end traversal when a user gets to the end of the self-assessment. Currently they have nowhere to go.

**Context:**
"How do you end this traversal? The only choice is summary or previous if I click on summary I don’t have anywhere to go either
![image001](https://user-images.githubusercontent.com/26304634/33559775-cb64c22c-d905-11e7-8a53-9a817aced1dc.jpg)"

**Comment by reddog** [comment]
A couple of questions to clarify the requirements here:

1.  The E24 integration simply displays **whatever** is passed in from E24 to the user.  How do we determine that we're on the last page of a traversal?  By the absence of a *next* button?  Will that work in all occasions?
**This is when the final conclusions/dispositions have been given**

2.  What should the button text be?
**Finish Assessment**

3.  Where should the button appear?
**@sarahwelton any preferences?**

4.  What should happen as a result of the user pressing this newly added button?
**Finish the assessment and directed back to the GT homepage? @sarahwelton any preferences**

5.  Are there any other places where this button is required?
**No**

**Comment by ellemindwave** [comment]
From Kat E24 / Elle:

1.     The E24 integration simply displays whatever is passed in from E24 to the user. How do we determine that we're on the last page of a traversal? By the absence of a next button? Will that work in all occasions?  **This is when the final conclusions/dispositions have been given**

2.     What should the button text be?  **Finish assessment**

3.     Where should the button appear?  Your decision - @sarahwelton ?

4.     What should happen as a result of the user pressing this newly added button? **Leave the  assessment and go back to the Good Thinking homepage?** @sarahwelton 

5.     Are there any other places where this button is required? No

6.     How urgent is it that this is implemented? **It confused our testers but it is not mission critical – its really a UX thing so will leave it to your decision**

**Comment by reddog** [comment]
@ellemindwave Does the destination for the *Finish* button have to be editable in the CMS or should it be hardcoded?

**Comment by sarahwelton** [comment]
1. I think so

2. *"Homepage"* (from _full_ self assessment)

3. Where the current "next" button is

4. Goes to GT homepage

5. Agreed!

**Comment by sarahwelton** [comment]
Hardcoded is fine for now if the additional time for editable is significant.

**Comment by reddog** [comment]
Thanks @sarahwelton. By `"Homepage" (from full self assessment)`, do you mean the button should have a different label if it's not on the *full* self assessment page?

**Comment by ellemindwave** [comment]
Homepage - will go to the relevant homepage that they came from. So, if they came from full assessment (from beta banner) then it will mean that they go back to the main homepage. 
If they came from the Anxiety assessment, then they would go back to the anxiety homepage etc. 

@sarahwelton should the button still just say 'Homepage' regardless of which homepage they are being directed back to? or 'Anxiety homepage', 'Depression homepage' etc

**Comment by reddog** [comment]
@ellemindwave So the *Homepage* button is more of a *back* button, hence can't be hardcoded to a single destination (eg the homepage of the site)?

**Comment by ellemindwave** [comment]
@reddog For now, hardcoded 'homepage' and it goes to the main homepage, no matter which assessment they have just completed. Sarah says we can think about this more in our user testing 👍

**Comment by reddog** [comment]
To get to a *conclusions* page go to the self assessment page at https://www.good-thinking.uk/self-assessment and answer as follows:

-Myself
- Male, 50
- no difficulty 
- 7-8 hours
- Under 15 mins
- Less that one hour
- No 
- No
