### ISSUE TITLE
Header banner transparent, not white, on first load

### ISSUE THREAD

**Issue by reddog** [LDMW/cms#86]
To reproduce:

1. Go to http://ldmw.herokuapp.com
2. Top *Beta...* banner will be shown with transparent background.
3. Scrolling correctly sets the banner background to be white. This is retained when scrolled fully to the top of the page.

**Comment by samhstn** [comment]
I think this may have been asked for in LDMW/app#433 and LDMW/app#444

@reddog could you confirm that this is wanted to be changed.

If this is to be changed, how would you like the transparency?

**Comment by Cleop** [comment]
@shouston3 see #249 - you're right it was intentional initially but it looks like the proposal is now white.

**Comment by Cleop** [comment]
Closing as a duplicate of #249
